### ISSUE TITLE
[Bug] Order button page not mobile responsive

### ISSUE THREAD

**Issue by ifedan-ed** [FOSSBilling/FOSSBilling#1012]
**Is your feature request related to a problem? Please describe.**
When using the order module as a link e.g. domain.com/orderbutton?order=3, the resulting page is not mobile reponsive
**Describe the solution you'd like**
Is it possible for the resulting page to fit in well, either mobile or desktop
**Describe alternatives you've considered**

**Additional context**

**Comment by BelleNottelling** [comment]
Please include screenshots for front-end issues

**Comment by John-S4** [comment]
Note to all: Please give Issues accurate and descriptive titles. Not just [Feature request]

**Comment by BelleNottelling** [comment]
Hello, can you please provide screenshots for the issue(s) described here?

**Comment by BelleNottelling** [comment]
Closing since we haven't gotten any response
