### ISSUE TITLE
[Feature Request] Ordermodule buttons & email write out in the invoice html and pdf

### ISSUE THREAD

**Issue by ifedan-ed** [FOSSBilling/FOSSBilling#1014]
**Is your feature request related to a problem? Please describe.**
The register and login buttons in the order seem offset
**Describe the solution you'd like**
If the buttons can be made to be at least look the same. On the invoice html, there is a lot of space between the name, email and the corresponding values, can the email address be made to wrap? This also applies to the listing of:
1. I want to register my own domains 
2. I want to transfer my own domains
Could this two be made to look more consistent in mobile?
**Describe alternatives you've considered**

**Additional context**

**Comment by BelleNottelling** [comment]
Please include screenshots for front-end issues

**Comment by BelleNottelling** [comment]
Regarding the invoice PDF, we have support for using custom CSS for them, you can find the newly created documentation on this functionality on [our documentation](https://fossbilling.org/docs/customizing-fossbilling/invoice_pdf)

**Comment by BelleNottelling** [comment]
Hello, can you please provide screenshots for the issue(s) described here?

**Comment by BelleNottelling** [comment]
Closing since we haven't gotten any response
