### ISSUE TITLE
[Bug] Unknown "encore_entry_link_tags" function.

### ISSUE THREAD

**Issue by elixon01** [FOSSBilling/FOSSBilling#1041]
### Describe the bug

Unknown "encore_entry_link_tags" function.

I just upgraded to 4.0 and it gives me this error when I enter the administrator panel : Unknown "encore_entry_link_tags" function.

¡¡¡¡¡¡I can't log in to the admin panel!!!!!!!

ERROR
Unknown "encore_entry_link_tags" function.

[Look for detailed error explanation](https://fossbilling.org/docs/en/latest/search.html?q=Unknown+%22encore_entry_link_tags%22+function.&check_keywords=yes&area=default)

Powered by [FOSSBilling](https://fossbilling.org/)

### How to reproduce

Unknown "encore_entry_link_tags" function

### Expected behavior

Unknown "encore_entry_link_tags" function.

I just upgraded to 4.0 and it gives me this error when I enter the administrator panel : Unknown "encore_entry_link_tags" function.

¡¡¡¡¡¡I can't log in to the admin panel!!!!!!!

ERROR
Unknown "encore_entry_link_tags" function.

[Look for detailed error explanation](https://fossbilling.org/docs/en/latest/search.html?q=Unknown+%22encore_entry_link_tags%22+function.&check_keywords=yes&area=default)

Powered by [FOSSBilling](https://fossbilling.org/)

### FOSSBilling version

0.4.0

### Module version

encore_entry_link_tags

### Information

Unknown "encore_entry_link_tags" function.

I just upgraded to 4.0 and it gives me this error when I enter the administrator panel : Unknown "encore_entry_link_tags" function.

¡¡¡¡¡¡I can't log in to the admin panel!!!!!!!

ERROR
Unknown "encore_entry_link_tags" function.

[Look for detailed error explanation](https://fossbilling.org/docs/en/latest/search.html?q=Unknown+%22encore_entry_link_tags%22+function.&check_keywords=yes&area=default)

Powered by [FOSSBilling](https://fossbilling.org/)

### Additional context

Unknown "encore_entry_link_tags" function.

I just upgraded to 4.0 and it gives me this error when I enter the administrator panel : Unknown "encore_entry_link_tags" function.

¡¡¡¡¡¡I can't log in to the admin panel!!!!!!!

ERROR
Unknown "encore_entry_link_tags" function.

[Look for detailed error explanation](https://fossbilling.org/docs/en/latest/search.html?q=Unknown+%22encore_entry_link_tags%22+function.&check_keywords=yes&area=default)

Powered by [FOSSBilling](https://fossbilling.org/)

**Comment by BelleNottelling** [comment]
This should only happen if the updater was unable to replace some of the files.
Please try performing a manual update, that should resolve any issues
https://fossbilling.org/docs/maintaining-fossbilling/updating#manually-updating-fossbilling

**Comment by elixon01** [comment]
I already did it.. I even installed it from scratch. I deleted
everything and reinstall it from the zip file and nothing. it still
throws the same error

2023-04-03 15:19 GMT-05:00, Belle Aerni ***@***.***>:

**Comment by BelleNottelling** [comment]
Hi there. After working with someone on our Discord server who was experiencing the same error, we determined that it was caused by FOSSBilling being under a sub-directory. I've submitted a [fix](https://github.com/FOSSBilling/FOSSBilling/pull/1048) for this issue, however it's always recommended to use a sub-domain instead of a sub-directory as the latter option can cause odd and behavior and unexpected issues

**Comment by elixon01** [comment]
Hello, this new update shows the administrator with errors in the login to
start section and when the data is entered and the section starts... It
does NOT start the section and only shows errors in the login:

{"result":null,"error":{"message":"Check your login details","code":403}}
