### ISSUE TITLE
[Bug] Canned responses aren't working in 0.4.0 (WebPack)

### ISSUE THREAD

**Issue by zetlex** [FOSSBilling/FOSSBilling#1042]
### Describe the bug

Canned responses don't work, when pressing nothing happens.

I have this in my devtools.

![image](https://user-images.githubusercontent.com/82660728/229566376-cd75c28e-fcb0-4a4a-9ab5-e25c881ad49e.png)
![image](https://user-images.githubusercontent.com/82660728/229566387-bf6a0a9c-0323-4283-9477-6cf92226b927.png)

I was told that webpack is causing the issue by adly.

I can also type in the Canned responses field.

### How to reproduce

Update to FossBilling 0.4.0

Reply to a ticket and you can see the problem.

### Expected behavior

It copies the message into the text field for you.

### Screenshots

Screenshots above.

### FOSSBilling version

0.4.0

### Module version

N/A

### Device

Desktop, Smartphone

### Information

Global

### Additional context

Talked with Adly in the discord, he seems to know what is causing the problem.

**Comment by BelleNottelling** [comment]
I am unable to replicate this. Seems like a bit of a long shot, but is it possible there was something cached in your browser / an extension causing the issue?
![Animation](https://user-images.githubusercontent.com/17304943/229694742-ad134475-fc54-4e12-8fa3-801d2f295cd1.gif)

**Comment by zetlex** [comment]
I tried using a blank browser and deleting my /data/cache/ and I still have the same problem.

**Comment by shmshd** [comment]
@zetlex Which exact page are you trying this? Error is due to CKEditor not being initialized on that page to set canned response.

**Comment by BelleNottelling** [comment]
I'm going to close this as nobody on the team has been able to replicate it and the original reporter has since gone quiet.
