### ISSUE TITLE
[Feature Request] Bring the badges back for navbar items

### ISSUE THREAD

**Issue by zetlex** [FOSSBilling/FOSSBilling#1043]
**Is your feature request related to a problem? Please describe.**
It's really annoying to navigate the admin dashboard after the new update.

**Describe the solution you'd like**
I think you could improve the admin dashboard by making changes to the nav bar.

Right now when you leftclick Invoices a dropdown appears and you need to click twice to access invoices.
I think it would be much smarter to make the dropdown appear on hover and if you were to click it would take you to the invoices tab with one click.

Also I think the red circles should be brought back as I used them everyday, now I need to navigate to the tickets section to see, if there are any tickets open.
![image](https://user-images.githubusercontent.com/82660728/229570500-27339407-2e4d-4051-9d3a-6cfb9bfc0b80.png)

**Comment by admdly** [comment]
Thank you for raising this issue - the notifications icons have been restored in the latest release. 🙂
