### ISSUE TITLE
Rework the permission system

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#1050]
The permission system for administrators needs a complete rework. Currently, it's all or none for modules and more oriented towards individual staff accounts.

* Not making the permissions based on groups makes groups serve no purpose at all. It also makes editing permissions for multiple accounts harder than it should be. Let's just make things based on account groups.
* The all or none situation mostly makes the permission system unusable. You either give full control for a module or just outright disable the whole thing. For example, a support agent should be able to use the "Support" module but not adjust its administrative settings. The same goes for the "System" module and such. Disallowing the module will break the dashboard.

**A possible approach**:
A permission system using different keys for individual actions would probably do the job. Some examples:
* `support.view_tickets`
* `system.purge_cache`
* `client.suspend`

**Comment by BelleNottelling** [comment]
Granular permissions are now a thing and group-level permissions are a part of #1869, so I'm going to close this as completed now
