### ISSUE TITLE
[Feature Request] IPv6 support

### ISSUE THREAD

**Issue by g00g1** [FOSSBilling/FOSSBilling#1074]
**Is your feature request related to a problem? Please describe.**
IPv4 address exhaustion is not a myth and causes ISPs to workaround address space limitation by using NAT as well as IPv6.

**Describe the solution you'd like**
IPv6 support where IP addresses are processed (login history for example)

**Describe alternatives you've considered**
\-

**Additional context**
I am connected via IPv6 to the demo instance and the IP column contains blank space. I suppose it is due to inappropriate handling of IPv6 address.
![image](https://user-images.githubusercontent.com/91201021/230147953-e360c67a-992c-4be2-9927-124e3dee3df9.png)

**Comment by jaapmarcus** [comment]
Demo mode has ip logging disabled. It is only available during the setup. Nothing is wrong with it...

**Comment by BelleNottelling** [comment]
Yeah, IP logging is supposed to be globally disabled in the demo. FOSSBilling has zero issue with IPV6 IP addresses.
Regarding the two that were logged, I believe that was from when the demo was getting fixed and I removed them from the history
