### ISSUE TITLE
[Bug] Server Manager DirectAdmin Error: Invalid Domain Name

### ISSUE THREAD

**Issue by mxroute** [FOSSBilling/FOSSBilling#1085]
### Describe the bug

I seem unable to activate a DirectAdmin account on my first order attempt. It's plausible that I'm doing something wrong, but the error "Invalid Domain Name" makes me think it isn't properly parsing my domain name for the order. It is, admittedly, a less common TLD so perhaps relevant?

### How to reproduce

1. Place order for hosting, set to use existing owned domain, use domain "jarland.me"
2. Attempt to provision service with DirectAdmin

### Expected behavior

I expected it to provision

### Screenshots

Screenshot of order: https://files.freesocial.co/f.php?h=1K2JFboa&p=1
Screenshot of activation attempt: https://files.freesocial.co/f.php?h=15wnbLmw&p=1

### FOSSBilling version

0.4.2

### Device

Desktop

**Comment by jaapmarcus** [comment]
I don't know if we have the ability to test Direct admin integration but it is strange that it is failing.

If you are able to share an reseller a account so we can test easier it would be awesome...

**Comment by admdly** [comment]
Thanks for raising this 🙂  - I’ll test this and fix ASAP. In the future, I’ll also add DirectAdmin to my pre-release testing regime to catch any issues.

**Comment by admdly** [comment]
I've identified this is due to the domain TLD missing the period, which is required. I'll get a patch up to check for its presence and add it if missing shortly to improve the user experience.
