### ISSUE TITLE
[Bug] WHM createacct fails when username  empty

### ISSUE THREAD

**Issue by kyotr** [FOSSBilling/FOSSBilling#1086]
### Describe the bug

When a customer try to order a hosting plan or when i try to place an order manually; Activating order fails. on the WHM control panel the domain is created  

`[08-Apr-2023 07:38:21 UTC] Idle timeout reached for "https://**********.com:2087/json-api/createacct".
`
On server Management when i try to sync with server it says 
`WHM server response error calling action accountsummary: "You must specify a user or domain to get a summary of" (9999)`

![image](https://user-images.githubusercontent.com/22255109/230712556-7198c456-fe98-48ed-b1e3-3d3e980923b4.png)
![image](https://user-images.githubusercontent.com/22255109/230712707-5db3bbf0-a31f-4ceb-8e08-fce1238e0f9b.png)

 

### How to reproduce

Go to Order -> New Order ->  select client / product -> Place Order without usename or password

or 

Place order from client interface and make payment   

### Expected behavior

1. Place order
2. . Activate order.
3. Send email to client with login information (username password)

### FOSSBilling version

0.4.2

**Comment by KY4U** [comment]
I believe the issue here is that the Fossbilling script used to call the API times out.
_Idle timeout reached for "https://**********.com:2087/json-api/createacct"_

If you check WHM you'll see that the account is created (it takes a few minutes).
Fossbilling is showing a blank user because the account creation has not completed yet, therefore no username.

I'm seeing the same problem where the script times out after 30 seconds, even though the account creation is still occurring on the server.

**Comment by rubenscmf** [comment]
Have resolution? I have the same problem

**Comment by kyotr** [comment]
> Have resolution? I have the same problem

Still have the same issue...

**Comment by rubenscmf** [comment]
I'm in contact with people on discord trying to find a solution, have you made any progress @kyotr ?

**Comment by kyotr** [comment]
unfortunately no progress at all

**Comment by KY4U** [comment]
This is more of a band aid than a fix, but it allows me to activate accounts...

In yourwebroot\vendor\symfony\http-client\Response\TransportResponseTrait.php, around line 191, comment out the following two lines:

```
$multi->handlesActivity[$j] = [new ErrorChunk($response->offset, sprintf('Idle timeout reached for "%s".', $response->getInfo('url')))]; 
$multi->lastTimeout ?? $multi->lastTimeout = $lastActivity;
```

Add the following line after the two lines you comment out:
`continue;`

**Comment by admdly** [comment]
> This is more of a band aid than a fix, but it allows me to activate accounts...
> 
> In yourwebroot\vendor\symfony\http-client\Response\TransportResponseTrait.php, around line 191, comment out the following two lines:
> 
> ```
> $multi->handlesActivity[$j] = [new ErrorChunk($response->offset, sprintf('Idle timeout reached for "%s".', $response->getInfo('url')))]; 
> $multi->lastTimeout ?? $multi->lastTimeout = $lastActivity;
> ```
> 
> Add the following line after the two lines you comment out: `continue;`

If your band aid solution works, then increasing the HTTP Client idle timeout should also work - have you actually tried this? This was previously suggested but not definitively confirmed or ruled out.

Can you try increasing the HTTP Client timeout on line 392 of `library/Server/Manager/Whm.php` to a higher value and reporting back?

**Comment by KY4U** [comment]
@admdly I backed out my changes and increased HTTP Client timeout as you suggested.  That did the trick.  Account activation working properly now.

Thanks for the help.

**Comment by admdly** [comment]
@KY4U glad it's now working for you. 🙂 Could you advise what you raised the timeout to, and I will update the code for the next release?

**Comment by KY4U** [comment]
@admdly  I set the timeout to 180 for my testing,

**Comment by rubenscmf** [comment]
> @admdly I set the timeout to 180 for my testing,

Good job, this configuration solved it!
