### ISSUE TITLE
[Feature Request] A html_custom folder for themes

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#1095]
Since the template files of our official themes are overwritten with each update, the only sensible way to modify the templates seems to be to copy the theme and create a new one of its own.

Logically, it doesn't make much sense to copy a whole theme just to edit a template or two. Creating a new folder that won't be overwritten with each update makes sense to me.

This is where the source paths for the templates are defined. It should be easy to add a `html_custom` folder that will be prioritized here:
https://github.com/FOSSBilling/FOSSBilling/blob/534b1ca4d794d3df2cfba23e94636b1f5c713c18/src/modules/Page/Service.php#L48-L51

I'm not sure about what to name the folder though.

![image](https://user-images.githubusercontent.com/35808275/230957369-df2bcac7-8b4d-4c4a-965b-74b972fa2386.png)
![image](https://user-images.githubusercontent.com/35808275/230956853-22b7d2fe-6c39-4335-b187-166b0f08ca42.png)

**Comment by John-S4** [comment]
Agree that this makes a lot of sense, it's overkill to need to create a new theme just to make one html or css change. 

As for the folder name, 'custom' would be fine, or maybe 'overrides'.

**Comment by ichilver** [comment]
This gets my vote too. 👍
