### ISSUE TITLE
Client password reset results in 404 when clicking the confirmation link in email

### ISSUE THREAD

**Issue by m4rkstevenson** [FOSSBilling/FOSSBilling#1098]
When a client requests a password reset, clicking the link received in an email redirects them to a 404 not found error page 

Page /reset-password-confirm/<redacted-token> not found.

Log entry...

Unable to find template "mod_pagereset-password-confirm<redacted-token>.html.twig" (looked into: /home/<redacted>/public_html/members/themes/huraga/html, /home/<redacted>/public_html/members/modules/Page/html_client).

I've checked the folders and can confirm the template to reset the password is missing

members sub-directory mapped to vhost members.domain.co.uk

**Comment by admdly** [comment]
This issue does not appear in the latest version of FOSSBilling. Could you update to version 0.4.3 once released and let us know if you still have problems?

**Comment by m4rkstevenson** [comment]
Still ongoing in 0.4.3... see log entry...

[01-May-2023 13:55:37 UTC] Unable to find template "mod_page_reset-password-confirm_<token>.html.twig" (looked into: /home/<path>/public_html/members/themes/huraga/html, /home/<path>/public_html/members/modules/Page/html_client).
[01-May-2023 13:55:37 UTC] Page /reset-password-confirm/<token> not found

**Comment by admdly** [comment]
> Still ongoing in 0.4.3... see log entry...
> 
> 
> 
> [01-May-2023 13:55:37 UTC] Unable to find template "mod_page_reset-password-confirm_<token>.html.twig" (looked into: /home/<path>/public_html/members/themes/huraga/html, /home/<path>/public_html/members/modules/Page/html_client).
> 
> [01-May-2023 13:55:37 UTC] Page /reset-password-confirm/<token> not found

Are you using a custom theme, or running in a subdirectory? 

There endpoint does exist and there is a theme associated with confirming.

**Comment by m4rkstevenson** [comment]
> > Still ongoing in 0.4.3... see log entry...
> > [01-May-2023 13:55:37 UTC] Unable to find template "mod_page_reset-password-confirm_.html.twig" (looked into: /home//public_html/members/themes/huraga/html, /home//public_html/members/modules/Page/html_client).
> > [01-May-2023 13:55:37 UTC] Page /reset-password-confirm/ not found
> 
> Are you using a custom theme, or running in a subdirectory?
> 
> There endpoint does exist and there is a theme associated with confirming.

I’m using the default themes. I moved from a sub-directory to a sub-domain before updating to 0.4.2 It might be useful to know that I migrated from BoxBilling, I have updated the DB schema twice since without errors.
