### ISSUE TITLE
[Bug] FOSSBilling + ISPConfig 3, deleting a customer damages the database

### ISSUE THREAD

**Issue by ozz-is-here** [FOSSBilling/FOSSBilling#1105]
### Describe the bug

I'm trying to use FOSSBilling with ISPConfig 3.

The steps I did were:

1. In ISPConfig I created a remote user and gave him all permissions.
2. Connected FOSSBilling to ISPConfig using the credentials for the remote user. The credentials are correct.
3. Registered a customer.
4. Tried to order a service, but received an error.
5. Deleted the customer.
6. Now I can't login and register as a customer, only as the admin, and I must restore the database from a backup.

Software versions:

* ISPConfig 3.2.9p1
* FOSSBilling 0.4.2
* PHP 8.0 with all the needed extensions installed
* MariaDB 15.1
* Apache 2.4.56
* Debian 11

### How to reproduce

1. Register a customer
2. Attempt to order a service and receive the error "There is no user account for this user name. (9999)"
3. Delete the customer
4. Get the "Model Client not found in the database" error on the main page

### Expected behavior

Deleting a customer doesn't damage the database.

### FOSSBilling version

FOSSBilling 0.4.2

**Comment by BelleNottelling** [comment]
The database isn't broken. You still have an active session for that client, which then causes an error because it can no longer find the ("active") user in the database. It just needs to destroy that session rather than showing the error message.

With that being said.. the ISPConfig server manager doesn't work: https://github.com/FOSSBilling/FOSSBilling/issues/890

**Comment by ozz-is-here** [comment]
Sorry for the false alarm. I didn't know about that.

**Comment by ozz-is-here** [comment]
I'm sorry to bother you again, but could you please change the message ("Model Client not found in the database") or force destroy the session by default if the user with this session does not exist?

**Comment by BelleNottelling** [comment]
> I'm sorry to bother you again, but could you please change the message ("Model Client not found in the database") or force destroy the session by default if the user with this session does not exist?

Yes, I have it on my to-do list
