### ISSUE TITLE
Object of class Symfony\Component\HttpClient\Response\CurlResponse could not be converted to string[Bug]

### ISSUE THREAD

**Issue by wocsol** [FOSSBilling/FOSSBilling#1132]
### Describe the bug

i have setup resellerclub as my domain registrar and when i am trying to search a new domain on user panel .. i am getting this error .. 
Object of class Symfony\Component\HttpClient\Response\CurlResponse could not be converted to string

### How to reproduce

i have setup resellerclub as my domain registrar and when i am trying to search a new domain on user panel .. i am getting this error .. 
Object of class Symfony\Component\HttpClient\Response\CurlResponse could not be converted to string

### Expected behavior

i have setup resellerclub as my domain registrar and when i am trying to search a new domain on user panel .. i am getting this error .. 
Object of class Symfony\Component\HttpClient\Response\CurlResponse could not be converted to string

### Screenshots

i have setup resellerclub as my domain registrar and when i am trying to search a new domain on user panel .. i am getting this error .. 
Object of class Symfony\Component\HttpClient\Response\CurlResponse could not be converted to string

### FOSSBilling version

0.4.2

### Device

Desktop

### Information

i have setup resellerclub as my domain registrar and when i am trying to search a new domain on user panel .. i am getting this error .. 
Object of class Symfony\Component\HttpClient\Response\CurlResponse could not be converted to string

### Additional context

i have setup resellerclub as my domain registrar and when i am trying to search a new domain on user panel .. i am getting this error .. 
Object of class Symfony\Component\HttpClient\Response\CurlResponse could not be converted to string

**Comment by admdly** [comment]
Thank you for raising this issue - I have raised a PR with a fix which should be merged soon and included in the next release.

**Comment by wocsol** [comment]
Thanks for the good working you guys are doing very good for this industry, soon will start donating for your work once i will start generating income , thanks again Sent from my iPhoneOn 22-Apr-2023, at 6:45 AM, Adam Daley ***@***.***> wrote:﻿
Thank you for raising this issue - I have raised a PR with a fix which should be merged soon and included in the next release.
