### ISSUE TITLE
Format Time invoice creater not same as time server/user [Bug]

### ISSUE THREAD

**Issue by binsaryunus** [FOSSBilling/FOSSBilling#1151]
### Describe the bug

change time on fossbilling config.php form UTC to GMT but my invoice not change

### How to reproduce

1. go to config.php
2. see the line timezone
3. set default utc to gmt
4. save it
5. see the client invoice and got error

### Expected behavior

should change string of timezone ?

### Screenshots

![image (2)](https://user-images.githubusercontent.com/66997989/233812733-20ef1fe4-e233-43ab-9502-b835fd485273.png)
![image (1)](https://user-images.githubusercontent.com/66997989/233812736-a8762fae-da37-420d-8b02-7a57eec07460.png)
![image](https://user-images.githubusercontent.com/66997989/233812737-09c1d2c7-5b51-4bcf-a1d2-986247f563ee.png)

### FOSSBilling version

FOSSBILLING VERSION 0.4.2 PHP VERSION 8.0.26

**Comment by BelleNottelling** [comment]
GMT+7 isn't really a valid timezone in PHP (which is what FOSSBilling runs on).
Please try using this list to get the correct one: https://www.php.net/manual/en/timezones.php

**Comment by binsaryunus** [comment]
![image](https://user-images.githubusercontent.com/66997989/233843293-a2b25af1-b726-489f-9554-6fec4c1d174e.png)
i already fix it i change php time zone to Asia/Jakarta
