### ISSUE TITLE
[Feature Request] DNS Management for domain

### ISSUE THREAD

**Issue by binsaryunus** [FOSSBilling/FOSSBilling#1152]
fossbilling should add future domain management dns for domain templete to change side client to redirect owned domain to other hosting
![Untitled](https://user-images.githubusercontent.com/66997989/233812884-c3eb66ca-0ab9-4204-8362-1d1b262f821c.jpg)
![image (3)](https://user-images.githubusercontent.com/66997989/233812913-4e4f6574-d810-4f05-ac86-ce3cd4e988f5.png)

**Comment by Anuril** [comment]
I also don't think that this should be in fossbilling. Adding DNS Management to any platform is.. a lot of work... 

Imo either use a server control panel like hestia or in the future maybe a specific DNS hosting manager might be added as a plugin. (F.eX https://atomiadns.com/ or https://www.poweradmin.org/

**Comment by John-S4** [comment]
I will leave this open for a couple of days to see if the OP has some reason for this being in FOSSBilling that I'm missing but if not then I am going to go ahead and close the issue.

**Comment by tobsowo** [comment]
I think it will be nice to have in FOSSBiling so that not every task will need logging to the web panel Egbe it can be quickly done in the billing.

**Comment by BelleNottelling** [comment]
Yeah I'm going to be completely honest.
I can understand the appeal of this, but right now with the current number of maintainers we have, the amount of work that needs to be done, and the very significant number of [open feature requests](https://github.com/FOSSBilling/FOSSBilling/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22), I would consider this to be a very, very low priority. Assuming we even want to implement this ourselves which we likely wont.

**Comment by binsaryunus** [comment]
@John-S4  this future very helpful to management DNS from billing like whmcs have cpanel manage it plus point if fossbilling have this future like @tobsowo say this help side client quickly to set it.

**Comment by John-S4** [comment]
In my mind a much better long term option is to improve the integration with server control panels including SSO, so that the FOSSBilling would have a link to go and manage the DNS in the server control panel. 

Personally I think that there should be tight integration between billing/client-management systems, and server control panels, but there are clear lines for me about which things each one should do. 

> like whmcs have cpanel manage it

I haven't used WHMCS (or cPanel) for a long time, but that sounds like the DNS management is handled by cPanel rather than WHMCS, which would support my point?

**Comment by tobsowo** [comment]
Adding the WHMCS feature list for reference purpose
![image](https://github.com/FOSSBilling/FOSSBilling/assets/5642737/967d8ca4-bc5c-4012-b445-d570da61233c)

**Comment by jaapmarcus** [comment]
WHMCS still depends on a 3rd party software like Cpanel to run the DNS servers. 

If somebody want to create it please go ahead but for us it is currently not a priority..

**Comment by BelleNottelling** [comment]
People need to realize a couple of important things about FOSSBilling:
1. We don't have many active contributors. Generally speaking, FOSSBilling will have 1 or 2 active contributors with temporary peaks up to 3. Right now, we are at 1 (me). 
2. We aren't paid for this. I haven't tracked it, but I estimate I've put in anywhere between 6 and 8 months of full-time development towards FOSSBilling. That's roughly $49,978.5 - $66,638 USD of completely free development from me alone.
3. FOSSBilling is still considered pre-production software. There are parts of it that don't work right, system that are overly complicated or convoluted to use and maintain, and just some security features that are outright missing such as MFA support.

So implementing new features is currently a very low priority and if we are going to implement a new feature, it needs to be something that almost everyone using FOSSBilling will benefit from. Unfortunately, a handful of people finding something useful or the fact that WHMCS supports it is not enough of a reason to justify putting any priority towards something.

And that's before we even mention the fact that there's currently 90 other [open feature requests](https://github.com/FOSSBilling/FOSSBilling/issues?page=1&q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) (91 total).
