### ISSUE TITLE
[Bug] The session is cleared when the client is redirected back from the payment gateway

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#1223]
### Describe the bug

When the client is done with the payment and the payment gateway redirects them back to the website (to `/invoice/thank-you/*`), the session is destroyed.

### How to reproduce

1. Do a payment
2. Get redirected to the "thank you" page
3. See if your session is destroyed

### Expected behavior

The session should persist

### FOSSBilling version

0.4.3

**Comment by Anuril** [comment]
#1630 is probably related to this.

**Comment by BelleNottelling** [comment]
> #1630 is probably related to this.

It is not. This never effected the stripe integration & is specific to other payment gateways.
More specifically, I think this was replicated using the Mollie integration and I am unaware of it happening with other ones, but I haven't tried to replicate it.

**Comment by jaapmarcus** [comment]
Yes I had the same issue with other payment modules (Mollie)
