### ISSUE TITLE
[Bug] Embeded domain show different extension

### ISSUE THREAD

**Issue by tobsowo** [FOSSBilling/FOSSBilling#1236]
### Describe the bug

When Domain checker form is embedded on a website, it already has a set of TLD and not using the one configured.

### How to reproduce

Go to Extension > Embed and Integrate

### Expected behavior

Show same list specified in domains.

### Screenshots

![image](https://github.com/FOSSBilling/FOSSBilling/assets/5642737/0f8c0cbf-a409-47d6-882c-9209e42b0f51)
![image](https://github.com/FOSSBilling/FOSSBilling/assets/5642737/3f9edbc7-ecfd-49fa-a314-8a033c3a2325)

### FOSSBilling version

0.4.3

**Comment by samapraku** [comment]
The list of tld's are coming from the Registrar adapter.

A possible solution will be to add a configuration value to prefer configured tlds over the ones in the adapter

**Comment by tobsowo** [comment]
I just noticed that too.
