### ISSUE TITLE
[Feature Request] brainycp

### ISSUE THREAD

**Issue by onmen** [FOSSBilling/FOSSBilling#125]
I would like to see integration with a free control panel, brainycp, is this possible? I couldn't do it myself

**Comment by John-S4** [comment]
It's definitely possible. 

Right now we are focusing mostly on squashing bugs and fixing errors, and also working on a big rewrite of the codebase, but there is no reason a module for integration with BrainyCP can not be built. 

Once we have a stable release of FOSSBilling you could also try reaching out to the team behind BrainyCP to see if they would be willing to create an integration.

**Comment by John-S4** [comment]
Closing this and rolling all control panel integration requests into one larger issue #1362

**Comment by admdly** [comment]
Set as sub-issue of https://github.com/FOSSBilling/FOSSBilling/issues/1362.
