### ISSUE TITLE
[Feature Request] Send the suspension reason to the control panel

### ISSUE THREAD

**Issue by kainjinez** [FOSSBilling/FOSSBilling#1261]
### Describe the bug

I tried to suspend a hosting service and note it as "Not renewal yet". But in DirectAdmin, although it is suspended as expected, but the reason showing "Not defined".

### How to reproduce

1. FOSSBilling: Order -> Overview -> Select a hosting service.
2. Suspend.
3. Type a reason.
4. Open admin in DirectAdmin, check the suspend reason.
5. 

### Expected behavior

Showing the same reason as FOSSBilling in DirectAdmin.

### FOSSBilling version

0.4.3

### Device

Desktop

**Comment by BelleNottelling** [comment]
I've updated this to be a feature request, as right now the suspension reason is only used on the FOSSBilling end & as a email notification to the client. IE: The functionality isn't implemented, so the current behavior of DirectAdmin not being sent the reason is actually the expected behavior.

**Comment by John-S4** [comment]
Folded into #1675
