### ISSUE TITLE
EFI ( GerenciaNet ) Gateway for Fossbilling [Feature Request]

### ISSUE THREAD

**Issue by heberq1978** [FOSSBilling/FOSSBilling#1262]
Aos brasileiros, eu tenho um link do app do EFI para o BoxBilling, eu testei ele no Fossbilling e o mesmo abriu, porém está dando erro com a questão dos SDK da EFI.
Segue o link para acesso: https://github.com/gerencianet/gn-api-boxbilling
...
Version English
For Brazilians, I have a link to the EFI app for BoxBilling, I tested it on Fossbilling and it opened, but it is giving an error with the EFI SDK issue.
Here is the link to access: https://github.com/gerencianet/gn-api-boxbilling

**Comment by BelleNottelling** [comment]
Closing to make one larger issue to track the payment gateways that have been requested
