### ISSUE TITLE
[Bug] Admin page dependent upon central api

### ISSUE THREAD

**Issue by BradBot1** [FOSSBilling/FOSSBilling#1270]
### Describe the bug

Upon loading the main admin page a request is sent to the central api for alerts. If this request fails the page will simply fail to render.

This means that if the server is to ever go down or experience a large volume of requests the admin page may not be accessible.

### How to reproduce

Issue is server side, client cannot manually initiate without modifying source files.

### Expected behavior

Perhaps an error box can be rendered as is done when I don't properly set the version:
![image](https://github.com/FOSSBilling/FOSSBilling/assets/45739045/f02ba6da-8c19-4671-bab9-0a4c5f55d162)
Just a simple message such as "Failed to fetch alerts."

### Screenshots

![image](https://github.com/FOSSBilling/FOSSBilling/assets/45739045/f0225f15-f2f2-44f7-ba18-0619e29ff1c1)

### FOSSBilling version

all

### Device

Desktop

### Information

OS: Windows 11
Browser: Google Chrome 110.0.5481.178, MS Edge 110.0.1587.57

**Comment by admdly** [comment]
Thanks for raising this - I have been going through and making the HTTP client code more resilient, and it appears this was missed. I'll get this fixed and extend the timeout a little to be more forgiving in general.
