### ISSUE TITLE
[Feature Request] Add uddoktapay payment gateway on fossbilling 

### ISSUE THREAD

**Issue by Sheikhlipu123** [FOSSBilling/FOSSBilling#1284]
Add this gateway on fossbilling : https://github.com/UddoktaPay/whmcs-module https://github.com/UddoktaPay/raw-php

**Comment by evrifaessa** [comment]
Sorry. This gateway is a fairly small regional one and we likely won't work on it.

You also can write the implementation yourself. Feel free to check the existing ones and ask for help in our Discord server if you're stuck.
