### ISSUE TITLE
[Bug] Missing translations in FR language

### ISSUE THREAD

**Issue by guillaumearnx** [FOSSBilling/FOSSBilling#1325]
### Describe the bug

Some translations are missing from the french file provided in sources.

![image](https://github.com/FOSSBilling/FOSSBilling/assets/37373941/a918bdcf-a665-4077-999b-9e45724a0e79)

### How to reproduce

1. Go to 'Sign Up' page

### Expected behavior

First Name => Prénom

### FOSSBilling version

latest

### Device

Desktop

**Comment by BelleNottelling** [comment]
Sorry, but an incomplete translation isn't a bug.
They are crowdsourced and rely on people who donate their time to translate them.

The French translation is only 27% complete, and that specific string [hasn't been translated yet](https://github.com/FOSSBilling/locale/blob/main/fr_FR/LC_MESSAGES/messages.po#L3826).

If you're fluent in French and English, feel free to contribute to the translations. That's always appreciated.
You can signup and contribute here: https://translate.fossbilling.org/fossbilling
