### ISSUE TITLE
[Bug] Order/Invoice Due date

### ISSUE THREAD

**Issue by jleiss** [FOSSBilling/FOSSBilling#1333]
### Describe the bug

I feel that this field should be common between orders and invoices so if the due date is changed in one it should be changed in the other as well

### How to reproduce

go to order, select and order and change the due date and update. Go to invoices and check the associated invoice and the due date has not changed.

### Expected behavior

When due date is updated in one (order or invice, it is also updated in the other)

### FOSSBilling version

5.0

### Device

Desktop

**Comment by BelleNottelling** [comment]
Sorry, but those are two separate things.
Orders don't have due-dates, they have renewal dates.
Depending on your configuration, FOSSBilling will create an invoice a certain number of days before an order's expiration / renewal and give the client a certain amount of time for it to be paid from it's creation date. The day the invoice is created is based on when the order is set to renew, but they aren't the same and under no situation should an existing invoice be automatically updated by the system.

In fact, an invoice shouldn't ever be updated unless there is an issue with something on the invoice and if it is updated the client should be informed that it was updated and what was changed on it.
