### ISSUE TITLE
[Feature Request] Ability to sort orders/invoices by due date

### ISSUE THREAD

**Issue by jleiss** [FOSSBilling/FOSSBilling#1334]
**Is your feature request related to a problem? Please describe.**
Ability to sort orders/invoices by due date

**Describe the solution you'd like**
Ability to sort orders/invoices by due date so I can see a list of orders by priority (due date)

**Describe alternatives you've considered**

**Additional context**

**Comment by BelleNottelling** [comment]
Tables have been sortable in the admin panel for quite some time now. I believe this can be closed.
