### ISSUE TITLE
[Bug] time stamps incorrect

### ISSUE THREAD

**Issue by jleiss** [FOSSBilling/FOSSBilling#1335]
### Describe the bug

I have container set to Central US time zone, went and cleaned up some orders and invoices and when I look at recent staff activity it does not reflect the correct time.

### How to reproduce

make changes and review staff activity to validate time

### Expected behavior

log activity would match the timezone of the container.

### Screenshots

<img width="1070" alt="image" src="https://github.com/FOSSBilling/FOSSBilling/assets/2677329/9e4792f5-d58c-4b3d-9e8b-d991660be0a7">

### FOSSBilling version

5.0

### Device

Desktop

**Comment by jleiss** [comment]
container log example from docker logs container_name

<img width="1721" alt="image" src="https://github.com/FOSSBilling/FOSSBilling/assets/2677329/dba8d662-af07-4a34-a903-ae23ebddb5f7">

**Comment by BelleNottelling** [comment]
FOSSBilling version 0.5.5 now communicates with the DB server and tells it what timezone FOSSBilling is using. I'm unable to replicate this with that version. Please try updating to 0.5.5 and if you are still seeing issues, ensure you have the timezone correctly set under your `config.php` file.
Here's the list of timezones that PHP supports: https://www.php.net/manual/en/timezones.php

**Comment by BelleNottelling** [comment]
Closing as I am unable to replicate this. If you can still replicate this with FOSSBilling version 0.5.5, feel free to reopen this.
