### ISSUE TITLE
[Feature Request] Custom Status

### ISSUE THREAD

**Issue by jleiss** [FOSSBilling/FOSSBilling#1336]
**Is your feature request related to a problem? Please describe.**
Be able to create your own status's for items

**Describe the solution you'd like**
I like to be able to created my own status's for things like shipped, etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by Anuril** [comment]
To be honest, I doubt that this is going to be included anytime soon. 
I don't see Fossbilling being able to handle the legal requirements to ship items, as this requires shipping documents and such.

Adding stati also requires a way to configure how to change them in an automated fashion, given our slogan is "Free and open source hosting automation."

**Comment by jleiss** [comment]
Thanks for responding, i recently switched off of FOSS just too many things to work around, moved to word press with woo commerce.
