### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by grinia982** [FOSSBilling/FOSSBilling#1341]
### Describe the bug

On demo page after add new product and new form order show error on product:
Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/html/modules/Formbuilder/Service.php on line 243 Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/html/modules/Formbuilder/Service.php on line 244 Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/html/modules/Formbuilder/Service.php on line 244 Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/html/modules/Formbuilder/Service.php on line 244 Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/html/modules/Formbuilder/Service.php on line 243 Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/html/modules/Formbuilder/Service.php on line 244 Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/html/modules/Formbuilder/Service.php on line 244 Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/html/modules/Formbuilder/Service.php on line 244

### How to reproduce

1. Go to page https://demo.fossbilling.org/order/test-product
2. https://demo.fossbilling.org/admin/extension/settings/formbuilder?id=1

### Expected behavior

after add new product

### FOSSBilling version

0.5.0

**Comment by jaapmarcus** [comment]
Disabled Debug mode....
