### ISSUE TITLE
[Bug] Warning: Unable to fetch alerts from Central Alerts System. See error log for more information.

### ISSUE THREAD

**Issue by heberq1978** [FOSSBilling/FOSSBilling#1350]
### Describe the bug

Warning: Unable to fetch alerts from Central Alerts System. See error log for more information.

### How to reproduce

Open Admin Panel

### Expected behavior

Open Admin Panel

### FOSSBilling version

0.5.0

### Device

Desktop

### Additional context

How do I fix?

**Comment by BelleNottelling** [comment]
This just means that FOSSBilling was unable to connect to our Central Alerts API. This might mean it was temporarily down, took longer than expected to respond, or that your ISP is blocking connection to it, all of which are things that will occasionally happen and they are outside of our control.

Everything will continue to function as normal, the only difference is that if we publish an alert related to the version of FOSSBilling you are using, you may not be notified immediately from the dashboard, but as long as the connection to `https://fossbilling.org/api/central-alerts/` isn't blocked, it should self-resolve
