### ISSUE TITLE
[Feature Request] Cardinity payment gateway

### ISSUE THREAD

**Issue by John-S4** [FOSSBilling/FOSSBilling#136]
The payment gateway Cardinity maintain their own integrations with various billing software.

[https://cardinity.com/developers](https://cardinity.com/developers)

They currently have one for BoxBilling (although it hasn't been updated since 2017). It would be good if they would also/instead support FOSSBilling

**Describe the solution you'd like**
When we have a stable release, we should reach out to Cardinity and ask them to create an integration module.

**Comment by BelleNottelling** [comment]
Closing to make one larger issue to track the payment gateways that have been requested
