### ISSUE TITLE
Not Found The requested URL was not found on this server.  Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

### ISSUE THREAD

**Issue by gemsbokgroup** [FOSSBilling/FOSSBilling#1366]
After Installation, I removed installer and received the following error messages while trying to access any other page. Note, i also renamed .htaccess file to simply '.htaccess'. 

BROWSER ERROR MESSAGE: Not Found
The requested URL was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Partial error log:

2 Trying to access array offset on value of type null /home/********/public_html/********/load.php 231

PHP Warning: Trying to access array offset on value of type null in /home/********/public_html/********/load.php on line 231

2 Undefined variable $config /home/********/public_html/********/load.php 232

PHP Warning: Undefined variable $config in /home/********/public_html/********/load.php on line 232

2 Trying to access array offset on value of type null /home/********/public_html/********/load.php 232

PHP Warning: Trying to access array offset on value of type null in /home/********/public_html/********/load.php on line 232

2 Undefined variable $config /home/********/public_html/********/load.php 233

PHP Warning: Undefined variable $config in /home/********/public_html/********/load.php on line 233

2 Trying to access array offset on value of type null /home/********/public_html/********/load.php 233

PHP Warning: Trying to access array offset on value of type null in /home/********/public_html/********/load.php on line 233

2 Undefined variable $config /home/********/public_html/********/load.php 234

PHP Warning: Undefined variable $config in /home/********/public_html/********/load.php on line 234

2 Trying to access array offset on value of type null /home/********/public_html/********/load.php 234

PHP Warning: Trying to access array offset on value of type null in /home/********/public_html/********/load.php on line 234

2 Undefined variable $config /home/********/public_html/********/load.php 235

PHP Warning: Undefined variable $config in /home/********/public_html/********/load.php on line 235

2 Trying to access array offset on value of type null /home/********/public_html/********/load.php 235

PHP Warning: Trying to access array offset on value of type null in /home/********/public_html/********/load.php on line 235

8192 str_starts_with(): Passing null to parameter #1 ($haystack) of type string is deprecated /home/********/public_html/********/load.php 235

PHP Deprecated: str_starts_with(): Passing null to parameter #1 ($haystack) of type string is deprecated in /home/********/public_html/********/load.php on line 235

2 Undefined variable $config /home/********/public_html/********/load.php 236

PHP Warning: Undefined variable $config in /home/********/public_html/********/load.php on line 236

2 Trying to access array offset on value of type null /home/********/public_html/********/load.php 236

PHP Warning: Trying to access array offset on value of type null in /home/********/public_html/********/load.php on line 236

2 Undefined variable $config /home/********/public_html/********/load.php 237

PHP Warning: Undefined variable $config in /home/********/public_html/********/load.php on line 237

2 Trying to access array offset on value of type null /home/********/public_html/********/load.php 237

PHP Warning: Trying to access array offset on value of type null in /home/********/public_html/********/load.php on line 237

2 file_put_contents(/cache/classMap.php): Failed to open stream: No such file or directory /home/********/public_html/********

ANY HELP?

**Comment by BelleNottelling** [comment]
Reporter stated they resolved the issue via a DM on Discord
