### ISSUE TITLE
The data-toggle="collapse" data-target=".nav-collapse" ( Bootstrap v3.4.1) used in Huraga theme for dropping menu when you toggle user profile is not collapsing on mobile view [Bug]

### ISSUE THREAD

**Issue by DigitalVocano** [FOSSBilling/FOSSBilling#1370]
### Describe the bug

visit https://demo.fossbilling.org/
On desktop shrink your browser to force mobile view
Or try accessing using mobile device
The menu is supposed to drop down under user profile
When you toggle the user profile, there i
<img width="351" alt="Capture" src="https://github.com/FOSSBilling/FOSSBilling/assets/123166151/b9f49f6f-64a5-4d4f-bb23-61dc68062d41">
s a slight movement but the menu is not collapsing

### How to reproduce

visit https://demo.fossbilling.org/
On desktop shrink your browser to force mobile view
Or try accessing using mobile device
The menu is supposed to drop down under user profile
When you toggle the user profile, there i
<img width="351" alt="Capture" src="https://github.com/FOSSBilling/FOSSBilling/assets/123166151/b9f49f6f-64a5-4d4f-bb23-61dc68062d41">
s a slight movement but the menu is not collapsing

### Expected behavior

When you press the user profile ,the menu
<img width="367" alt="Capture" src="https://github.com/FOSSBilling/FOSSBilling/assets/123166151/b86f98f1-b376-40d0-a00f-d20e5585ec8f">
 must drop down on mobile view

### FOSSBilling version

latest release

### Device

Smartphone

### Information

<img width="367" alt="Capture" src="https://github.com/FOSSBilling/FOSSBilling/assets/123166151/4e73add8-36bf-4239-abd9-f35006b17902">

**Comment by jaapmarcus** [comment]
Huraga theme is over 10 years old. And quite buggy on mobile. So a known issue.

**Comment by DigitalVocano** [comment]
noted

**Comment by BelleNottelling** [comment]
I'll fix this while migrating the client area to BS v5
