### ISSUE TITLE
Cart refreshed for guests users when logged in or sign up

### ISSUE THREAD

**Issue by tobsowo** [FOSSBilling/FOSSBilling#1395]
### Describe the bug

The cart refreshes to zero when a guest signed up or login.

### How to reproduce

Logout and try adding products to cart
Then login or sign up

### Expected behavior

Continue to payment

### FOSSBilling version

0.5.3

**Comment by BelleNottelling** [comment]
This will remain an issue until we rewrite the cart (#556).
It uses session IDs which are regenerated when logging as a security measure, meaning we won't be changing that behavior
