### ISSUE TITLE
[Feature Request] Support for CyberPanel

### ISSUE THREAD

**Issue by tobsowo** [FOSSBilling/FOSSBilling#141]
**Describe the solution you'd like**
Support for open source hosting panel - CyberPanel.
It is actively developed and been used by many.
https://github.com/usmannasir/cyberpanel/

**Comment by John-S4** [comment]
Closing this and rolling all control panel integration requests into one larger issue #1362

**Comment by admdly** [comment]
Set as sub-issue of https://github.com/FOSSBilling/FOSSBilling/issues/1362.
