### ISSUE TITLE
[Feature Request] Orders sortable by client name

### ISSUE THREAD

**Issue by mwlandolsi** [FOSSBilling/FOSSBilling#1411]
**Is your feature request related to a problem? Please describe.**
Could not list orders or invoices  by customer name

**Describe the solution you'd like**
add filter by customer name to listings of invoices or orders 
add possibility click over list tile to sort listed invoices and orders

**Comment by tobsowo** [comment]
I believe is fixed and should come with the next release.

**Comment by John-S4** [comment]
Yes, a PR has been merged, and there will be much better ability to sort by columns including name in the next release. 

@mwlandolsi Please, in the future, can you give Issues a clear descriptive title, instead of just [Feature Request], it makes it much easier to look through them quickly.
