### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by firedwir** [FOSSBilling/FOSSBilling#1427]
### Describe the bug

No admin area in download

### How to reproduce

Download

### Expected behavior

Go to login

### FOSSBilling version

Releases (v0.5.4)

### Module version

admin area

**Comment by BelleNottelling** [comment]
Not a bug, you have your web-server miss-configured for FOSSBilling.
See: https://fossbilling.org/docs/troubleshooting#http-error-404 and https://fossbilling.org/docs/getting-started
