### ISSUE TITLE
[Bug] Unable to Create Announcement 

### ISSUE THREAD

**Issue by DigitalVocano** [FOSSBilling/FOSSBilling#1438]
### Describe the bug

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'description' in 'field list' (9999)

### How to reproduce

Go to Announcements
Select create New
Fill in the fields
Select Create

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'description' in 'field list' (9999)

### Expected behavior

Go to Announcements
Select create New
Fill in the fields
Select Create

Announcements Successfully created

### Screenshots

<img width="273" alt="Capture" src="https://github.com/FOSSBilling/FOSSBilling/assets/123166151/46fb095c-2b42-4d96-9d73-e1364e1d0e17">

### FOSSBilling version

FOSSBilling 0.5.4

### Device

Desktop

### Additional context

The Notifications are not visible in the dark theme mode.
Text and Background color have the same color (White)
<img width="261" alt="Capture" src="https://github.com/FOSSBilling/FOSSBilling/assets/123166151/d827c7c2-8cc1-47a2-86b4-3d1be4dae2bf">

**Comment by BelleNottelling** [comment]
I can't reproduce this. Have you made any modifications to FOSSBilling?
![Animation](https://github.com/FOSSBilling/FOSSBilling/assets/17304943/0cfec78b-a5c0-494c-a039-ac6e61bac29b)

Additionally, can you do a sanity check and verify that your `post` table actually has the `description` column?

**Comment by BelleNottelling** [comment]
Hello, @DigitalVocano 
Are you able to replicate this on FOSSBilling version 0.5.5?

**Comment by BelleNottelling** [comment]
Closing due to the lack of response & the fact that we are unable to replicate it
