### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by mxroute** [FOSSBilling/FOSSBilling#1446]
### Describe the bug

I attempted to update to the latest version and the result was this:

Typed property Box\Mod\System\Controller\Admin::$di must not be accessed before initialization

Then when reloading the page, it would always return this:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fingerprint' in 'field list'

### How to reproduce

Click update

### Expected behavior

Something else I'm sure :)

### FOSSBilling version

Presently unclear, I wish I had taken note of what version it was prior to clicking update.

**Comment by BelleNottelling** [comment]
Hi, @mxroute 

Navigate to yourdomain.com/run-patcher.
This will perform the backup patching method which will bring the Database up-to-date with the current patches.

If you have any issues, I'd suggest joining our discord and I'll ensure you get the help you need with that.
https://fossbilling.org/discord

**Comment by mxroute** [comment]
Flawless approach, thank you!

**Comment by BelleNottelling** [comment]
> Flawless approach, thank you!

Glad that resolved it!
I know you were mostly directly working with Adam when he had more availability. If needed, I'd be happy to lend a helping hand in his place.

Take care!
