### ISSUE TITLE
[Feature Request] Update bootstrap to the latest version.

### ISSUE THREAD

**Issue by ichilver** [FOSSBilling/FOSSBilling#1455]
It would be good if FOSSBilling themes supported the latest version of Bootstrap and Fontawesome.

I tried to create a custom theme using BootStrap 5 only to discover there are modules, etc, outside of the theme that contain HTML using Bootstrap 3 CSS.  It got very messy.

So a future feature request is to support the newer (latest) version of bootstrap.

**Comment by BelleNottelling** [comment]
FYI: you can override these template files in your theme by simply just having a file with a matching name. That's actually the intention for most themes (assuming they don't use exactly the same dependencies & libraries)

Updating the BS version is ultimately one of the pre-requisites to us building and shipping a new client area theme, though. So I'll take a look at this at some point.

**Comment by hambolu** [comment]
you can create your own custom themes from huraga and modify it to what ever you want well that what I did

**Comment by jaapmarcus** [comment]
> you can create your own custom themes from huraga and modify it to what ever you want well that what I did

Yes we know that how ever it doesn't mean we need to update the default theme...
