### ISSUE TITLE
[Bug] count(): Argument #1 ($value) must be of type Countable|array, bool given

### ISSUE THREAD

**Issue by andpavlenko** [FOSSBilling/FOSSBilling#148]
I'm have encountered errors on many pages, that prevent page loading.
Error log: `count(): Argument #1 ($value) must be of type Countable|array, bool given`

I'm fix simple [typo](https://github.com/FOSSBilling/FOSSBilling/blob/66de9c3d4ee00eecfcf92cbb276b083d8ab88c97/src/bb-modules/System/Service.php#L935) in my commit #[6480da2](https://github.com/FOSSBilling/FOSSBilling/pull/113/commits/6480da20c283ea70ee89a5b668f768eb554d2c47).

**Comment by BelleNottelling** [comment]
Resolved as of PR #367
