### ISSUE TITLE
An error has occurred - update error from version 0.3.0 to version 0.5.5

### ISSUE THREAD

**Issue by dspasov** [FOSSBilling/FOSSBilling#1480]
### Describe the bug

Hello,

After I updated the FOSSBilling from version 0.3.0 to version 0.5.5 I received the following error messages:

"An error has occurred.

Error Code: #0

Component: Generic

You've received a generic error message: FOSSBilling\Session::__construct(): Argument #3 ($cookieLifespan) must be of type int, string given, called in /home/raxwebsites/my.raxwebsites.com/di.php on line 242"

"An error has occurred.

Error Code: #0

Component: Generic

FOSSBilling\Session::__construct(): Argument #3 ($cookieLifespan) must be of type int, string given, called in /home/raxwebsites/my.raxwebsites.com/di.php on line 242"

### How to reproduce

I try to change the PHP Version to 8.2 but I get the same error messages.

### Expected behavior

Please help me to fix this error.

### Screenshots

![error](https://github.com/FOSSBilling/FOSSBilling/assets/5227311/83c4d9d2-5361-494f-bce9-2b840e428620)

### FOSSBilling version

FOSSBilling 0.3.0

### Device

Desktop

**Comment by BelleNottelling** [comment]
Hello,
You will need to edit your `config.php`and replace `'cookie_lifespan' => "7200",` with `'cookie_lifespan' => 7200,`.
After that, the final step will be to navigate to `yourdomain.com/run-patcher` which will bring your database up-to-date as FOSSBilling isn't capable of automatically doing so when going from pre-0.5.X versions to 0.5.X.

**Comment by dspasov** [comment]
Dear BelleNottelling,

Thank you again for your help. Now I am not able to log in my.mydomain.com/admin  after this update/changes - here is the error message that I get

System message:
"n_array(): Argument #2 ($haystack) must be of type array, null given (9998)" 

php_error.log:

"[30-Jul-2023 10:54:25 UTC] 2 Undefined array key "i18n" /home/raxwebsites/my.raxwebsites.com/modules/System/Api/Guest.php 175
[30-Jul-2023 10:54:25 UTC] 2 Trying to access array offset on value of type null /home/raxwebsites/my.raxwebsites.com/modules/System/Api/Guest.php 175
[30-Jul-2023 10:54:27 UTC] Unable to find template "mod_page_favicon.ico" (looked into: /home/raxwebsites/my.raxwebsites.com/themes/huraga/html, /home/raxwebsites/my.raxwebsites.com/modules/Page/html_client).
[30-Jul-2023 10:54:27 UTC] Page /favicon.ico not found
[30-Jul-2023 10:55:08 UTC] Unable to find template "mod_page_favicon.ico" (looked into: /home/raxwebsites/my.raxwebsites.com/themes/huraga/html, /home/raxwebsites/my.raxwebsites.com/modules/Page/html_client).
[30-Jul-2023 10:55:08 UTC] Page /favicon.ico not found
[30-Jul-2023 10:55:09 UTC] 2 Undefined array key "rate_limit_whitelist" /home/raxwebsites/my.raxwebsites.com/modules/Api/Controller/Client.php 95
[30-Jul-2023 10:55:09 UTC] in_array(): Argument #2 ($haystack) must be of type array, null given
[30-Jul-2023 10:57:11 UTC] 2 Undefined array key "rate_limit_whitelist" /home/raxwebsites/my.raxwebsites.com/modules/Api/Controller/Client.php 95
[30-Jul-2023 10:57:11 UTC] in_array(): Argument #2 ($haystack) must be of type array, null given
"
I will expect your reply. Thank you again for your cooperation.

Best Regards,
Dimitar S.
Senior Specialist "Technical Support" Department

**Comment by BelleNottelling** [comment]
It sounds like the config file didn't get migrated. Did you do the `/run-patcher` step already? 
If you did and it didn't migrate the config file, you'll need to do it manually.

I would make a backup of the existing configuration file and then re-create it using the example config file:
https://github.com/FOSSBilling/FOSSBilling/blob/main/src/config-sample.php

The important details to copy over from the existing config file are the following parameters: `salt`, `url`, `path_data`, `path_logs`, all under `db` and all under `twig`.

**Comment by dspasov** [comment]
Hi,

When I try to run foss-update.php I get this "Update completed. You are using FOSSBilling 0.3.0"

run-patcher does not work. I make a new config.php with your parameters but now I get new error messages 

"You've received a generic error message: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fingerprint' in 'field list'"

I will expect your reply. Thank you again for your cooperation.

Best Regards,
Dimitar S.

**Comment by BelleNottelling** [comment]
> When I try to run foss-update.php I get this "Update completed. You are using FOSSBilling 0.3.0"

The `foss-update.php` script has been replaced with a different method in the project and no longer exists. The version you ran is an old copy and it'll do nothing to help the situation. 

> run-patcher does not work

Please clarify what happens & how you've attempted to access it.

**Comment by dspasov** [comment]
Hi,

When I run "run-patcher" I get this message: "An error occurred while attempting to apply patches:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''id', 'param', 'value', 'public', 'category', 'hash', 'created_at', 'updated_at'' at line 1"

**Comment by dspasov** [comment]
Hi,

I try to upgrade manually from version  0.3.0 to 0.4.0 - uploading and replacing the files with the 0.4.0 version and I run foss-update.php "Update completed. You are using FOSSBilling 0.4.0". The client area is working but the access to administration does not work correctly - mydomain.com/my/admin/staff/login

"ERROR - Unknown "encore_entry_link_tags" function."

Please help me to fix this error. I am lost now. If I can't solve this problem I will have to install fresh/new FOSSBilling [0.5.5] and move my clients and products manually and settings.

Looking to your reply. Thank you again. 

Best Regards,
Dimitar S.

**Comment by BelleNottelling** [comment]
> The client area is working but the access to administration does not work correctly - mydomain.com/my/admin/staff/login

Due to clunky routing (that we inherited from BoxBilling code), FOSSBilling does not support installations on sub-folders. We intend to re-do how the routing behaves and re-add support for installing it to a sub-folder before FOSSBilling hit production ready (version 1.0.0), however there is no ETA on this & it won't work correctly until then.

> When I run "run-patcher" I get this message: "An error occurred while attempting to apply patches:
> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''id', 'param', 'value', 'public', 'category', 'hash', 'created_at', 'updated_at'' at line 1"

I suspect I know what the problem is and how to fix it. Would it be possible to get you to join our [discord](https://fossbilling.org/discord) so we can more easily communicate and troubleshoot a fix for your installation?
