### ISSUE TITLE
[Bug] Order Suspension Reason is Blank

### ISSUE THREAD

**Issue by TheCuteFoxxy** [FOSSBilling/FOSSBilling#1502]
### Describe the bug

The reason provided in the suspension log for order history is blank, both automated and user provided.

### How to reproduce

1. Create a new order and set it to automatically expire
2. Let the order expire automatically or manually suspend it
4. Go to the order history
5. Observe the suspension log line item
6. The suspension reason is blank

### Expected behavior

The log should explain the order expired or the reason provided by the user.

### Screenshots

Red is automated suspension, blue is manual suspension.
![Screenshot of Logs](https://cdn.thecutefoxxy.com/KEMZYG.png)

### FOSSBilling version

0.5.3

### Device

Desktop

### Information

- Asus Desktop
- Windows 11 x64
- Firefox 115.0.3 (64-bit)

**Comment by Anuril** [comment]
I'm trying to replicate this issue, and from what I can see with 0.5.5, this issue doesn't exist.
![grafik](https://github.com/FOSSBilling/FOSSBilling/assets/1939311/761831e8-3909-4813-a2ce-c8d385bc36fc)

Can you try to upgrade and see if it still persists? 

Also: Did you configure the field "Auto Suspend Reason" in the Settings?

![grafik](https://github.com/FOSSBilling/FOSSBilling/assets/1939311/bca1d71e-6b06-4b7e-8bd5-26090f3aefaf)

I'll have an order expire in 20 minutes, I can then tell you if i could replicate the automated part.

**Comment by Anuril** [comment]
I'm sorry, I cant' replicate your issue. My system automatically suspended the order  (red) as well as manually (green) - both times it used the comment.

![grafik](https://github.com/FOSSBilling/FOSSBilling/assets/1939311/4252f9c2-7e06-4416-9c7b-533d6c008930)

Please update to FOSSBilling Version 0.5.5 and verify your settings. If the issue persists, feel free to reach out again.

**Comment by TheCuteFoxxy** [comment]
I'll update to 0.5.5 and see if the issue persists.

**Comment by TheCuteFoxxy** [comment]
Not sure what exactly was causing it, but its working now after re-installing 0.5.3 (can't upgrade to 0.5.5 due to issues when installing)
