### ISSUE TITLE
[Feature Request] fastpanel panel

### ISSUE THREAD

**Issue by twixi** [FOSSBilling/FOSSBilling#1513]
ADD support https://fastpanel.direct/

**Comment by jaapmarcus** [comment]
See https://github.com/FOSSBilling/FOSSBilling/issues/1362

**Comment by admdly** [comment]
> will this thing be worked on @admdly 

It's unlikely this will be handled by us based on past comments and developer availability. Hopefully it is something that can be provided as an extension by the community.

**Comment by tobsowo** [comment]
@admdly they now support API access.
https://kb.fastpanel.direct/api/
