### ISSUE TITLE
[Bug] No verification link sent in welcome email

### ISSUE THREAD

**Issue by coldwhiz** [FOSSBilling/FOSSBilling#1525]
### Describe the bug

I was testing your client portal and found the welcome email did not send the verification email.

When I clicked the "Resend verification link", it opened a new page and threw json code,
`{"result":null,"error":null}`

### How to reproduce

Register for new account

### Expected behavior

Welcome email with activation link. And "Resend verification link" to redirect instead of throwing JSON.

### FOSSBilling version

0.5.5

### Device

Desktop

**Comment by BelleNottelling** [comment]
> When I clicked the "Resend verification link", it opened a new page and threw json code,

What browser are you using and what version?
