### ISSUE TITLE
[Bug] **Call to undefined function imagecreatefrompng()**

### ISSUE THREAD

**Issue by fabpot-del** [FOSSBilling/FOSSBilling#153]
**Describe the bug**
When trying to download the order invoice in PDF from this error "imagecreatefrompng ()"

**To Reproduce**
1. Go to 'admin page'
2. Click on 'invoices'
3. Scroll down to 'overview'
4. Click on 'BOX0001'
5. Click on 'PDF'
6. See error

**Screenshots**
![Screenshot 2022-06-26 at 09-17-10 An error ocurred](https://user-images.githubusercontent.com/93833001/175803763-fbaa85a6-48d4-4449-a452-284a20a6a8c6.png)

**Comment by jaapmarcus** [comment]
You are missing GD libary make sure it is installed in php

**Comment by fabpot-del** [comment]
Now he gives me this error "imagecreate(): Argument #1 ($width) must be greater than 0"

**Comment by jaapmarcus** [comment]
Check php error log and provide with more info...

**Comment by fabpot-del** [comment]
Then the installation said that I had all the plugins enabled but they weren't so I reinstalled and enabled the plugins but it gives me the same error so I went to the error.log and found this "[Sun Jun 26 09:41:10.385539 2022] [php:notice] [pid 21284:tid 1756] [client 127.0.0.1:53305] PHP Deprecated:  PDOStatement::fetchAll(): Passing null to parameter #1 ($mode) of type int is deprecated in C:\\xampp\\htdocs\\rb.php on line 822, referer: http://localhost/install/install.php"

**Comment by evrifaessa** [comment]
Seems like you're using XAMPP.

You need to enable the GD extension. You can follow this guide: https://codeanddeploy.com/blog/php/how-to-install-php-gd-extension-on-windows-wamp-and-xampp-server

**Comment by fabpot-del** [comment]
I I already have the GD extension enabled

**Comment by evrifaessa** [comment]
Maybe you forgot to restart the server?

**Comment by fabpot-del** [comment]
I have already restarted the server several times

**Comment by jaapmarcus** [comment]
https://github.com/FOSSBilling/FOSSBilling/blob/e4074827ccaf658d314f43e4223035cc3df68f68/src/rb.php#L822

Is the line in question that causes the issue. 

Assuming your are running 8.1?

**Comment by fabpot-del** [comment]
Yes, i am in PHP 8.1

**Comment by BelleNottelling** [comment]
Please try PHP 8

**Comment by fabpot-del** [comment]
From the same error if you have it on your pc you pass me your php.ini so we can check if it is a problem of enabling the extension?

**Comment by jaapmarcus** [comment]
Can confirm the last issue

**Comment by BelleNottelling** [comment]
Tested after PR #340 was merged and the PDF generates without an error on PHP 8.1 now.
Closing, feel free to re-open if you are still experiencing the same issue
