### ISSUE TITLE
[Bug] Unable to create product

### ISSUE THREAD

**Issue by jaapmarcus** [FOSSBilling/FOSSBilling#158]
**Describe the bug**

Create a new product an popup appears with "Product ID not passed" 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/9754650/175965633-4fbc70a4-6c9d-4ee2-ba23-33cafd65b383.png)**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Multiple users reported this error

**Comment by John-S4** [comment]
Fixed by #178
