### ISSUE TITLE
[Bug] File not found for /admin or /signup

### ISSUE THREAD

**Issue by McSwizzlestix** [FOSSBilling/FOSSBilling#1619]
### Describe the bug

After new install File not found for admin area or registrations.

### How to reproduce

1. Install using Steps at https://fossbilling.org/docs/getting-started/shared
2. Browse click Admin area after install or browse to admin URL

### Expected behavior

Admin or Registration area loads

### FOSSBilling version

v0.5.5

### Device

Desktop

### Information

Windows 10 Desktop
Chrome Browser latest version

### Additional context

.htacces file has already been renamed. mod_rewrite is enabled.
All troubleshooting from Foss documentation has been followed

**Comment by BelleNottelling** [comment]
> .htacces file has already been renamed

Renamed? You shouldn't have to rename it. It comes with the correct name

>  All troubleshooting from Foss documentation has been followed

What kind of server do you have?

**Comment by McSwizzlestix** [comment]
you're correct it was already renamed upon unpacking.

Server Info:
  Server Version: Apache/2.4.57 (cPanel) OpenSSL/1.1.1k mod_bwlimited/1.4 mod_fcgid/2.3.9 mod_cpanel/1.4 
  Phusion_Passenger/6.0.18
  Server MPM: event
  Virtualization: kvm
  Operating System: CloudLinux 8.8 (Anatoly Filipchenko)
  Kernel: Linux 4.18.0-477.21.1.lve.1.el8.x86_64
  Architecture: x86-64

**Comment by BelleNottelling** [comment]
Okay, and what are the contents of your `.htaccess` file?

**Comment by BelleNottelling** [comment]
Hi, @McSwizzlestix can you please share the of your `.htaccess` file?
Thank you.

**Comment by BelleNottelling** [comment]
Closing due to the lack of response.
The issue you are having is almost without a doubt an issue with your server's configuration.

If you'd like help, our Discord or forums are a great option, but we can also continue troubleshooting here if you'd like.
Otherwise, this is staying closed
