### ISSUE TITLE
[Feature Request] Namecheap EPP code

### ISSUE THREAD

**Issue by insxa** [FOSSBilling/FOSSBilling#1651]
If you can implement namecheap EPP code

**Comment by Anuril** [comment]
According to their suppirt, that is not possible, see the comments here: https://www.namecheap.com/support/api/methods/domains/set-registrar-lock/
Closing this issue

**Comment by jaapmarcus** [comment]
To be more clear:

> Unfortunately, the option for getting the EPP code is not available for API. In order to receive the EPP/Auth code to your Registrant email address, you need to log into your Namecheap account, go to Domain List and click Manage next to the domain you want to transfer out. Go to Sharing & Transfer tab and click on the Auth Code button in the Transfer Out section.

>You can also find the detailed instructions with the screenshots in [this article](https://disq.us/url?url=https%3A%2F%2Fwww.namecheap.com%2Fsupport%2Fknowledgebase%2Farticle.aspx%2F258%2F84%2Fwhat-should-i-do-to-transfer-a-domain-from-namecheap%3ANwtzC7vQSiPSuO_gXF5kvzseUB0&cuid=508003).

> If you have any questions, feel free to contact our Support Team via [Live Chat](https://disq.us/url?url=https%3A%2F%2Fwww.namecheap.com%2Fsupport%2Flive-chat%2Fgeneral%3Al2Q1OLq3HUWmIeImaj6ztqUopUU&cuid=508003) or by [submitting a Support Ticket](https://disq.us/url?url=https%3A%2F%2Fsupport.namecheap.com%2Findex.php%3F%2FTickets%2FSubmit%3AOHm80ILOYCOYuB7etKweGFG3Ync&cuid=508003).

>Kind regards,
>Namecheap Team
