### ISSUE TITLE
New installer

### ISSUE THREAD

**Issue by John-S4** [FOSSBilling/FOSSBilling#1683]
The current installer works fine but is a bit clunky, unclear, and outdated in some ways. 

A replacement with improved UX and not reliant on jQuery (#907) should be implemented.

**Comment by Ron-Zarbyte** [comment]
I started looking at an overhaul to the installer after #1583 out of my own interest, so this is convenient timing. I will go ahead and continue working on it and post updates here.

**Comment by John-S4** [comment]
> I see it got bumped a bit further down the roadmap, but I think a better installer would be great for v1.0.0.

I kicked it down the roadmap a little bit simply because it would be good to get a stable 1.0 out as soon as possible rather than in the unforeseeable future and the current installer is fit for purpose while there are a lot of other things that really aren't and therefore take priority. 

Having said that, of course if there is a new shiny better option on the table for 1.0 or before then that is even better. :)

**Comment by John-S4** [comment]
Will be closed by #1698
