### ISSUE TITLE
[Feature Request] - Company name in client search bars

### ISSUE THREAD

**Issue by gilesytheking** [FOSSBilling/FOSSBilling#1686]
Would it be possible to make the Client Company Name searchable in the Client search when creating new orders, tickets etc.

Sometimes its easier to remember the company name, rather then the name of the person on the account. I also have some clients that have multiple accounts with the same client name but different companies. In this instance I have to remember the client ID for the specific company account.

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/0d1565a7-9d28-4d1c-94ae-2780b9975693)

**Comment by John-S4** [comment]
This is a really good point, and yes the search should be updated to look for company name as well as client name.

**Comment by John-S4** [comment]
> This is a really good point, and yes the search should be updated to look for company name as well as client name. It's a small thing but a big usability improvement.

**Comment by BelleNottelling** [comment]
Maybe name, company, or email should all be searchable?

Also it might be nice if it fetched the list of clients before you actually type anything if you wanted to just scroll for the client.
You can do that now by typing something and then deleting, but it'd be nicer if it just did it from the start.
We would need to implement that properly though so it's not going to try and fetch a list of thousands of clients, but it could be a nice QoL improvement

**Comment by jaapmarcus** [comment]
Email, company, name and id off course should be more then enough.
