### ISSUE TITLE
Make PDF Invoices translateable

### ISSUE THREAD

**Issue by John-S4** [FOSSBilling/FOSSBilling#1699]
Currently PDF invoices are not translatable which is an issue both for users and also for legality reasons when a company is obliged to provide an invoice in the national lanaguage.

**Comment by evilmc** [comment]
I hope this will be soon possible to change English strings! Thanks!

**Comment by xeruf** [comment]
This is a blocker for us using FOSSBilling, can we speed up development with a bounty here? :)
