### ISSUE TITLE
[Bug] Events/hooks don't work until you run cron jobs for the first time

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#170]
**Describe the bug**
see title

**To Reproduce**
1. Perform a fresh install
2. Don't set up the crontab
3. Try any functionality that requires hooks, you could set up CAPTCHAs and see that they won't work because they depend on the pre-signup event

**Expected behavior**
Events should work without needing to run the cron jobs

**Additional information**
Originally https://github.com/boxbilling/boxbilling/issues/624.

**Comment by BelleNottelling** [comment]
Linked PR will run cron the first time an admin logs in & any time it's gone past 15min since last execution. Should resolve this

**Comment by John-S4** [comment]
Closing - Resolved by #397
