### ISSUE TITLE
[Feature Request] customer panel UI

### ISSUE THREAD

**Issue by BursaYazilimCom** [FOSSBilling/FOSSBilling#1705]
Will there be a design change for the customer panel?

**Comment by BelleNottelling** [comment]
Yes.
See https://github.com/FOSSBilling/FOSSBilling/pull/1612, https://github.com/FOSSBilling/FOSSBilling/pull/1602, https://github.com/FOSSBilling/FOSSBilling/issues/1455, and the [WIP changelog for the next major release](https://fossbilling.org/docs/changelog#060-wip).
![Client-Area](https://github.com/FOSSBilling/FOSSBilling/assets/17304943/4c9779fe-943e-499d-902c-b8306248a5eb)
