### ISSUE TITLE
[Bug] problem with cron.php send this error to my email

### ISSUE THREAD

**Issue by cahb52** [FOSSBilling/FOSSBilling#1710]
### Describe the bug

i have this issue with php 8.2
can you help me?
thanks
<br />
<b>Warning</b>:  Undefined array key "SCRIPT_NAME" in <b>public_html/foss/load.php</b> on line <b>34</b><br />
<br />
<b>Deprecated</b>:  dirname(): Passing null to parameter #1 ($path) of type string is deprecated in <b>/home/quetzalg/public_html/foss/load.php</b> on line <b>34</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /public_html/foss/load.php:34) in <b>public_html/foss/load.php</b> on line <b>39</b><br />
<br />
<b>Warning</b>:  require(public_html/foss/config.php): Failed to open stream: No such file or directory in <b>public_html/foss/load.php</b> on line <b>225</b><br />

### How to reproduce

php ea-php82  8.2

### Expected behavior

do you have any fix to this issue?

### FOSSBilling version

0.5.6

**Comment by BelleNottelling** [comment]
Have you even completed the installation yet?

> Warning: Cannot modify header information - headers already sent by (output started at /public_html/foss/load.php:34) in public_html/foss/load.php on line 39

This line shouldn't be reached unless the installer is still on the disk and there isn't a config file yet, which suggests you've setup cron and nothing else in the FOSSBilling instance.

If that is the case, then all except for the very first item are to be expected as cron will not function if you haven't installed FOSSBilling yet

**Comment by cahb52** [comment]
Have you even completed the installation yet?
Yes, is completed, the error is only with php 8 or above

**Comment by BelleNottelling** [comment]
FOSSBilling doesn't support anything less than PHP 8.
Actually, if you try to use less than PHP 8 execution will be prevented entirely, so that's not fixing the error. It's just preventing it from reaching the code that displays the error.

Looking at your error messages, I can see two issues:
1. You appear to be trying to run FOSSBilling under a sub-folder which is currently non-functional (`public_html/foss/`)
2. If the file under `public_html/foss/config.php` does exist, PHP is unable to see / access it under the CLI which is most likely a permission issue. I'd start by looking at [the troubleshooting docs](https://fossbilling.org/docs/troubleshooting#permission-issues)

**Comment by cahb52** [comment]
You appear to be trying to run FOSSBilling under a sub-folder which is currently non-functional (public_html/foss/)
it was a mistake because i installed a copy in another folder for test purpuses, but i got the same error.
the root directory es public_html and in this folder config.php exist

i think the error is because the function on line 34 is deprecated
<b>Deprecated</b>:  dirname(): Passing null to parameter #1 ($path) of type string is deprecated in <b>/public_html/load.php</b> on line <b>34</b><br />

**Comment by BelleNottelling** [comment]
> it was a mistake because i installed a copy in another folder for test purpuses, but i got the same error.
> the root directory es public_html and in this folder config.php exist

All of the errors indicate that the cron job is the install you put under `public_html/foss/`. If that's the case and the config file is in the parent directory, that's going to cause the error you are seeing. 

> i think the error is because the function on line 34 is deprecated
Deprecated: dirname(): Passing null to parameter #1 ($path) of type string is deprecated in /public_html/load.php on line 34

It isn't. You can validate this for yourself by editing `load.php` and replacing
```PHP
function checkConfig()
{
    $filesystem = new Filesystem();

    $base_url = 'http' . ((isset($_SERVER['HTTPS']) && ($_SERVER['HTTPS'] === 'on' || $_SERVER['HTTPS'] == 1)) || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') ? 's' : '') . '://' . ($_SERVER['HTTP_HOST'] ?? '');
    $base_url .= rtrim(dirname($_SERVER['SCRIPT_NAME']), '/');

    // Check if configuration is available, and redirect to installer if not.
    if (!$filesystem->exists(PATH_CONFIG)) {
        if ($filesystem->exists('install/index.php')) {
            header('Location: ' . $base_url . '/install/index.php', true, 307);
        } else {
            throw new Exception('The FOSSBilling configuration file is empty or invalid.', 3);
        }
    }
}
```
with
```PHP
function checkConfig()
{
}
```

**Comment by BelleNottelling** [comment]
As far as I can tell, this error was a result of user-error & there's nothing for us to complete.
Closing due to that & since there's been no reply for some time
