### ISSUE TITLE
[Feature Request] Directadmin Servers on non-standard port

### ISSUE THREAD

**Issue by ilevennet** [FOSSBilling/FOSSBilling#1717]
**Is your feature request related to a problem? Please describe.**
I can't connect to Directadmin installation because I use DA on non standard port 8443 instead 2222

**Describe the solution you'd like**
Add a new text input for port to connect

**Comment by jaapmarcus** [comment]
Save server and edit it you are able to edit / change the connection port 

How ever this needs to be able to change on "Add server"

**Comment by jaapmarcus** [comment]
See PR
