### ISSUE TITLE
[Feature Request] - Run Cron from an external source

### ISSUE THREAD

**Issue by gilesytheking** [FOSSBilling/FOSSBilling#1720]
Hoping someone can help. Due to limitations of my current hosting environment, I'm unable to run CRON at 5 min intervals. The Cron job does work, but at a higher interval, meaning there is a bigger delay in running Scheduled tasks, which is not ideal.

There are a number of 3rd party services available, (I currently use cron-jobs.org, which is FREE and works for other sites I host) that will allow me to run CRON Job at 5min intervals. However the cron.php file for FOSS billing is not publicly available and cannot be triggered externally via HTTP.

Would anyone have any advice on how to trigger the FOSSbilling cron using the above external service?

TIA.

**Comment by Anuril** [comment]
We do not recommend this, but you could modify the .htaccess file to allow general access to cron by changing this line https://github.com/FOSSBilling/FOSSBilling/blob/63a71305ec5bf6621738a9cd75f2e519c6eb0098/src/.htaccess#L23C36-L23C36 

```     RewriteCond %{REQUEST_URI} ^/(index\.php|ipn\.php|install/index\.php|install/install\.php|cron.php) [NC] ```

Or you could add 

```
<Files "cron.php">
    Order Deny,Allow
    Deny from all
    Allow from xxx.xxx.xxx.xxx  # replace with the desired IP address
</Files>
```
directly after #BEGIN FOSSBilling.

You need to test if that works though.

**Comment by epichosts** [comment]
I noticed that when going to the URL that is shown in 'Execute scheduled tasks from browser', it still executes the cron, even though it shows a login page for the user that went to the URL. Does this happen for anyone else?

**Comment by BelleNottelling** [comment]
Existing releases of FOSSBilling shouldn't do anything to block access to the `cron.php` file, although that has changed with preview releases.
I can make a configurable guest API endpoint (IE: has to be enabled) for calling it, but we are trying to move away from making PHP files generally directly accessible which is why the change was originally introduced.

@epichosts I think that is normal, I know the old behavior was to perform the cron tasks and then to perform a redirect

**Comment by evrifaessa** [comment]
Can you use basic auth to identify with your cron runner? If so, you can authenticate yourself with your admin API token and call the endpoint to trigger the cron jobs.

**Comment by gilesytheking** [comment]
@Anuril thanks for your reply, I have tried both options, but as @epichosts pointed out the cron redirects to the login page, so I wasn't able to get the cron to run correctly and post back to cron-job.org to say the cron had been triggered.

@BelleNottelling I totally agree, its not ideal making php files directly accessible. Not sure if you could make an end point, similar to the run-patcher endpoint that could trigger the cron.php and post a response to say the cron has run successfully.

@evrifaessa there is an option for http auth, but I'm not sure how best to configure this to allow authentication. Cron-job.org does have its own API, so I'm not sure if that could be utilized.

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/5e6c9c60-8f88-492e-b695-e4e3433c8075)

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/c40ee093-fa0d-4279-9e7c-1e74ab30a795)

**Comment by gilesytheking** [comment]
After reading into the Fossbilling API and doing abit more testing, I have been able to execute the cron externally via cron-job.org using the API and http authentication.

For anyone else who may want to run Cron externally here are my steps to get it working.

URL - https://mywebsiteurl/api/admin/cron/run

HTTP User: admin

HTTP Pass: API key from admin users profile (see below screenshot)

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/06152195-8328-4570-a318-f3b233b7ea06)

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/d2aa1fbc-98e1-4867-8c22-757888e420f0)

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/54e4dd8b-c86c-4a4b-a2bf-87a1eb261c1b)
