### ISSUE TITLE
Opt-in error logging and tracking

### ISSUE THREAD

**Issue by BelleNottelling** [FOSSBilling/FOSSBilling#1730]
We should look into options for adding opt-in error reporting for FOSSBilling.

[Sentry.io](https://sentry.io/welcome/) looks to be a great option as it'll allow us to easily add in error logging, offers the ability to collect performance metrics, and comes with a bunch of other really great features like:
- Tracking releases & health: Allowing us to easily identify if a new release introduces a regression in stability, see adoption rate, and track the overall stability of the progress over time
- Built-in tools to scrub any sensitive information to ensure nothing is being logged
- [Certified compliance](https://sentry.io/security/) in terms of security, data handling, and privacy practices
- Data filtering tools
- Great customization
- Just generally a great dashboard to allow us to easily find, filter, sort, and understand the data that's being collected.

If implemented correctly something like Sentry improve our ability to resolve common problems in FOSSBilling and improve the stability of it quickly and easily.

Additionally and counter-intuitively, adding in the additional logging metrics through sentry would *improve* the privacy of FOSSBilling administrators and their clients as rather than needing someone to share an error log which may potentially leak private information, we would instead only need to know the `server_name` that's set for a given install with the Sentry SDK.
Having that would allow us to find errors reported through the dashboard, including more information than what would be found in a standard error log. That info will already be scrubbed of sensitive data and by using the sentry implementation wherever possible, it can reduce the frequency at which someone shares an error log publicly without validating if it may contain sensitive information.

I will experiment with a Sentry implementation and submit a PR if I create what I consider to be a good implementation of it, but if others have any suggestion for other tools that can be used, I'd be happy to hear it

**Comment by John-S4** [comment]
Agree this would be really good and Sentry is a good option. 

This should be explicitly opt-in with the option added to the installer (would also be good if the first update after it is implemented presents the option for existing installs, although that might be a bit more of a hassle to implement?).
