### ISSUE TITLE
[Bug] ResellerClub JSON content was expected to decode to an array "bool" returned

### ISSUE THREAD

**Issue by 2020media** [FOSSBilling/FOSSBilling#1733]
### Describe the bug

When using the "transfer domain" function, an error is returned as follows:

JSON content was expected to decode to an array, "bool" returned for "https://httpapi.com/api/domains/validate-transfer.json?...

I believe this is due to a change introduced in PHP 8 when an error occurs when a boolean variable attempts to become an array 

### How to reproduce

Setup Resellerclub module with correct credentials (I can provide demo creds)
Attempt to place a domain transfer order for a domain using the Resellerclub module.
After pressing "Check" the error is displayed on screen

### Expected behavior

The code should parse the "true" bolean result from the function in  Resellerclub.php 

    public function isDomaincanBeTransferred(Registrar_Domain $domain)
    {
        $params = array(
            'domain-name'       =>  $domain->getName(),
        );
        $result = $this->_makeRequest('domains/validate-transfer', $params, 'GET');
        return (strtolower($result) == 'true');
   }

### FOSSBilling version

0.5.6

### Device

Desktop

**Comment by BelleNottelling** [comment]
Hi, @2020media, to the best of my knowledge none of the active contributors has access to a ResellerClub account.
If you're able to submit a patch that resolves this error, we'd be happy to review it and get it merged.

Thank you!

**Comment by 2020media** [comment]
Unfortunately this error seems deeper with the system than just the module. 
I note that anyone can create a demo account for testing the Logicboxes/Resellerclub API: https://manage.logicboxes.com/kb/node/394

**Comment by jaapmarcus** [comment]
domains/validate-transfer

doesn't exists anymore as endpoint
