### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by andylucena85** [FOSSBilling/FOSSBilling#1750]
### Describe the bug

A 500 error is generated when accessing the installer

### How to reproduce

Write to here!

### Expected behavior

Install

### FOSSBilling version

Latest

### Device

Desktop

### Information

Ubuntu 22.04

### Additional context

I have FOSSBilling at the root of a subdomain, I have assigned permissions to it and installed the corresponding dependencies. When accessing http://subdomain.mydomain.com a 500 error is generated

**Comment by andylucena85** [comment]
php_error.log here
[php-error.txt](https://github.com/FOSSBilling/FOSSBilling/files/13071929/php-error.txt)

**Comment by andylucena85** [comment]
other log here!

[Mon Oct 23 11:03:52.700988 2023] [proxy_fcgi:error] [pid 2146274] [client 172.17.0.2:0] AH01071: Got error 'PHP message: PHP Warning:  require_once(/home/celerteam/web/panel.celerteam.com/public_html/vendor/composer/autoload_real.php): Failed to open stream: No such file or directory

**Comment by jaapmarcus** [comment]
How did you install Fossbilling via https://fossbilling.org/downloads

**Comment by andylucena85** [comment]
wget https://fossbilling.org/downloads/stable

**Comment by BelleNottelling** [comment]
Resolved via discord: downloaded zip was corrupt
