### ISSUE TITLE
[Bug] Text before and after Invoice Items not displaying correctly

### ISSUE THREAD

**Issue by gilesytheking** [FOSSBilling/FOSSBilling#1759]
### Describe the bug

Whilst creating a custom PDF template, I have noticed that there aren't any lines in the default-pdf.twig file to display the Text before and after the Invoice Items table.

I have also noticed that in the web invoice view the Text before Invoice table is displayed after.

### How to reproduce

Invoice -> Texts -> Add text to invoice -> Update -> View invoice

Invoice -> View invoice as client

### Expected behavior

Before text to display before the table on client invoice view.

Both texts to be display on the PDF invoice.

### Screenshots

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/3016915d-90cb-4acc-8855-df28858adc1b)

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/72cb38e1-2689-4549-8412-c153e0ae946c)

### FOSSBilling version

0.5.6

### Additional context

I have patched this on my on my own custom PDF twig file, using the below code. I can provide my custom twig and CSS files if anyone is interested. I have tweaked the PDF layout and CSS to give a more modern look to the PDF invoice.

after line 51 - `<div class='Breakdown' style='top: {{top}}px'>`

```
<div class='text-before'>
<p>{{ invoice.text_1 }}</p>
</div>
```

After line 89 - 	`</table>`

```
<div class='text-after'>
<p>{{ invoice.text_2 }}</p>
</div>
```	

I have also added the following CSS 

```
div.text-before {
    white-space: pre-line;
}


div.text-after {
    white-space: pre-line;
}
```

**Comment by BelleNottelling** [comment]
The before & after text is correctly placed in the default theme so that's an issue with the theme you are using:
![image](https://github.com/FOSSBilling/FOSSBilling/assets/17304943/fb8f8de5-d6f2-4faa-a4c8-38bb8392f36e)


> I have patched this on my on my own custom PDF twig file, using the below code. I can provide my custom twig and CSS files if anyone is interested. I have tweaked the PDF layout and CSS to give a more modern look to the PDF invoice.

If you have an improved template we'd be happy to get a pull request for it, especially since it adds in the missing info.

**Comment by gilesytheking** [comment]
I have submitted a pull request with the above updates to the PDF along with the addition of the bank beneficiary name #1802 

The tide-main theme displays both text after the invoice table, it displays correctly in Huraga.

**Comment by BelleNottelling** [comment]
I'm going to close this as there the bug is for a 3rd party theme and not our own.
