### ISSUE TITLE
Replace direct config references with constants

### ISSUE THREAD

**Issue by BelleNottelling** [FOSSBilling/FOSSBilling#1760]
This issue is mostly just as an open reminder to myself, but I intend to go through the application and replace direct config references with constants instead where applicable.

If we get in the habit of using constants for items then less code needs to be updated in the event that the config structure changes as as long as the name of the constant remains the same, things will still point to the right place.

**Comment by admdly** [comment]
> replace direct config references with constants instead where applicable.

I assume this also, eventually, means dropping `$di['config']` as it won't be necessary?
