### ISSUE TITLE
[Bug] Translation word

### ISSUE THREAD

**Issue by insxa** [FOSSBilling/FOSSBilling#1794]
### Describe the bug

During transalation im notice word error

### How to reproduce

Go to https://fossbilling.crowdin.com/translate/ddc573f086bad0aea827918f4284d176/303/en-sr/20#13644
find word "autoamted " 

### Expected behavior

It should be word automated 

### FOSSBilling version

0.5.6

**Comment by BelleNottelling** [comment]
Thanks for finding that. I've pushed a commit to one of my open PRs to add in the spelling fix for this and will get the translation sources updated once it's merged
