### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#18]

**Comment by gOOvER** [comment]
Crowdin is great and free for OpenSource projects

**Comment by jaapmarcus** [comment]
Crowding or Weblate work both fine. 

We need to decide in the future when more Is know about storage format

**Comment by 0x6b-dev** [comment]
https://github.com/boxbilling/boxbilling/issues/1016

**Comment by evrifaessa** [comment]
I've applied to Crowdin for an open source license.

**Comment by evrifaessa** [comment]
Crowdin just approved our request. That was fast!

**Comment by evrifaessa** [comment]
> do you have the link?

There you go: https://crowdin.com/project/FOSSBilling

**Comment by Komodroid** [comment]
Good job evri!! ❤️

**Comment by Komodroid** [comment]
Hey guys, please add Spanish language!

**Comment by evrifaessa** [comment]
> Hey guys, please add Spanish language!

done.

**Comment by Komodroid** [comment]
> done.
Thank you, I'll start right away.

**Comment by saosangmo** [comment]
@[evrifaessa](https://github.com/evrifaessa)
Could you add Vietnamese language for me?

**Comment by evrifaessa** [comment]
> @[evrifaessa](https://github.com/evrifaessa)
> Could you add Vietnamese language for me?

I can, but you won't be able to translate until the rewrite is over.

**Comment by saosangmo** [comment]
Hope you make the rewrite come over very soon.

**Comment by evrifaessa** [comment]
I can guarantee it's not really coming "very" soon. But we'll do our best.

**Comment by xinomilo** [comment]
can we add new translations/PRs on this repo : https://github.com/FOSSBilling/locale ? 
(prefer to use locally installed poedit, than crowdin)

**Comment by evrifaessa** [comment]
@xinomilo yeah, you can.

**Comment by jaapmarcus** [comment]
Will close the issue.  Translations can be made via Crowdin
