### ISSUE TITLE
[Bug] Cards in the admin theme report wrong numbers

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#185]
**Describe the bug**
![image](https://user-images.githubusercontent.com/35808275/180654612-03139e48-af70-4e01-993c-2091b5317893.png)

The cards above show "12, 32, 12 and 32" no matter what the actual count is.

**To Reproduce**
1. Log in as an admin

**Expected behavior**
Correct numbers should take place

**Comment by phonkala** [comment]
Those seem to be "hardcoded" into `/bb-themes/admin_default/html/mod_index_dashboard.html.twig`
