### ISSUE TITLE
[Feature Request] Add sign in to Google

### ISSUE THREAD

**Issue by chippytech** [FOSSBilling/FOSSBilling#186]
**Is your feature request related to a problem? Please describe.**
Can you add Sign in with Google to FOSSBilling?
**Describe the solution you'd like**
People need to input their own API key and OAuth ID.
**Describe alternatives you've considered**
Sign-in to Apple is okay, but what about Google?
**Additional context**
That's all.

**Comment by John-S4** [comment]
Personally I try to avoid using Google, Facebook, or Apple IDs to sign up for or into anything other than the products of those companies, especially when it is comes to something business related. 

BUT by sheer volume of users I would say that being able to sign in with Google was probably a higher priority than being able to sign in with Apple just due to sheer number of users.

**Comment by jaapmarcus** [comment]
Both methods should be optional and only after enabling from "admin" and not enabled by default

**Comment by kennysinkeler** [comment]
Shouldn't we do this as a separate module?
Also for #124

**Comment by John-S4** [comment]
> Shouldn't we do this as a separate module? Also for #124

Yep, I think this should probably be a separate module. Perhaps one module that covers alternative logins: Google, Apple, oAuth.

**Comment by weismannweb** [comment]
If we do a separate module i dont think licensing conflicts are such an issue if its available from marketplace and not in the core so I would consider using:

https://github.com/hybridauth/hybridauth

thoughts?

**Comment by kennysinkeler** [comment]
> 

laravel has its own: https://github.com/laravel/socialite

**Comment by weismannweb** [comment]
yes i saw that but for some reason i thought it supported like 3 providers, now i see its very good: https://socialiteproviders.com/about/

**Comment by John-S4** [comment]
> laravel has its own: https://github.com/laravel/socialite

This seems like a very good solution. 

We should drop all of these external sign-in (Apple, Google, whatever) from the 0.x roadmap, and plan to implement socialite in 1.0.

**Comment by weismannweb** [comment]
100%

**Comment by jaapmarcus** [comment]
Don't invest any time in adding new providers for the non larval branch. It is a waste of our time. We are going to phase it out anyway

**Comment by John-S4** [comment]
See #1432
