### ISSUE TITLE
[Bug] Error text string in theme Huraga

### ISSUE THREAD

**Issue by insxa** [FOSSBilling/FOSSBilling#1943]
### Describe the bug

In theme Huraga template Profile API Key tab /modules/Client/html_client/mod_client_profile.html.twig
There is twice "Change password" string in both Change Password and API Key tabs

### How to reproduce

In mod_client_profile.html.twig on line 196 instead Change Password shold put API Key

### Expected behavior

It sholud be API Key

### FOSSBilling version

0.5.6

**Comment by admdly** [comment]
Thank you for raising this issue - it will be fixed in the next release. 🙂
