### ISSUE TITLE
[Bug] Unable to add custom field in custom form builder

### ISSUE THREAD

**Issue by DuncanBennie** [FOSSBilling/FOSSBilling#1944]
### Describe the bug

When attempting to create a custom form, the text entry field that is supposed to be present for naming custom form fields is not present.

As shown in the screenshot below, I receive this error when trying to add a field: `Field name can not be empty. Please make sure it is not empty and does not contain special characters. (3502)`

I also have this error in my log at the time of attempting to add a field: `Wrong encoding, conversion from "utf-8" to "us-ascii//TRANSLIT"`

### How to reproduce

1. Go to Settings.
2. Go to Form Builder.
3. Create a new form.
4. Attempt to add a field.

### Expected behavior

Form fields should be nameable and therefore addable.

### Screenshots

![Screenshot 2023-12-09 at 3 54 40 pm](https://github.com/FOSSBilling/FOSSBilling/assets/33364216/eec5c030-bbcc-49bb-88ee-7ba3150a2e36)

### FOSSBilling version

0.5.6

### Device

Desktop

### Information

- Server OS: Alpine Linux
- Desktop OS: macOS 14.1.2
- Browser: Firefox 120.0.1

**Comment by BelleNottelling** [comment]
I am unable to replicate this issue. Can you check and see if there's any errors in your browser console when you try to add them?
![Animation](https://github.com/FOSSBilling/FOSSBilling/assets/17304943/a1d1b85b-baef-418e-961b-9c7b4716ad8b)

**Comment by DuncanBennie** [comment]
Resolved by using the Docker image rather than installing it on an Nginx/SWAG server.
