### ISSUE TITLE
Update Docker Builds to PHP 8.3

### ISSUE THREAD

**Issue by admdly** [FOSSBilling/FOSSBilling#1949]
Docker is currently set to use PHP 8.2 as there is an upstream issue (Imagick/imagick#640) causing our builds to fail when attempting to install `imagick` with PHP 8.3.

Hopefully the fix (Imagick/imagick#641) will be merged soon - opening this issue to track the progress.

Once released I will bump PHP in Docker to 8.3.

**Comment by BelleNottelling** [comment]
> Hopefully the fix ([Imagick/imagick#641](https://github.com/Imagick/imagick/pull/641)) will be merged soon - opening this issue to track the progress.

A single line change submitted to the repo 3 weeks ago with no update from the maintainers. They haven't even approved of the workflow runs. That's not looking promising, lol

**Comment by admdly** [comment]
> A single line change submitted to the repo 3 weeks ago with no update from the maintainers. They haven't even approved of the workflow runs. That's not looking promising, lol

It is unfortunate, especially considering this is the official PHP imagick extension repo. 

Though, I'd rather not work around it if avoidable as it just puts more work on us (albeit minimal) and PHP 8.2 is above our minimum spec at the moment. That said, if it starts to impact on us in any way I'll use the workaround.

**Comment by admdly** [comment]
Looks like we're just waiting on a new release for this to be fixed, which should hopefully occur soon  🤞.

**Comment by BelleNottelling** [comment]
> Looks like we're just waiting on a new release for this to be fixed, which should hopefully occur soon 🤞.

There haven't been any commits in 9 months.. good luck 🤷‍♀️

**Comment by BelleNottelling** [comment]
Given we only recommend the `imagick` extension because of DomPDF, I've gone ahead and asked them to clarify if there's any actual benefit to having both it and the `gd` extension. https://github.com/dompdf/dompdf/discussions/3376.

Hopefully there isn't so we can simply drop it altogether rather than twiddling out thumbs and waiting indefinitely for the compilation issues to *maybe* be fixed.

**Comment by John-S4** [comment]
> I've gone ahead and asked them to clarify if there's any actual benefit to having both it and the `gd` extension. [dompdf/dompdf#3376](https://github.com/dompdf/dompdf/discussions/3376).

Given the reply over there and how minimally we use it I'd say it can be dropped.

**Comment by admdly** [comment]
> Given the reply over there and how minimally we use it I'd say it can be dropped.

Agreed, given that this *still* hasn't been resolved, reliance on `imagick` as a requirement should best be avoided. I'll get a PR up dropping it from the docker image.

Somewhat related - @BelleNottelling it looks like both `GD` and `imagick` are only recommended requirements, is this still correct? I would guess that with both missing, the related PDF functionality would be broken.

**Comment by BelleNottelling** [comment]
> Somewhat related - @BelleNottelling it looks like both `GD` and `imagick` are only recommended requirements, is this still correct? I would guess that with both missing, the related PDF functionality would be broken.

Hmm, indeed GD is only listed as a suggestion and not as a requirement. That replicates the DomPDF docs, but since our template includes an image by default it probably should be required

**Comment by maciejbaba** [comment]
what about building in the docker file magick from source like here?

https://orkhan.dev/2024/02/07/using-imagick-with-php-83-on-docker/
