### ISSUE TITLE
[Bug] Post-setup link broken

### ISSUE THREAD

**Issue by xeruf** [FOSSBilling/FOSSBilling#1951]
### Describe the bug

When using the link to the admin area at the end of the setup, I end up at this URL:
https://billing.deltapeak.de/index.php?_url=/admin

which shows this on the page:
![image](https://github.com/FOSSBilling/FOSSBilling/assets/13354331/89fe84b0-4dab-4d5e-81e8-4fe949a50fbd)

rather than simply redirecting to /admin right away?

### How to reproduce

Run setup
click Admin area

### Expected behavior

redirect to admin area works

### FOSSBilling version

latest

**Comment by BelleNottelling** [comment]
I'm not aware of anyone else who's had issues with the link generated, but starting with 0.6.2 it'll be `/admin` instead of `index.php?_url=/admin`.
