### ISSUE TITLE
Redesign error pages

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#196]
Our error pages are still the same ones as BoxBilling, and to be honest, they are not the most helpful error pages ever.

We should redesign our error pages to include:
* Error codes
* Dark themed (default or per browser configuration)
* A direct link to the relevant section of the documentation (linked by the error code)
* A brief explanation of the problem
* "What can I do?" section for the visitors
* Bug report button, maybe even with some sections prefilled with the error details

**Comment by evrifaessa** [comment]
A quick mockup. Inspired by https://bunny.net/blog/building-better-error-pages/.
I'll change it according to suggestions or start over if needed.

![Group 2](https://user-images.githubusercontent.com/35808275/181111570-45a33e44-a2b2-4883-9384-fee444c16819.png)

**Comment by John-S4** [comment]
That's a good looking and useful error page - I like it a lot.

**Comment by evrifaessa** [comment]
This layout is now implemented into our Laravel branch. I don't know if we should bother with implementing it to the original codebase as well.

**Comment by John-S4** [comment]
IF, and only if, it isn't a lot of hassle, then I think we should. The more consistency (visually and functionally) between the two branches the better as far as users are concerned when it comes to migration.

**Comment by BelleNottelling** [comment]
Due to the significant progress with the original code-base, I think we should re-consider implementing this

**Comment by evrifaessa** [comment]
Another one I've been working on.
![Group 2](https://user-images.githubusercontent.com/35808275/228484192-b0d8ea40-cc5a-4f62-a52e-4569d7288c1e.png)

**Comment by BelleNottelling** [comment]
Error pages got replaced recently and now incorporate functionality so we can give direct links to documentation for specific error codes when we see fit.
