### ISSUE TITLE
[Bug] property Server_Client::$company of type string

### ISSUE THREAD

**Issue by rubenscmf** [FOSSBilling/FOSSBilling#1961]
### Describe the bug

Error
![imagem_2023-12-13_123817304](https://github.com/FOSSBilling/FOSSBilling/assets/153752418/07616f41-583d-42e5-b0d0-fc3f00b7f20a)

### How to reproduce

In home of admin panel

### Expected behavior

No create cpanel plans

### FOSSBilling version

The latest

**Comment by BelleNottelling** [comment]
Hello, @rubenscmf the changes in https://github.com/FOSSBilling/FOSSBilling/pull/1965 should resolve this for you.
I also expect another minor update to come out soon with this fix, but I'm unsure if you're able to access any other aspects of the administrator panel or not to perform an update

**Comment by rubenscmf** [comment]
So far, yes, thank you very much!

**Comment by BelleNottelling** [comment]
Happy to hear it worked!
