### ISSUE TITLE
[Bug] Possible issues with the auto updater

### ISSUE THREAD

**Issue by gilesytheking** [FOSSBilling/FOSSBilling#1975]
### Describe the bug

Not sure if these are bugs or not, but I have noticed the following;

- the updater is not showing the latest version of Foss. Latest is 0.6.3, my install is using 0.6.2. (10 hours since 0.6.3 was published). Does the updater pull directly from Github? Foss Website is showing 0.6.3 as the latest version.

- Updater still shows the update Foss billing button, even when the latest version is installed.

- updates are done in sequence and not directly to the latest version. 0.5.6 -> 0.6.0 -> 0.6.1 -> 0.6.2 instead of 0.5.6 -> 0.6.2.

- I was using the preview build (prior to 0.6.0) on my staging site, but did a manual update to the latest release version. However the updater doesn't seem to be functioning correctly - Still thinks its using a preview build.

### Expected behavior

- Latest version to be shown in auto updater page l when it is released.

- If latest version is installed, update button to be hidden and message to say - Your installation of Foss Billing is up to date.

- Updater should update to the latest version straight away, rather than having to install all the updates in between current installed version and latest
-
- Manual update / apply patches should update preview build to release build.

### Screenshots

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/ccbbbcab-34c5-48d1-a7a3-cdd5f64147d1)

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/2d796089-a8ad-4153-9261-31496aa8db42)

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/8371e1c1-9fe5-4c03-b760-5a9609baf2c6)

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/edb887a5-ec76-4cd8-8f96-dea82990c4de)

### FOSSBilling version

0.6.2

### FOSSBilling instance ID

937f3585-788d-4528-abfe-acaf2ec45d07

### Device

Desktop

**Comment by BelleNottelling** [comment]
None of these are bugs really, just a misunderstanding the current implementation.

> the updater is not showing the latest version of Foss. Latest is 0.6.3, my install is using 0.6.2. (10 hours since 0.6.3 was published). Does the updater pull directly from Github? Foss Website is showing 0.6.3 as the latest version.

Both pull directly from GitHub. You're seeing 0.6.2 because it checks the latest release and then caches that result for 24 hours. Clearing the cache will cause it to fetch this again and display the most recent release.

> Updater still shows the update Foss billing button, even when the latest version is installed.

Nothing was ever setup to do so, so technically this isn't a bug either. I have plans to refine the update screen a bit though, and I'll also make this a bit more clearer then.

> updates are done in sequence and not directly to the latest version. 0.5.6 -> 0.6.0 -> 0.6.1 -> 0.6.2 instead of 0.5.6 -> 0.6.2.

I'm not sure what's made you think this is the case, but it's not possible with the current implementation. FOSSBilling pulls the latest version via the GitHub API using this endpoint: https://api.github.com/repos/FOSSBilling/FOSSBilling/releases/latest.
That endpoint only has info on the most recent release, so it's impossible for anything except the latest to be downloaded and updated to.

> I was using the preview build (prior to 0.6.0) on my staging site, but did a manual update to the latest release version. However the updater doesn't seem to be functioning correctly - Still thinks its using a preview build.

It's functioning as intended. The update branch is [configurable](https://github.com/FOSSBilling/FOSSBilling/blob/main/src/config-sample.php#L63-L67) via your config file to allow someone to switch between between release and preview builds and then perform the update via the admin panel. Once you change it to `release`, it will show update info for releases.

**Comment by gilesytheking** [comment]
> Both pull directly from GitHub. You're seeing 0.6.2 because it checks the latest release and then caches that result for 24 hours. Clearing the cache will cause it to fetch this again and display the most recent release.
> 

Good to know. I have cleared cache and got the latest update. Again thanks for the quick response for the invoice issue.

> Nothing was ever setup to do so, so technically this isn't a bug either. I have plans to refine the update screen a bit though, and I'll also make this a bit more clearer then.
> 

Perfect. As with other platforms the update button only shows, when an update is available. Might be confusing for users.

> I'm not sure what's made you think this is the case, but it's not possible with the current implementation. FOSSBilling pulls the latest version via the GitHub API using this endpoint: https://api.github.com/repos/FOSSBilling/FOSSBilling/releases/latest. That endpoint only has info on the most recent release, so it's impossible for anything except the latest to be downloaded and updated to.
> 

When I updated from 0.5.6, the latest version at the time was 0.6.1. The updater showed 0.6.0 as the latest version. Once I had installed that, the updater then show 0.6.1. Perhaps this was to do with the cache as you have already mentioned.

> It's functioning as intended. The update branch is [configurable](https://github.com/FOSSBilling/FOSSBilling/blob/main/src/config-sample.php#L63-L67) via your config file to allow someone to switch between between release and preview builds and then perform the update via the admin panel. Once you change it to `release`, it will show update info for releases.
>

Thanks for the info, that's actually really handy for my staging site. I'm still getting to grips with all the options and settings.

**Comment by BelleNottelling** [comment]
> Good to know. I have cleared cache and got the latest update. Again thanks for the quick response for the invoice issue.

You're welcome

> When I updated from 0.5.6, the latest version at the time was 0.6.1. The updater showed 0.6.0 as the latest version. Once I had installed that, the updater then show 0.6.1. Perhaps this was to do with the cache as you have already mentioned.

It probably is, yeah.

> Thanks for the info, that's actually really handy for my staging site. I'm still getting to grips with all the options and settings.

The only thing to keep in mind is that the existing system isn't designed to perform backwards patching so going from a preview build to an older release may not work in some cases depending on what's been changed in the preview builds, but it should be relatively uncommon.
