### ISSUE TITLE
[Bug] Error in login page after install

### ISSUE THREAD

**Issue by agjunior** [FOSSBilling/FOSSBilling#198]
**Describe the bug**
The admin login page doesn't work after a fresh install.

![screenshot-local fossbilling org-2022 07 26-19_27_27](https://user-images.githubusercontent.com/4437044/181123457-e4baefaa-35d5-4a91-bfca-83189de44269.png)

**Comment by jaapmarcus** [comment]
Make sure to follow the instruction in the readme.md or download the preview version

**Comment by agjunior** [comment]
The build with gulp is also showing errors:

```
[19:53:41] Requiring external module babel-register
TypeError: Cannot read properties of undefined (reading 'replace')
```

**Comment by agjunior** [comment]
I copied the preview template for now. But gulp is very outdated.
