### ISSUE TITLE
[Bug] Hide empty phone number from invoice PDF footer

### ISSUE THREAD

**Issue by xeruf** [FOSSBilling/FOSSBilling#1998]
### Describe the bug

Invoice PDF download:
![image](https://github.com/FOSSBilling/FOSSBilling/assets/13354331/db9872b8-66c7-4bf3-911f-445ff751104b)

### How to reproduce

We added the company name and email, and removed the phone number in `/admin/extension/settings/system` because we do not offer phone service. Yet the phone number keeps reappearing and the company name and email are also incorrect.

### Expected behavior

company name and email substituted by configured values, telephone number omitted entirely

### FOSSBilling version

0.6.4

### Additional context

I am translating all relevant strings to German on crowdin following https://github.com/FOSSBilling/FOSSBilling/pull/1967 so we can start using FOSSBilling this week, would appreciate another release after resolving this :)
Related to https://github.com/FOSSBilling/FOSSBilling/issues/1681

**Comment by xeruf** [comment]
Nevermind, it worked fine in a new invoice.
The only thing remaining here is that if the phone number is empty it should be fully omitted from the footer.

**Comment by BelleNottelling** [comment]
> Nevermind, it worked fine in a new invoice.

Yes, the current system stores company & client info in each Invoice so they don't pull in the latest date when you go back and revisit them.

>  The only thing remaining here is that if the phone number is empty it should be fully omitted from the footer.

I'll take a look at that at some point, but you can pretty easily just use a custom template to remove / add whatever you'd like:
https://fossbilling.org/docs/customizing-fossbilling/invoice_pdf#invoice-html

**Comment by admdly** [comment]
> Yes, the current system stores company & client info in each Invoice so they don't pull in the latest date when you go back and revisit them.

That may very well be a legal requirement in some jurisdictions - invoices can be considered legal documents that should not be modified once issued.
