### ISSUE TITLE
Version constraints for modules and themes

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#200]
Modules and themes should have version constraints. Developers should be able to specify what minimum/exact/maximum version of FOSSBilling the module/theme is made to work with.

The example below is from [Composer docs](https://getcomposer.org/doc/articles/versions.md). We could follow a similar approach.

![image](https://user-images.githubusercontent.com/35808275/181913851-e1b0fe99-3200-4499-b69a-4adc14a199e0.png)

**Comment by evrifaessa** [comment]
We could use the [composer/semver](https://packagist.org/packages/composer/semver) package for this one.

**Comment by BelleNottelling** [comment]
Closing and merging into #409 as this is ultimately a sub-item of that issue.
