### ISSUE TITLE
[Feature Request] Translating to Persian/Farsi

### ISSUE THREAD

**Issue by UnrivaledIr** [FOSSBilling/FOSSBilling#2001]
Hello, I recently became familiar with this project and I'm very interested in it. I believe this project has a great future and I want to have a small share in its development. So, please add a Persian translation section (there isn't any Farsi section in [Crowdin](https://fossbilling.crowdin.com/fossbilling)) so I can also contribute. I hope to be able to participate technically in the future as well. Thank you.

Sincerely

**Comment by BelleNottelling** [comment]
Just added it, so you should now see it as an option
