### ISSUE TITLE
Limited functionality for clients on mobile devices

### ISSUE THREAD

**Issue by adamh2021** [FOSSBilling/FOSSBilling#2031]
### Describe the bug

Clients have a limited menu when on a smartphone - they can only see the following menu items:

- Dashboard
- Order
- Profile
- Sign out

### How to reproduce

Login to a client account on a smart phone - hamburger menu limited.

### Expected behavior

When accessing the admin login, you can access full menu and functionality on a mobile device. It would be nice for clients to be able to access all menu items and functionality as they would when logging in via a desktop / laptop. 

### Screenshots

![Screenshot_20231230_112334_Chrome](https://github.com/FOSSBilling/FOSSBilling/assets/94173435/fff5deca-edf5-4400-8160-5a3aa69d5f1c)
![Screenshot_20231230_112345_Chrome](https://github.com/FOSSBilling/FOSSBilling/assets/94173435/c533fb71-ca67-40e4-8692-192b574a330e)

### FOSSBilling version

0.6.6

### Device

Smartphone

### Information

Samsung S22 Ultra 

### Additional context

Not sure of this has been highlighted before, I couldn't see anything reported. If it has, apologies.

**Comment by BelleNottelling** [comment]
Closed via #2031, will be in the next release

**Comment by adamh2021** [comment]
Awesome - thanks all!
