### ISSUE TITLE
[Feature Request] TeX templates

### ISSUE THREAD

**Issue by xeruf** [FOSSBilling/FOSSBilling#204]
**Is your feature request related to a problem? Please describe.**
We have been searching for a while for the billing solution that fits us, and they often lacked flexibility when it comes to templating.

**Describe the solution you'd like**
Would you consider a templating system using TeX (LaTeX or ConTeXt), because this is simply *the* typesetting system to create professional documents?

**Describe alternatives you've considered**
An image or PDF of our letter paper which can be included as background - but that might look off.

Maybe this could be realised through something like Emacs Org-mode, which allows you to put the content first and then typeset it with different systems and templates.

**Comment by jaapmarcus** [comment]
What would be the advantages of Tex vs Twig what Fossbilling is allready using?

**Comment by xeruf** [comment]
Professional typesetting, and reusability of designs across different environments :)

**Comment by jaapmarcus** [comment]
But it will lack a lot of options to integrate with Laravel so it will be impossible to integrate to a level we need.
