### ISSUE TITLE
[FORUM] Error 401 when registering using GitHub Account

### ISSUE THREAD

**Issue by semplon** [FOSSBilling/FOSSBilling#2057]
Hello, I want to register at forum with my github Account, but there was error occured upon registration process. 

![image](https://github.com/FOSSBilling/FOSSBilling/assets/3163608/d41da7b7-3215-45d8-9459-7b6d9f66814e)

**Comment by John-S4** [comment]
@semplon Can you try it again (if you haven't already registered using another method), I have just tried it with a test GH account and it worked for me.

**Comment by semplon** [comment]
Hello @John-S4 , it worked now. 
Thank You

**Comment by jaapmarcus** [comment]
Closing issue
