### ISSUE TITLE
[Bug] Custom Invoice Twig Template suddenly stopped working

### ISSUE THREAD

**Issue by woutr-nl** [FOSSBilling/FOSSBilling#2070]
### Describe the bug

I've created a custom twig template which was working like a charm. After a day or 2 i wanted to create an invoice, and when i checked the invoice the whole layout was broken. It does seem something is going wrong in the CSS or something. Editing specific things like hiding an h3 or something still is working, but for example the background is completely gone.

### How to reproduce

1. Create custom-pdf.twig in the Invoice folder
2. Add the code below

```
{% if buyer_lines >= seller_lines %}
	{% set top = 325 + (25 * buyer_lines) %}
{% else %}
	{% set top = 325 + (25 * seller_lines) %}
{% endif %}

{% set address_lines = [] %}
	{% for line in [footer.address_1, footer.address_2, footer.address_3] %}
		{% if line|length > 0 %}
			{% set address_lines = address_lines|merge([line]) %}
		{% endif %}
	{% endfor %}
{% set address = address_lines|join(',') %}

<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
		<title>{{ invoice.serie_nr }}</title>
		<style>
			{{css}}
			body {
				background-image: url('https://cdn.woutr.io/images/briefpapier.jpg');
				background-size: cover;
				background-repeat: no-repeat;
				background-attachment: fixed;
				margin: 0;
				padding: 0;
			}
			.container {
				margin: 20px; /* Adjust the margin size as needed */
				padding: 0;
			}
			.breakdown {
				width: 80%; /* Adjust the margin-top value as needed */
				padding-right: 20px;
			}
			@page {
				size: A4;
				margin: 0;
			}
			html, body {
				height: 100%;
			}
			
            table {
                border-collapse: collapse;
            }
            
            p {
                font-size: 18px;
            }
            
            tr:nth-of-type(odd) {
                background-color: rgba(41,127,185, 0.2);
            }
            
            .right{
                text-align:right;
            }
            
		</style>
	</head>
	<body>
	    <div class="container">
		{#{% if logo_source is not empty %}#}
		{#	<img src='{{ logo_source }}' height='50' class='CompanyLogo'>#}
		{#{% endif %}#}
		{#<hr class='Rounded'>#}

		{#<h3 class='CompanyInfo'>{{ 'Company'|trans }}</h3>#}
		{#<div class='CompanyInfo'>#}
		{#<p>#}
		{#{% for key, value in seller %}#}
		{#{% if key == 'Name' %}<b>{% endif %}#}
		{#{% if key == 'Phone' %} Tel:{% endif %}#}
		{#		{{ value }}<br>#}
		{#{% if key == 'Name' %}</b>{% endif %}#}
		{#{% endfor %}#}
		{#</p>#}
		{#</div>#}

		{#<h3 class='ClientInfo'>{{ 'Client'|trans }}</h3>#}
		<div class='ClientInfo'>
		<p>
		{% for key, value in buyer %}
		{% if key == 'Company' %}<b>{% endif %}
		{% if key == 'Phone '%} Tel:{% endif %}
				{{ value }}<br>
		{% if key == 'Company' %}</b>{% endif %}
		{% endfor %}
		</p>
		</div>

		<div class='Breakdown' style='top: {{top}}px'>
			<table style='width:750px'>
				<tr>
					<th style='text-align: center'>{{ 'Product'|trans }}</th>
					<th style='text-align: left'></th>
					<th style='text-align: center'>{{ 'Hoeveelheid & Prijs'|trans }}</th>
					<th style='text-align: center'>{{ 'Totaal'|trans }}</th>
				</tr>
				{% set nr = 0 %}
				{% for item in invoice.lines %}
					{% set nr = nr + 1 %}
					<tr>
					    <td style='text-align: center'>{{ item.title }}</td>
						<td style='text-align: left; width:25px;'></td>
						<td style='text-align: center'>{{ item.quantity }}x {{ item.price|money(currency_code) }}</td>
						<td style='text-align: center'>{{ item.total|money(currency_code) }}</td>
					</tr>
				{% endfor %}
				<tr>
					<th colspan='4'>______________________________________________________________________________________________</th>
				</tr>
				{% if invoice.tax > 0 %}
					<tr>
						<th style='text-align: right' colspan='3'>{{ invoice.taxname }}
							{{ invoice.taxrate }}% :</th>
						<th style='text-align: center'>{{ invoice.tax|money(currency_code) }}</th>
					</tr>
				{% endif %}
				{% if invoice.discount|default and invoice.discount > 0 %}
					<tr>
						<th style='text-align: right' colspan='3'>{{ 'Discount'|trans }}:</th>
						<th style='text-align: center'>{{ invoice.discount|money(currency_code) }}</th>
					</tr>
				{% endif %}
				<tr>
					<th style='text-align: right'  colspan='3'>{{ 'Total'|trans }}:</th>
					<th style='text-align: center'>{{ invoice.total|money(currency_code) }}</th>
				</tr>
			</table>
		{#<p>{{ footer.signature }}</p>#}
		</div>
		<div class='InvoiceInfo'>
			<p>{{ 'Factuurnummer'|trans }}: {{ invoice.serie_nr }}</p>
        <p>{{ 'Factuurdatum'|trans }}: {{ invoice.created_at|date('d/m/Y') }}</p>
        <p>{{ 'Verloopdatum'|trans }}: {{ invoice.due_at|date('d/m/Y') }}</p>
			{#<p>{{ 'Status'|trans }}: {{ invoice.status|capitalize }}</p>#}
            <p>{{ 'Status'|trans }}: 
               <span style="{% if invoice.status == 'unpaid' %}color: red;{% elseif invoice.status == 'paid' %}color: green;{% endif %}">
                  {% if invoice.status == 'unpaid' %}
                      Niet betaald
                  {% elseif invoice.status == 'paid' %}
                      Betaald
                  {% else %}
                      Onbekend
                  {% endif %}
               </span>
            </p>

		</div>
		{#<div class='InvoiceFooter'>#}
		{#	{% if footer.display_bank_info == 1 %}#}
		{#		<b>{{ 'Payment details'|trans }}:</b><br >#}
		{#		<b>{{ 'Account Owner'|trans }}:</b> {{ footer.company_name }} | <b>{{ 'Bank'|trans }}:</b> {{ footer.bank_name }} | <b>{{ 'BIC / SWIFT Code'|trans }}:</b> {{ footer.bic }} | <b>{{ 'Account number'|trans }}:</b> {{ footer.account_number }}<br><br>#}
		{#	{% endif %}#}

		{#	<b>{{ footer.company_name }}</b>#}
		{#	{% if address %} {{ address }} <br> {% endif %}#}
		{#	<b>{{ 'Email'|trans }}:</b> {{ footer.email }} | <b>#}
		{#	{% if footer.phone %} {{ 'Phone'|trans }}:</b> {{ footer.phone }}<br> {% endif %}#}
		{#	{% if footer.company_vat %} <b>{{ 'VAT ID'|trans }}:</b> {{ footer.company_vat }} | {% endif %}#}
		{#	{% if footer.company_number %} <b>{{ 'Company Registration #:'|trans }}</b> {{ footer.company_number }} | {% endif %}#}
		{#	<b>{{ 'Website'|trans }}: </b>{{ footer.www }}#}
		{#</div>#}
		</div>
	</body>
</html>
```

### Expected behavior

I don't have a good screenshot on how the PDF should be showing.

### FOSSBilling version

0.6.9 ( Last update check: 15 jan. 2024 09:17 )

### FOSSBilling instance ID

91dc8263-ebf6-4deb-88c7-cce73c4ed292

### Device

Desktop

### Information

Chrome ( Version 120.0.6099.217 (Official build) (64-bits)

**Comment by BelleNottelling** [comment]
I am fairly certain the issue is your template and not a bug in FOSSBilling.
We use DomPDF under the hood for rendering and it doesn't support all CSS and HTML functionality (See [our docs](https://fossbilling.org/docs/customizing-fossbilling/invoice_pdf#limitations) and their [readme](https://github.com/dompdf/dompdf)).

Additionally, you have nearly everything commented out in the invoice so it's going to render a mostly empty page, even if all CSS is being applied as expected:
![image](https://github.com/FOSSBilling/FOSSBilling/assets/17304943/e47fb366-d465-4c6e-816d-4388a71d6d95)


> but for example the background is completely gone.

You're referencing an external image. Try downloading it, placing it on your server, and using it's local path in your template

**Comment by woutr-nl** [comment]
Hey Belle,

Thanks. I've looked into it but i can't really seem to find out what is going wrong.
Somehow it looks like an image is not being rendered anymore..

**Comment by woutr-nl** [comment]
Is there some sort of 'documented way' of adding an background image to a custom invoice? I don't think i'm the only business who would like to use a background on a PDF invoice.

**Comment by woutr-nl** [comment]
Been trying it with local path now, base64 etc. Nothing works. It's all compliant to the rules (CSS2.1 etc). What is causing this?

**Comment by BelleNottelling** [comment]
I was able to get this to work correctly using base64. Specifically utilizing this site & copying the CSS tag it provided:
https://www.base64-image.de/

I was also able to get it to work using a remote image and changing the company logo to a URL which forces FOSSBilling to enable remote content for DomPDF (it's disabled by default for improved security). I would not use this option though as DomPDF appears to re-fetch the image on each PDF render which causes the process to take quite a bit longer and use extra bandwidth for no benefit.

![image](https://github.com/FOSSBilling/FOSSBilling/assets/17304943/fa4c52d6-92ff-4cd9-a0ae-182c7e028e67)

However, I was not able to get it work correctly by providing a path to DomPDF and I am unsure if that's a *me* issue or a bug on their end.

**Comment by woutr-nl** [comment]
Hey Belle,

That's weird. I've been trying it with that site too.
Can you provide me with your custom twig file? Just curious if i see any differences.

**Comment by BelleNottelling** [comment]
> Can you provide me with your custom twig file? Just curious if i see any differences.

Yes: [custom-pdf.zip](https://github.com/FOSSBilling/FOSSBilling/files/14017487/custom-pdf.zip)

> The weird thing is that i already had an external URL as logo by the way:

Do you also have `allow_url_fopen` set to `true` in your PHP ini settings as per the system requirements? That's what DomPDF uses to fetch remote content

**Comment by BelleNottelling** [comment]
Providing a local path also works fine.. I just accidentally had a typo in mine when testing

**Comment by woutr-nl** [comment]
Quite weird, with you base64 it works. Thanks!!!!!!

**Comment by BelleNottelling** [comment]
> Quite weird, with you base64 it works. Thanks!!!!!!

You're welcome
