### ISSUE TITLE
[Bug] Installation ERROR FAIL Check system requirements

### ISSUE THREAD

**Issue by VGzsysadm** [FOSSBilling/FOSSBilling#2090]
### Describe the bug

On fresh installation an error is shown:

Installation is blocked because you do not meet one or more system requirements.

/var/www/html/config.php | FAIL | Please make sure that file exists and is writable.

Only exist config-sample.php

If you create the file config.php

An other error is shown:

FOSSBilling is already installed. If you are trying to reinstall, take the following steps:

Delete your database tables or recreate your database.
Delete config.php.
Refresh this page and you will see the installer.

### How to reproduce

1- Fresh installation
2-  ERROR -> /var/www/html/config.php | FAIL | Please make sure that file exists and is writable.
3- Only exist config-sample.php
4- You create the file config.php
5- Other error shown:
FOSSBilling is already installed. If you are trying to reinstall, take the following steps:
6- Remove config.php
7- Return to step 2

You are stuck

### Expected behavior

Install the software.

### FOSSBilling version

0.6.9

**Comment by jaapmarcus** [comment]
Check error logs

**Comment by VGzsysadm** [comment]
![1](https://github.com/FOSSBilling/FOSSBilling/assets/39667448/9b002d46-9fc5-43b2-8039-00e821209312)
![2](https://github.com/FOSSBilling/FOSSBilling/assets/39667448/02b9ca15-a25a-44f5-b562-b9d24f9442e2)

There's no errors on /var/log/apache2/error.log

**Comment by jaapmarcus** [comment]
Delete config.php first...

**Comment by BelleNottelling** [comment]
The error message displayed is misleading.. I thought I had changed that already, but clearly not.
It tries to check the permissions by creating and then deleting the file, so if you're seeing that error you have a permissions issue where PHP is unable to create new files

**Comment by jaapmarcus** [comment]
> The error message displayed is misleading.. I thought I had changed that already, but clearly not. It tries to check the permissions by creating and then deleting the file, so if you're seeing that error you have a permissions issue where PHP is unable to create new files

If the file can't be created we should just display the generated config.php and as the user to create it. Like Wordpress does...

**Comment by BelleNottelling** [comment]
> If the file can't be created we should just display the generated config.php and as the user to create it. Like Wordpress does...

I don't think that's a sufficient fix. If PHP can't create the file, it probably can't write to it either which is essential behavior we rely on. If it can't create the config file, it also probably can't create cache files which again is behavior we really want to have working correctly

**Comment by jaapmarcus** [comment]
For cache folder users can always apply the correct file permissions.

For config.php php should really need it ..

**Comment by getpinga** [comment]
Yes, running into the same bug, so had to do manual install of my test installations.

**Comment by BelleNottelling** [comment]
I'm going to close this.
The message displayed will be revised in the release to be less confusion and provide a link to the [troubleshooting docs](https://fossbilling.org/docs/troubleshooting#permission-issues) for permissions.

Ultimately, nothing indicates that there's a bug on our end and everything points to a permissions issue on your server.
