### ISSUE TITLE
Resellerclub domain registration failing

### ISSUE THREAD

**Issue by adamh2021** [FOSSBilling/FOSSBilling#2096]
### Describe the bug

When a customer purchases a domain with or without web hosting, the registration to resellerclub is failing and is reporting: 

`API RESULT: {"domainname.com":{"classkey":"thirdleveldotuk","status":"available"}}	`

`Registrar_Exception: HttpClientException: HTTP/2 500 returned for "https://httpapi.com/api/domains/orderid.json?domain-name=domainname.com&auth-userid=99999&api-key=our_api_key". in /fossbilling_directory/public_html/library/Registrar/Adapter/Resellerclub.php:723 Stack trace: #0 /fossbilling_directory/public_html/library/Registrar/Adapter/Resellerclub.php(227): Registrar_Adapter_Resellerclub->_makeRequest() #1 /fossbilling_directory/public_html/library/Registrar/Adapter/Resellerclub.php(642): Registrar_Adapter_Resellerclub->_getDomainOrderId() #2 /fossbilling_directory/public_html/library/Registrar/Adapter/Resellerclub.php(297): Registrar_Adapter_Resellerclub->_hasCompletedOrder() #3 /fossbilling_directory/public_html/modules/Servicedomain/Service.php(224): Registrar_Adapter_Resellerclub->registerDomain() #4 /fossbilling_directory/public_html/modules/Order/Service.php(776): Box\Mod\Servicedomain\Service->action_activate() #5 /fossbilling_directory/public_html/modules/Order/Service.php(714): Box\Mod\Order\Service->_callOnService() #6 /fossbilling_directory/public_html/modules/Order/Service.php(658): Box\Mod\Order\Service->createFromOrder() #7 /fossbilling_directory/public_html/modules/Order/Service.php(688): Box\Mod\Order\Service->activateOrderAddons() #8 /fossbilling_directory/public_html/modules/Cart/Service.php(663): Box\Mod\Order\Service->activateOrder() #9 /fossbilling_directory/public_html/modules/Cart/Service.php(465): Box\Mod\Cart\Service->createFromCart() #10 /fossbilling_directory/public_html/modules/Cart/Api/Client.php(29): Box\Mod\Cart\Service->checkoutCart() #11 /fossbilling_directory/public_html/library/Api/Handler.php(110): Box\Mod\Cart\Api\Client->checkout() #12 /fossbilling_directory/public_html/modules/Api/Controller/Client.php(183): Api_Handler->__call() #13 /fossbilling_directory/public_html/modules/Api/Controller/Client.php(83): Box\Mod\Api\Controller\Client->_apiCall() #14 /fossbilling_directory/public_html/modules/Api/Controller/Client.php(74): Box\Mod\Api\Controller\Client->tryCall() #15 [internal function]: Box\Mod\Api\Controller\Client->post_method() #16 /fossbilling_directory/public_html/library/Box/App.php(242): ReflectionMethod->invokeArgs() #17 /fossbilling_directory/public_html/library/Box/App.php(400): Box_App->executeShared() #18 /fossbilling_directory/public_html/library/Box/App.php(181): Box_App->processRequest() #19 /fossbilling_directory/public_html/index.php(94): Box_App->run() #20 {main}	
`

### How to reproduce

Resellerclub account needed

Reseller ID, and API key needed - from Resellerclub and API whitelisting 

Admin or Customer order a domain name - domain availability seems to work, but purchase seems to fail. 

### Expected behavior

When a customer or admin places an order for a domain, for the order to be sent through to Resellerclub. I've read some previous posts on similar issues regarding Resellerclub API. I appreciate FossB is pre-production but it is a web hosting billing platform and domain sales is part of that - so some development on the Domain Registry API's would not only benefit me, but also FossBilling and its customer base - I did also open a feature request for DNS management in resellerclub plugin. 

In the nicest possible way...these are basic needs for web hosting / billing :)

### FOSSBilling version

0.6.10

### FOSSBilling instance ID

9bf99362-739e-443c-90e1-d416d2f2b4e7

### Device

Desktop

**Comment by jaapmarcus** [comment]
https://github.com/FOSSBilling/FOSSBilling/issues/1733
https://github.com/FOSSBilling/FOSSBilling/issues/77

There are more issues with it. But due to the fact that

```
The server returned a "405 Method Not Allowed".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

When I try to contact for support...
```

When I try to fill in a https://www.resellerclub.com/domain-reseller/api  -> Get dedicated assistance or have to pay at least 25 dollar with out even never to know it ... 

It is great...

**Comment by adamh2021** [comment]
> #1733 #77
> 
> There are more issues with it. But due to the fact that
> 
> ```
> The server returned a "405 Method Not Allowed".
> 
> Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
> 
> When I try to contact for support...
> ```
> 
> When I try to fill in a https://www.resellerclub.com/domain-reseller/api -> Get dedicated assistance or have to pay at least 25 dollar with out even never to know it ...
> 
> It is great...

Try: https://www.resellerclub.com/domain-reseller/signup-now

Sign up should be free...then you can contact the support desk.

**Comment by jaapmarcus** [comment]
It was not able to skip it ...

**Comment by BelleNottelling** [comment]
> Try: https://www.resellerclub.com/domain-reseller/signup-now
> 
> Sign up should be free...then you can contact the support desk.

I previously looked to make a Resellerclub account to investigate the issues and while they allow you to create an account without paying money, you are **immediately** hit with a paywall before you are allowed to do a single thing.

**Comment by adamh2021** [comment]
@BelleNottelling @jaapmarcus 

Send me a screen shot of how much they want and a private message to send a payment over to you.

If your willing to invest time and skill...I have to be willing to play my part and dip in my pocket to help out, try to fix this extension and maybe add DNS management at the same time...but first and foremost...a fix. 

Sound like a plan?

**Comment by jaapmarcus** [comment]
<img width="561" alt="Screenshot 2024-01-25 at 11 09 55" src="https://github.com/FOSSBilling/FOSSBilling/assets/9754650/fee553e1-ffba-4ddc-9031-3b0f3ecb7d6d">

If you are DM just call @jaapmarcus in our public discord channel and I will send you a DM

<img width="794" alt="Screenshot 2024-01-25 at 11 21 50" src="https://github.com/FOSSBilling/FOSSBilling/assets/9754650/f33edaec-1fa0-4add-993a-ce826daba794">

**Comment by jaapmarcus** [comment]
After a few days (and a week of cold / fever ...)  I finally got access to the dashboard and ran some tests:

What works:

- Whois works 
- Creating a customer works ...

What doesn't works 

Everything else ...

First of all:
https://github.com/FOSSBilling/FOSSBilling/blob/a0323e8da2f6845dc20f28bbfe97f5ce757e3789/src/library/Registrar/Adapter/Resellerclub.php#L994-L1016

If an Customer already exists in their system you can't simply delete them...
