### ISSUE TITLE
[Bug] Creating new user account on cPanel, problem while password generating.

### ISSUE THREAD

**Issue by jokerrs** [FOSSBilling/FOSSBilling#2130]
### Describe the bug

random_int(): Argument #1 ($min) must be less than or equal to argument #2 ($max) at /var/www/fossbilling/library/FOSSBilling/Tools.php:143

```php
          default:
                $lower = random_int(1, $length - 3);
                $upper = random_int(1, $length - $lower - 2);
                $numeric = random_int(1, $length - $lower - $upper - 1);
                $other = $length - $lower - $upper - $numeric;
```

### How to reproduce

Create cPanel account thru FOS

### Expected behavior

cannot create cPanel account

### FOSSBilling version

latest

### Additional context

After putting the following code, and hard coding the password length , everything is working just fine.

```php
            default:
                $lower = random_int(1, 8);
                $upper = random_int(1, 8);
                $numeric = random_int(1, 8);
                $other = $length - $lower - $upper - $numeric;

                break;
```

**Comment by BelleNottelling** [comment]
First time I've seen this issue occur. What password length did you configure for the cPanel sever when you added it?
Regardless I've been meaning to take a look at and refactor the password generation function so I suppose now's as good at time as ever, lol
