### ISSUE TITLE
[Feature Request] OnlineNIC Registrar

### ISSUE THREAD

**Issue by komputronika** [FOSSBilling/FOSSBilling#2138]
I've been using OnlineNIC for years. Could the OnlineNIC registrar module be added to FOSSBilling?

https://wiki.onlinenic.com/#!DomainFunction.md

Thank you

**Comment by getpinga** [comment]
I'm developing some external modules, and I will add this to my wishlist. Can not guarantee though that it will happen very fast.

**Comment by John-S4** [comment]
Added this to the list of community requested domain registrars - #1414
