### ISSUE TITLE
[Bug] Cron jobs - Not run warning

### ISSUE THREAD

**Issue by techhost01** [FOSSBilling/FOSSBilling#2160]
### Describe the bug

Even after scheduling the cron jobs in cPanel the FOSSBilling platform is giving me the notification that the 'Danger! [FOSSBilling has detected that cron hasn't been run in an abnormal time period. Please ensure the cronjob is configured to be run every 5 minutes. (Message will remain for 15 minutes)](https://billing.techinhost.com/admin/extension/settings/cron)'

When clicking on it shows that the cron jobs are running 'Last time scheduled tasks were executed: | Feb 21, 2024, 5:44 AM (1 minute ago)'

Not sure, what I'm missing or why is it showing this here. I have schedule it to run every minute

### How to reproduce

Login to FossBilling to see the error.
Click on it to see that its working and ran just a minute ago

### Expected behavior

It should not show this Danger warning, when the Cron jobs are running fine

### Screenshots

![Screenshot 2024-02-21 094815](https://github.com/FOSSBilling/FOSSBilling/assets/160702714/cde9fd14-a7f5-4849-953e-53f6564d8db1)
![Screenshot 2024-02-21 094807](https://github.com/FOSSBilling/FOSSBilling/assets/160702714/c46e6374-31dc-41e0-9116-d16341bc918d)

### FOSSBilling version

0.6.14

### Device

Desktop

**Comment by BelleNottelling** [comment]
When the message appears, FOSSBilling also executes the cron job in the background, so that's not actually indicating that it's working. Check back about 5 min after the error appears and you should see the last execution time will continue to rise.

See the troubleshooting docs which covers this and some more info:
https://fossbilling.org/docs/troubleshooting#issues-with-cron

**Comment by BelleNottelling** [comment]
We were able to resolve this via discord.
Problem was with how cron was setup and it prevented FOSSBilling from correctly detecting that it's being run under CLI.

Changing the cron command resolved it.
```diff
- /usr/bin/php /home/example/billing.example.com/cron.php
+ /usr/local/bin/php /home/example/billing.example.com/cron.php
```

As far as I can tell, there's no way for us to fix it as we are already using [3 different methods](https://github.com/FOSSBilling/FOSSBilling/blob/main/src/library/FOSSBilling/Environment.php#L63) of detecting CLI usage and I'm not aware of any other (reliable) methods.
