### ISSUE TITLE
[Bug] Custom form builder should not allow certain field names

### ISSUE THREAD

**Issue by aphick** [FOSSBilling/FOSSBilling#2169]
### Describe the bug

I was trying to hack on the custom service registration, and when using a field called `domain`, I encountered the error:
```
Cannot access offset of type string on string at /var/www/0.6.15/modules/Cart/Service.php:543
```
The line in question references a `domain` item.
https://github.com/FOSSBilling/FOSSBilling/blob/88f282a544d31a6b708e11d36d6c2615ad0b599b/src/modules/Cart/Service.php#L543
This suggests to me that there is some kind of confusion to happen, and that it may be possible to use other sensitive variables in the as the form field name.

### How to reproduce

Order a product with a custom form field entry named `domain`.

### Expected behavior

Either stop users from creating fields with conflicting names, or add a prefix.

### FOSSBilling version

0.6.15

**Comment by isshiimwe** [comment]
just updated and I’m having this issue 
![image](https://github.com/FOSSBilling/FOSSBilling/assets/122705379/08d8d1b8-6dc7-490f-b73a-f98c12fefbb4)

**Comment by BelleNottelling** [comment]
> just updated and I’m having this issue

Please check the troubleshooting steps for how to handle errors after updating:
https://fossbilling.org/docs/troubleshooting#errors-after-updating

If these don't help, we can assist you via the [forum](https://forum.fossbilling.org/), [Discord](https://fossbilling.org/discord), or through a **new** issue here on GitHub, but as it's unrelated to the current issue, I'm collapsing your comment as being off-topic.
