### ISSUE TITLE
[Bug] Bootstrap theme comes unconfigured and displays a white page

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#217]
**Describe the bug**
When you activate the Bootstrap theme for the first time, configuration will be messed up for some reason and you won't see anything but a full white page when you visit the client area.

It is confusing for new users, it should come preconfigured with the default theme instead.

**To Reproduce**
1. Perform a fresh install
3. Activate the Bootstrap theme
4. Check the client area
5. You should see a full white page instead of actual content

**Expected behavior**
The theme should come preconfigured with the default theme and should display regular content.

**Additional context**
This problem used to exist in BoxBilling too.

**Comment by 4yx** [comment]
I couldn't reproduce this on my fresh local test installation (built from source). I chose "Set as default" to enable it as the default theme, reloaded the client area and it worked well, not sure if that's what you meant by "Activate the Bootstrap theme".

Of course since this will likely be superseded by the PR above, it won't matter much, but I thought I'd let you know.

**Comment by jaapmarcus** [comment]
Issue has been solved by downgrading to beta11 instead of beta12 for tabler we need to find what caused the issue

**Comment by 4yx** [comment]
> Issue has been solved by downgrading to beta11 instead of beta12 for tabler we need to find what caused the issue

Ah, thanks. I thought Tabler only fixed the admin theme issue for some reason.

**Comment by jaapmarcus** [comment]
We are going to drop  boxbilling (Current default) and bootstrap in favor for Huraga to simplify maintaining. 

https://github.com/FOSSBilling/FOSSBilling/pull/279

**Comment by evrifaessa** [comment]
It likely happens when the post-install script can't copy the example configuration file to the correct location due to permission issues.

-----

> Issue has been solved by downgrading to beta11 instead of beta12 for tabler we need to find what caused the issue

Unrelated. This is for the Bootstrap theme, Tabler is used for the default admin theme.

> Ah, thanks. I thought Tabler only fixed the admin theme issue for some reason.

That's correct.
