### ISSUE TITLE
Error after upgrade from 0.5.6 to 0.6.x

### ISSUE THREAD

**Issue by mwlandolsi** [FOSSBilling/FOSSBilling#2196]
Hello, I got this error after upgrade
An error has occurred.
Instance ID: aa4173f2-f31b-46b6-b909-3b3f8d7a3972 Error Code: #0 Component: Generic 

You've received a generic error message: Constant "BB_URL" is undefined. 
I checked the forum I did not find any answer for this. 
Could you help me please?

**Comment by BelleNottelling** [comment]
You need to update your theme:
https://github.com/getpinga/tide/releases

**Comment by mwlandolsi** [comment]
Thanks, Solved.

**Comment by mwlandolsi** [comment]
thanks

**Comment by BelleNottelling** [comment]
You're welcome
