### ISSUE TITLE
[Laravel] Database migration

### ISSUE THREAD

**Issue by HunterNyan** [FOSSBilling/FOSSBilling#22]
Progress of the Database migrations for the lara branch
This will need to include the code to move the data out of existing tables into the new schema
### Stage 1

- [x]  setting 
- [x] currency
- [x] pay_gateway
- [ ] subscription
- [x] tax
- [ ] Documentation

### Stage 2

- [x] product_category
- [ ] product_payment
- [ ] product
- [ ] Documentation

### Stage 4

- [ ] Users / Clients
- [ ] User Groups
- [ ] admin
- [ ] admin_group
- [ ] Documentation

### Stage 5

- [ ] promo
- [ ] client_order
- [ ] client_order_meta
- [ ] client_order_status
- [ ] client_balance
- [ ] transaction
- [ ] Documentation

### Stage 6

- [ ] cart
- [ ] cart_product

**Comment by andpavlenko** [comment]
This mean what database schema will be changed or migrate to modern ORM without change database schema?

1. If you change the database schema, that break most modules that you will not be able to rewrite.
2. Community has decided integrate Laravel?

**Comment by jaapmarcus** [comment]
I understand the concerns 

Staring an existing fork of a project is off course a an ideal starting point to "Decide" to make such decisions or not. 

Plans for now are to migrate existing modules how ever for "modules" out of control is a valid point

If I look at the taxes:
https://github.com/FOSSBilling/FOSSBilling/commit/6d9f03c2f1cbadcf4c0103558a8ea21212746507

Changes will be made so if a module depends on it will. break

How ever for them are 2 options:

- Stay at box billing 
- Migrate to FOSSBilling but it will mean some DIY is required. 

At some point we need to make pain full changes and we can do it better now then over 1 year.. When xx% allready switched.

**Comment by John-S4** [comment]
> At some point we need to make pain full changes and we can do it better now then over 1 year.. When xx% allready switched.

Absolutely agree with this. BB had an old codebase that was not maintained for long periods of time and often lacked clear direction when it was. 

There have to be breaking changes if the project is going to move forward and it is better to make them sooner than later.
