### ISSUE TITLE
[Feature Request] API Calls // for example Jellyfin Usermanagement

### ISSUE THREAD

**Issue by Nazgile94** [FOSSBilling/FOSSBilling#2219]
A Payed Subscription with API Call possibility would be nice, for example:

I create XXX Movies * lol * by myself and want to share that content with some friends / users, but they need to pay for it for example on jellyfin.

Jellyfin provides an api for activate, deactivate users and more,.

Would be nice, if FOSSBilling can manage that subscription - user paid = enable jellyfin account trough api call X Y Z not paid = disable trough api call X Y Z

**Comment by BelleNottelling** [comment]
I would be.. hesitant to provide official support for Jellyfin with FOSSBilling as I personally would be worried about taking that and attempting to sell access to their movie library.

However, you're asking for "API calls" specifically which to me implies you are willing to write a bit of code.
Product types in FOSSBilling are actually modular and anyone can build a custom one to fulfill a purpose that they don't have.

Any module that provides a product (or "service") should have it's name start with `Service`, indicating to FOSSBilling that it implements a new product type. At that point once it's installed it'll appear in the admin interface so the administrator can setup and start selling new products with it.

I'd suggest taking a look at the code for [Serviceapikey](https://github.com/FOSSBilling/FOSSBilling/tree/main/src/modules/Serviceapikey) as the logic in it is pretty simple and it's one of the few (if only?) default product type that's not still setup with a deprecated order logic system

**Comment by BelleNottelling** [comment]
Realistically, I don't see us implementing direct support for Jellyfin & there's already an option for adding custom integrations, so I'm going to close this.
