### ISSUE TITLE
Stripe Payment gateway not making subscription automatically for manual products

### ISSUE THREAD

**Issue by umargigani** [FOSSBilling/FOSSBilling#2236]
### Describe the bug

Stripe Payment gateway not making subscription automatically for manual products

### How to reproduce

Stripe Payment gateway not making subscription automatically for manual products

### Expected behavior

i setup products for recurring payment logically it should create subscription in stripe gateway and customer should be charge automatically but it is only make it one time pay and not recurring  

### FOSSBilling version

0.6.2

### FOSSBilling instance ID

3e9a4df7-14a5-4d47-8967-93a26599e8c9

### Device

Desktop

**Comment by BelleNottelling** [comment]
Subscriptions are not yet implemented in Stripe at this time.

https://fossbilling.org/docs/extensions#list-of-payment-adapters

You also do not need to submit an issue for it, one already exists and I'm slowly working on it between other items

**Comment by umargigani** [comment]
ok thank you i didnt see the above page waiting for this feature to be active thank you

**Comment by BelleNottelling** [comment]
You're welcome. Something to note is that it'll probably be some time until it's done.
I'm moving in just a few days and expect to generally have less availability + while working on Stripe I'm looking to redo a fair bit of the internal logic for payment gateways so they can provide more functionality and be easier to work with
