### ISSUE TITLE
[Feature Request]Transrate into Japanese

### ISSUE THREAD

**Issue by PYU224** [FOSSBilling/FOSSBilling#2252]
**Is your feature request related to a problem? Please describe.**
Hello.
I want to use this tool, but I think that Japanese user feel unuseful by English.
Would you transrate it into Japanese?

**Comment by jaapmarcus** [comment]
I have added Japanese to Crowdin ...

https://fossbilling.crowdin.com/u/projects/4/l/ja

Feel free to start translations how ever we are unable to do it our self...
