### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by naeemirza** [FOSSBilling/FOSSBilling#2259]
I am using the fossbilling for domain registeration through InternetBS.net. The domain registeration is being processed but the migration of domain using fossbilling interface is not getting through and getting an error message. I discussed it with InternetBS team and I am replying their response below:

We have searched and found this: https://github.com/FOSSBilling/FOSSBilling/blob/main/src/library/Registrar/Adapter/Internetbs.php
 
Inside that file one would need to replace this:
  public function isDomaincanBeTransferred(Registrar_Domain $domain): never
  {
      throw new Registrar_Exception(':type: does not support :action:', [':type:' => 'Internet.bs', ':action:' => __trans('checking domain transferability')]);
  }
with this:
 
public function isDomaincanBeTransferred(Registrar_Domain $domain)
{
$params = [
'domain' => $domain->getName(),
];
$result = $this->_process('/Domain/Check', $params);
 
//return true if status is UNAVAILABLE
//For not supported TLDs, the status will be 'FAILURE'
return $result['status'] == 'UNAVAILABLE';

**Comment by John-S4** [comment]
When did you discuss this with them, was it in the last few days or was it more than a week ago?

There was an update to that file by a member of the team from internet.bs merged about a week ago, maybe that fixes your issue or is it a new issue since then?

See here: https://github.com/FOSSBilling/FOSSBilling/pull/2241

**Comment by BelleNottelling** [comment]
Closed by #2241. It'll be part of the next FOSSBilling update, but since you already know the changes required I'm sure you've already applied them to your local copy & are using them
