### ISSUE TITLE
Synology docker installation with MariaDB on custom port

### ISSUE THREAD

**Issue by MuadDibIII** [FOSSBilling/FOSSBilling#2265]
Hello,

I'm considering install FOSSBilling on my Synology NAS, and I saw that I could use the stand alone version if I already have a MySQL database.

On my case I have a MariaDB that run on a custom port (not the default 3306). Is it possible to point FOSSBilling to this database or do I have to use the Docker Compose one?

Thanks in advance for your answer,

Best regards,
Marc

**Comment by BelleNottelling** [comment]
Hi there!

I completely missed this question, apologies.
When installing FOSSBilling, you can enter whatever database port you need so this should work without issue for you.
