### ISSUE TITLE
[Feature Request] Flutterwave payment gateway

### ISSUE THREAD

**Issue by hypoclone** [FOSSBilling/FOSSBilling#227]
**Is your feature request related to a problem? Please describe.**
Most times Africans are not always put into consideration when developing software solutions, most of the international payment gateway don't work for Africans businesses. 

**Describe the solution you'd like**
It would be nice if you guys could please add [Paystack](https://paystack.com/) and [flutterwave](https://flutterwave.com/) as payment options they are mainly used in Nigeria and other African countries. https://paystack.com/developers# , https://developer.flutterwave.com/
Thanks.

**Comment by evrifaessa** [comment]
The nice thing about open source software is that anyone can add something. We can't keep up with every provider in every region. We would be very happy if you could help.

**Comment by evrifaessa** [comment]
For Paystack, #46 already exists.

**Comment by hypoclone** [comment]
@evrifaessa Thanks so much for all you do, I wasn't aware paystack has an integration. Unfortunately, I am not a programmer

**Comment by evrifaessa** [comment]
Paystack doesn't have an integration. There already is a feature request about it but nothing has been implemented yet.

**Comment by hypoclone** [comment]
Oh! ok

**Comment by BelleNottelling** [comment]
Closing to make one larger issue to track the payment gateways that have been requested
