### ISSUE TITLE
[Feature Request]Edit to closed Feature Request #2208

### ISSUE THREAD

**Issue by AusWideWebsites** [FOSSBilling/FOSSBilling#2290]
**Is your feature request related to a problem? Please describe.**
FossBilling created a Knowledge Base Categories page in Feature Request #2208

**Describe the solution you'd like**
They should be listed alphabetically from A to Z and not the reverse Z to A as currently displayed in the single-page listing for the Knowledge base. Attached is an image displaying as currently Z to A
![FossBilling KB Categories](https://github.com/FOSSBilling/FOSSBilling/assets/165226152/b55e75f2-71f9-42c0-af12-978d5d3fe060)

**Describe alternatives you've considered**
None

**Additional context**
Additionally, all Knowledge Base Articles in all categories should be listed alphabetically from A to Z. Currently the only search/looking alternative is to manually scroll through all listed items (many categories have large listings) as they are listed randomly and not alphabetically.
![FossBilling KB Display Orders](https://github.com/FOSSBilling/FOSSBilling/assets/165226152/12a1e06d-3d15-429d-a401-011857f1b1b8)

**Comment by BelleNottelling** [comment]
These are actually being shown by the order they were added into the system. Not as if that's any more sensible for users, though.

Labeling this as a bug rather than a FR since the existing behavior is unexpected from a user's perspective.
