### ISSUE TITLE
[Task] Make Twig render raw HTML from CKEditor output

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#236]
Originally https://github.com/boxbilling/boxbilling/issues/965

### What is the task

WYSIWYG saves the output as HTML, so we need to make sure Twig is not trying to sanitize HTML output into plain text.
Additional Notes

**Comment by evrifaessa** [comment]
Another solution would be getting CKEditor (or another editor if we decide to switch) to output Markdown.

**Comment by jaapmarcus** [comment]
Doesn't matter can also contain xss crap we should ideal add an library that filters them

**Comment by BelleNottelling** [comment]
> Doesn't matter can also contain xss crap we should ideal add an library that filters them

Twig markdown filter already does sanitization:
https://github.com/FOSSBilling/FOSSBilling/blob/main/src/bb-library/Box/TwigExtensions.php#L295

**Comment by BelleNottelling** [comment]
I'm going to close this, I think we all have agreed that it;'s best to stick to MD output for everything (for security purposes) & soon we should have CKEditor 5 with markdown output
