### ISSUE TITLE
[Task] Release v0.1.0

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#237]
I'm planning to release v0.1.0 with the current codebase soon. But we still have some issues blocking any future release:

- [ ] https://github.com/FOSSBilling/FOSSBilling/issues/236

**Comment by John-S4** [comment]
Absolutely, it would be really good if we can push that release out in the next week. 

If anyone has time to address the issue referenced above, or any of the other issues and tasks that are listed in the roadmap for the 0.1.1 release then please do jump in and help, and let's get it done. 

See here: https://github.com/orgs/FOSSBilling/projects/2/views/8

**Comment by John-S4** [comment]
@evrifaessa I think it would be really good to get this release out if we can. 

What are the issues that you think still need to be closed before we can do that? Anything else we can push to the next point release.

**Comment by evrifaessa** [comment]
> @evrifaessa I think it would be really good to get this release out if we can. 
> 
> 
> 
> What are the issues that you think still need to be closed before we can do that? Anything else we can push to the next point release. 

#236 is definitely a must. It's now broken in the main branch and anything with WYSIWYG functionality will look broken.

Other than that, I think we can push everything else to the next point release.

**Comment by jaapmarcus** [comment]
- Stripe not working  https://github.com/FOSSBilling/FOSSBilling/issues/269
- Filemanager not working and links lead to 404 / error
<img width="854" alt="Screenshot 2022-09-19 at 18 16 07" src="https://user-images.githubusercontent.com/9754650/191064435-0d028f28-0b80-4555-b022-7635842c327c.png">


Those issue al don't work for a great user experience before releasing those issues should be fixed

**Comment by John-S4** [comment]
@jaapmarcus 

Agree totally about Stripe, we need to get that sorted out. 

The file manager though... I thought that had been removed to be honest, and in my personal opinion a file manager has absolutely no business being in a billing solution, that is a job for a server/hosting control panel. My thought would be that it shouldn't be there at all and there should be no links to it.

**Comment by John-S4** [comment]
That's what I thought, so any links to it need to be removed wherever they are.

**Comment by evrifaessa** [comment]
> That's what I thought, so any links to it need to be removed wherever they are.

@John-S4 found only one and created a PR: https://github.com/FOSSBilling/FOSSBilling/pull/270

**Comment by xeruf** [comment]
Hey, I was wondering, as that might be related:

> FOSSBilling is under active development but is currenly very much beta software

Now, I thought FOSSBilling is a fork/continuation of BoxBilling, which was already stable, right?
So should I prefer BoxBilling for now, or is FOSSBilling already _more_ stable than that?

**Comment by jaapmarcus** [comment]
The main branch of Boxbilling is way less stable the the release. And the Fossbilling main branch is allready bit more stable. But suggest not use it in production...

**Comment by BelleNottelling** [comment]
We also need to sort out any remaining issues caused by the new admin theme

**Comment by DataLores** [comment]
Have we tagged a consolidated list of remaining issues/blockers to cutting 0.0.1?

**Comment by evrifaessa** [comment]
> Have we tagged a consolidated list of remaining issues/blockers to cutting 0.0.1?

I think we need to get Huraga working without the visitors having to log in as a client.

**Comment by evrifaessa** [comment]
Done :))
