### ISSUE TITLE
[Bug] Mollie Payment Adapter IPN Parameter Prefix Removal (fix added)

### ISSUE THREAD

**Issue by Daisy-Debby** [FOSSBilling/FOSSBilling#2407]
### Describe the bug

The Mollie Payment Adapter in FOSSBilling is currently using outdated IPN parameter prefixes. The bb_ prefix has been removed from all IPN parameters, but the adapter hasn't been updated to reflect this change.

Current Behavior
The Mollie Payment Adapter is using the following outdated parameter names:

bb_invoice_id
bb_gateway_id

### How to reproduce

1. Examine the Mollie Payment Adapter code in the FOSSBilling codebase.
2. Look for instances of bb_invoice_id and bb_gateway_id.

### Expected behavior

The adapter should use the updated parameter names without the bb_ prefix:

invoice_id
gateway_id

### FOSSBilling version

0.6.22

### FOSSBilling instance ID

9384f7b9-ea02-4791-9a03-4fc94e8de717

### Module version

Mollie 0.0.3

### Device

Desktop

### Additional context

Code Changes Required
In the _generateForm method of the Mollie Payment Adapter:

`// Change this line:
$output = $service->create(array('txn_id' => $payment->id, 'bb_invoice_id' => $invoice->id, 'bb_gateway_id' => $payGateway->id));

// To this:
$output = $service->create(array('txn_id' => $payment->id, 'invoice_id' => $invoice->id, 'gateway_id' => $payGateway->id));`

**Comment by jaapmarcus** [comment]
https://github.com/FOSSBilling/Mollie

Next time please create PR :)
