### ISSUE TITLE
[Feature Request] Display order for Knowledge base Articles

### ISSUE THREAD

**Issue by AusWideWebsites** [FOSSBilling/FOSSBilling#2430]
**Is your feature request related to a problem? Please describe.**
The new Knowledge base category display is listed as Z down to A and English countries utilise A down to Z display option.

**Describe the solution you'd like**
Set the category page with all Categories listed. They should be listed alphabetically from A to Z and not the reverse Z to A as currently displayed in the single-page listing for the Knowledge base.

**Describe alternatives you've considered**
Set selection option for both displays in set up default settings and Admin can select option required.

**Additional context**
The image displays the current default as Z down to A. I advised in original Feature Request
[BelleNottelling] closed this as [completed] in #2212 on Mar 30 - advised for reference.

![Knowledgebase Screenshot 2024-09-09 133401](https://github.com/user-attachments/assets/07cf4828-2ecf-4fe0-998f-b854c7e68c1b)

**Comment by AusWideWebsites** [comment]
Should I have placed this in a different area? Only ask because it has been 3 weeks without any response.

**Comment by BelleNottelling** [comment]
It is the right place, I am just completely swamped with my personal life at the moment.
Remaining optimistic that I'll have more time in around a month

**Comment by AusWideWebsites** [comment]
All good Belle. Is there anything I/we can help with.
No good with programming etc but simple tasks etc happy to take the load if that helps.

**Comment by BelleNottelling** [comment]
Duplicate of #2518
