### ISSUE TITLE
[Feature Request] Modulo para Integração Cyberpanel

### ISSUE THREAD

**Issue by mxsmarcos** [FOSSBilling/FOSSBilling#2437]
Eu procurei em vários lugar e não achei um módulo de integração para cyberpanel. Seria um par perfeito principalmente para nos aqui no Brasil que sofre com a infração e alta do dólar uma vez que a maioria dos serviços são pagos em dólares 
[CyberPanel](https://cyberpanel.net/) 

[Comunidade Github ](https://github.com/usmannasir/cyberpanel)
![Captura de tela 2024-09-17 114109](https://github.com/user-attachments/assets/d475c84d-d365-4fcb-8f35-18a26f88af56)

**Comment by roger-net** [comment]
https://github.com/NerdbyteIO/FOSSBilling-CyberPanel
