### ISSUE TITLE
Cant Install FOSSBilling (Data Folder)

### ISSUE THREAD

**Issue by damianschoenberger** [FOSSBilling/FOSSBilling#2463]
![image](https://github.com/user-attachments/assets/2be9aaac-7650-4af8-a7aa-ccde25f76c37)

Everytime i get this Error, if i Start the Installer.

P.S. I use KeyHelp

**Comment by BelleNottelling** [comment]
Did you check the troubleshooting link & try following it?
https://fossbilling.org/docs/troubleshooting#permission-issues

**Comment by BelleNottelling** [comment]
Following the linked troubleshooting steps should resolve this for you.
Closing as resolved.
