### ISSUE TITLE
[Bug] Trying to use ddev rewrite dosnt work even after mode rewrite is enable inside ddev container.

### ISSUE THREAD

**Issue by Tdnshah** [FOSSBilling/FOSSBilling#2467]
### Describe the bug

I am trying to setup my local  development environment for Fossbilling library using ddev, the installation works fine but when i try to login as admin i observed that one home page client side keeps loading, it seems the rewrite is not working. I have tried alll the steps mentioned in troubleshooting documentation for apache still no success.

### How to reproduce

1. Step 1: git clone fossbilling repo in a directory.
2. Step 2:  Install ddev in your system and run ddev config.
3. Step 3: Select php project in question prompted by ddev config command.
4. Step 4 :  Visit url provided by ddev and complete the installation of fossiblling.
5. Step 5: Now try to open admin login page and it will keep opening the client home page.

### Expected behavior

I should be able to visit any page include admin login, client login pages

### FOSSBilling version

0.6.22

### Information

- ddev docker container 
- Apache
- mysql 
- php

**Comment by BelleNottelling** [comment]
If you're trying to use it with NGINX, there's a specific config that must be used.
https://fossbilling.org/docs/getting-started/installation#webserver-configurations

**Comment by Tdnshah** [comment]
No I was using ddev with apache2, though would try with ngnix and see if it works, thanks for directing

**Comment by BelleNottelling** [comment]
FOSSBilling now has a ddev config and will work easily out of the box.

1. Clone the repo & CD into it
2. Run `ddev start`
3. After started, run `ddev npm i` and then `ddev npm run build` to build the needed front-end assets.

**Comment by Tdnshah** [comment]
Hey thanks this would help setting up local dev environments, thanks for adding the config @BelleNottelling

**Comment by BelleNottelling** [comment]
Thanks for submitting this issue!

Having now played around with ddev a bit, I can confidently say it's quite useful and I'll be using it for more of my projects to speed up development so I appreciate being introduced to it.
