### ISSUE TITLE
Replace Google Fonts

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#249]
_(a part of #176)_

We rely on Google Fonts in [12 different files](https://github.com/FOSSBilling/FOSSBilling/search?q=fonts.googleapis.com). We should replace them.

### 2. Downtimes potentionally breaking the software
Our software should be able to continue functioning regularly if Google Fonts has a downtime. Keeping these fonts locally or replacing them with [web-safe fonts](https://www.w3schools.com/cssref/css_websafe_fonts.asp) should minimize the impact on our users.
### 3. GDPR
Even if the user isn't practically visiting a website owned by Google, the resource is hosted on Google's servers and they do log identifying information about the user. A regional court in Munich, Germany recently had a judgement about Google Fonts. To read more on this, [here is a link](https://www.lexology.com/library/detail.aspx?g=8546d90b-61f5-4c96-8bd0-86d1676863c2).

## How to replace
For some (many) instances, we can replace the fonts with [web-safe fonts](https://www.w3schools.com/cssref/css_websafe_fonts.asp). For other specific fonts, there are useful tools like [this](https://google-webfonts-helper.herokuapp.com/fonts) to grab the source and self-host.

**Comment by John-S4** [comment]
Down to 3 files, definitely a step forward :)
