### ISSUE TITLE
[Feature Request] Better docker-compose documentation

### ISSUE THREAD

**Issue by meesvw** [FOSSBilling/FOSSBilling#251]
**Is your feature request related to a problem? Please describe.**
I am having problems installing and running FOSSBilling with Docker. I am running Traefik as a reverse-proxy and I would like FOSSBilling to route through Traefik. This is why I cannot use the makefile, since it will create the container without respecting the Traefik as reverse-proxy.

**Describe the solution you'd like**
I would like the docs for the Docker deployment to describe a way to run it without using the makefile. Or I would like a better documentation on how the application is working in order to implement it with a reverse-proxy.

**Describe alternatives you've considered**
I've considered recreating the makefile with the Traefik integration, but it doesn't seem to work.

**Comment by jaapmarcus** [comment]
https://github.com/FOSSBilling/FOSSBilling#installing-with-docker

Some information has been added. 

But it should be expanded in the future...

**Comment by evrifaessa** [comment]
Will be resolved with #30.
