### ISSUE TITLE
[Feature Request] Lexoffice Integration

### ISSUE THREAD

**Issue by plotnicsystems** [FOSSBilling/FOSSBilling#2512]
Can you add a Fully Lexoffice integration for creating invoices directly on lexoffice and the customer can download the invoice via api from Lexoffice or the FossBilling Pannel via Lexoffice Sync (import the Lexoffice invoice to Fossbilling via pdf).

best regards

**Comment by plotnicsystems** [comment]
Well, I do think that there would be added value for the German market, as everyone is quickly using Lexoffice. In addition, the currently integrated invoice function is not GDPR-compliant and cannot be used in my company, for example.

I can offer to develop an extension and then offer it in my shop for a fee.

**Comment by jaapmarcus** [comment]
Go ahead we have limited resources and personally I we want to spend time to more GDPR approved it won't be moving to a paid invoicing system but keeping it internally.

**Comment by BelleNottelling** [comment]
I don't really even see how it's supposed to function.
Core functionality like renewals, payments, notifications, ect all depend on invoices being generated within FOSSBilling. Trying to separate invoice functionality from it would complicate all of that quite a lot
