### ISSUE TITLE
Error with UddoktaPay payment extension: Incorrect Integer Value for invoice_id

### ISSUE THREAD

**Issue by rownok860** [FOSSBilling/FOSSBilling#2539]
I'm encountering an issue while using UddoktaPay as the payment gateway in FossBilling. Whenever a transaction is processed, I receive the following error:
![Screenshot](https://i.ibb.co.com/k4CnQZX/Business-Suite-creation-1118996456410075.png)
```
{

"result": null,

"error": {

"message": "SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'p13pW605mfefPNUIYW2f for column 'invoice_id' at row 1"

}
```

**Comment by jaapmarcus** [comment]
You should contact the developer of the module...

**Comment by BelleNottelling** [comment]
Issue with their payment gateway itself, not with FOSSBilling.
It looks like there's now an updated version of it:
https://github.com/UddoktaPay/FOSSBilling/releases/tag/1.0.1
