### ISSUE TITLE
[Bug] 'Add Funds' allows client deposit without a corresponding transaction

### ISSUE THREAD

**Issue by DataLores** [FOSSBilling/FOSSBilling#262]
**Describe the bug**
Creating invoices as a client via add-funds allows invoices to be marked as paid when there is no corresponding successful transaction.

**To Reproduce**
1. For an authenticated user, navigate to payment history (/client/balance)
2. Add a positive integer amount of funds (bottom left).
3. Wait until the bb-cron is next invoked. You will observe in the event history as admin that the invoice left open was "Marked as Paid"
4. Return to invoice portal as client, invoice is marked as paid.

**Expected behavior**
Invoices should not be marked as paid until there is a valid corresponding transaction recorded from the payment gateway.

**Desktop (please complete the following information):**
Windows 10/11 with Latest Chrome
PHP version: 7.4.30
BoxBilling: 4.22.1.5 Release
Stripe Version: 7.121.0

**Comment by evrifaessa** [comment]
Wow, this is serious. Thanks for the report and the fix.

**Comment by DataLores** [comment]
Issue merged to main branch, resolving.
