### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by roger-net** [FOSSBilling/FOSSBilling#266]
When starting the installation on the first screen the requirements are all ok, on the second screen where the database is configured and after everything is configured correctly when clicking on the "next" button nothing happens and the installation stops on this screen.

**Comment by jaapmarcus** [comment]
Please check the log files from php

**Comment by roger-net** [comment]
> Please check the log files from php

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined function error_log() in /home/users/*****/www/cart/install/install.php:273
Stack trace:
#0 /home/users/*****/www/cart/install/install.php(284): Box_Installer->getPdo()
#1 /home/users/*****/www/cart/install/install.php(99): Box_Installer->canConnectToDatabase()
#2 /home/users/*****/www/cart/install/install.php(490): Box_Installer->run()
#3 {main}
thrown in /home/users/novacast/www/cart/install/install.php on line 273', referer: https://*****/install/install.php

500 | POST /install/install.php?a=check-db HTTP/2.0

**Comment by jaapmarcus** [comment]
https://www.php.net/manual/en/function.error-log.php

Is a default php function you should contact your provider about it or enable that function your self
