### ISSUE TITLE
Stripe Payment dont redirect to payment page

### ISSUE THREAD

**Issue by trickbaze** [FOSSBilling/FOSSBilling#269]
**Describe the bug**
I got the currency EUR, but when i try to pay the site does not take me to the stripe payment page

**Desktop (please complete the following information):**
 - OS: Windows 11 With XAMPP
 - Browser Chrome
 - Version 22

**Comment by DataLores** [comment]
Can you confirm what client theme is configured (bootstrap, boxbilling, huraga)? If you switch to huraga, are you able to reproduce the problem?

**Comment by jaapmarcus** [comment]
I used "Bootstrap" and "Boxbilling"

**Comment by DataLores** [comment]
Closes #279
