### ISSUE TITLE
[Bug] Gulp can't build the admin theme

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#275]
**Describe the bug**
Gulp produces a faulty bundle JS and the admin area looks broken.

**To Reproduce**
1. Clone the main branch
2. Run gulp and complete the setup
3. Check the admin area

**Expected behavior**
The page should look fine and Gulp shouldn't display this error

**Screenshots**
![image](https://user-images.githubusercontent.com/35808275/191818317-045e55ee-47eb-4899-a7fd-0a6fc62cb7d8.png)

**Error messages**
Gulp:
```
[gulp-chug] (src/bb-themes/admin_default/gulpfile.babel.js) Error in plugin "sass"
Message:
    ../../../node_modules/@tabler/core/dist/css/boxbilling-bundle.min.css
Error: @use rules must be written before any other rules.
      ╷
16651 │ @use "bootstrap";
      │ ^^^^^^^^^^^^^^^^
      ╵
  ../../../node_modules/@tabler/core/dist/css/boxbilling-bundle.min.css 16651:1  root stylesheet
```
Browser console:
```
Uncaught (in promise) Error: Element not found
    value http://localhost/bb-themes/admin_default/build/js/boxbilling-bundle.min.js?v=0.0.1:1
    value http://localhost/bb-themes/admin_default/build/js/boxbilling-bundle.min.js?v=0.0.1:1
    setPlotDataData http://localhost/bb-admin/index:812
    <anonymous> http://localhost/bb-admin/index:751
    i http://localhost/bb-themes/admin_default/build/js/boxbilling-bundle.min.js?v=0.0.1:1
    fireWith http://localhost/bb-themes/admin_default/build/js/boxbilling-bundle.min.js?v=0.0.1:1
    ready http://localhost/bb-themes/admin_default/build/js/boxbilling-bundle.min.js?v=0.0.1:1
    s http://localhost/bb-themes/admin_default/build/js/boxbilling-bundle.min.js?v=0.0.1:1
```

**Desktop (please complete the following information):**
 - OS: Fedora Linux (37)
 - Browser: Mozilla Firefox (104.0.2)

**Additional context**
If this is reproducible for everyone, I think this is an urgent issue.

**Comment by evrifaessa** [comment]
Seems like it happened with the latest automated preview build too.
![image](https://user-images.githubusercontent.com/35808275/191819643-6efb49ce-513d-4a88-8573-6b699fd04364.png)
https://github.com/FOSSBilling/FOSSBilling/actions/runs/3104617057/jobs/5029296166#step:10:37

**Comment by evrifaessa** [comment]
I was able to spot what caused this.

[The latest Tabler update](https://github.com/FOSSBilling/FOSSBilling/pull/271) causes this. Let me see what particular change might be the cause.

**Comment by evrifaessa** [comment]
As a temporary fix, I'll revert Tabler to the preview release until we get ready to use the latest one.

**Comment by evrifaessa** [comment]
Reverted Tabler with #274.

**Comment by BelleNottelling** [comment]
Looks like we are already on the latest version of tabler, so this must have been fixed. Closing
https://github.com/FOSSBilling/FOSSBilling/blob/main/package.json#L15
