### ISSUE TITLE
[Feature Request] A new WYSIWYG editor

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#276]
Implement a modern WYSIWYG editor with markdown output.
We could go with raw HTML but we'd need to make Twig render it right away instead of sanitizing it into raw text.

One possible solution would be [CKEditor 5](https://ckeditor.com/). It has [markdown output](https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html) support.

**Comment by John-S4** [comment]
ProseMirror is also excellent.

**Comment by BelleNottelling** [comment]
CKEditor 5 seems like a good option. It's well established and still under active development
