### ISSUE TITLE
[Feature Request] Pterodactyl Module

### ISSUE THREAD

**Issue by Coo-ops** [FOSSBilling/FOSSBilling#28]
https://github.com/boxbilling/boxbilling/issues/1309

**Comment by karkkijokeri** [comment]
We need this! I have also been looking for a billing system with pterodactyl support.

**Comment by cosmii02** [comment]
Really need this integration

**Comment by givinghawk** [comment]
I also really need this

**Comment by BelleNottelling** [comment]
We currently have no plans to introduce official support for Pterodactyl.
If the community wants to build and maintain one that's great, however for now no official support will be given for it.

**Comment by cosmii02** [comment]
rip the 1 module that would make sense ._.

**Comment by jcsnider** [comment]
I recently posted this in the Pterodactyl discord, figured I'd throw it here as well...

As a small incentive for anyone who is already considering to tackle this, I'd personally be willing to contribute $200/USD towards the development of a free & open source Pterodactyl module for FOSSBilling.  This would be dependent on the completion of the module including validation of functionality but not dependent on any sort of long term upkeep/maintenance/support. Feel free to tag me if you'd like to connect and work out details.
