### ISSUE TITLE
[Bug] Staff modal tabs do not render (Permissions, Password, API)

### ISSUE THREAD

**Issue by DataLores** [FOSSBilling/FOSSBilling#282]
**Describe the bug**
When logged in as an administrator, if you click into manage a specific staff member:

1. The permissions tab does not render {{ member_name }} to a value.
2. The password tab does not render content.
3. The API tab does not render content.

**To Reproduce**
1. Go to staff management page.
2. Click on any administrator.
3. Click each of the tabs mentioned above to see the behavior.

**Expected behavior**
Variables and tabs render with expected features.

**Desktop (please complete the following information):**
 - OS: Win10/Chrome latest
 - PHP 8.0.23
 - FOSSBilling main branch

**Additional context**

**Comment by evrifaessa** [comment]
I'll try to reproduce this evening.

**Comment by evrifaessa** [comment]
I was able to reproduce.

**Comment by evrifaessa** [comment]
It only happens when you attempt to manage your own user account. The tabs render fine for other staff members' accounts.

**Comment by evrifaessa** [comment]
Will be fixed with #319.
