### ISSUE TITLE
Separate the Docker script into smaller scripts

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#285]
The installer (/bin/install.sh) will now build, configure and get the Docker containers up and running. We should separate the building process into another script.

## Why?
Some might not want to run FOSSBilling on Docker containers, but may still benefit from the part of the script that sets up the dependencies and builds the software.

**Comment by weismannweb** [comment]
Interesting +1

**Comment by BelleNottelling** [comment]
Is this issue still valid?

**Comment by jaapmarcus** [comment]
No. Should be closed and remove any docker related items...
