### ISSUE TITLE
[Feature Request] Configuration generator for web servers

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#286]
We could create a basic web app that generates minimal configuration files for different web servers. I've seen many people being confused while setting up FOSSBilling on their nginx servers, so this might help them a lot.

I also made a mockup:
![mockup](https://user-images.githubusercontent.com/35808275/192459219-6df78aa2-49d7-41a5-af4f-eff3a2767c5a.png)

**Comment by jaapmarcus** [comment]
Current example config should be fine:

https://github.com/FOSSBilling/FOSSBilling/blob/0a1523b06fd108d154260a729e6d36211f53f5cd/data/nginx.conf#L23

How ever this line of code should be changed why the user

**Comment by John-S4** [comment]
It's a nice idea. 

Are you thinking about just nginx or adding other servers as well?

**Comment by evrifaessa** [comment]
Likely others too

**Comment by John-S4** [comment]
Since this is now up at https://config.fossbilling.org/ - can this issue be closed? @evrifaessa

**Comment by evrifaessa** [comment]
> Since this is now up at https://config.fossbilling.org/ - can this issue be closed? @evrifaessa 

yes, of course. thanks for the reminder :)
