### ISSUE TITLE
[Feature Request] SolusVM extension update

### ISSUE THREAD

**Issue by 0x6b-dev** [FOSSBilling/FOSSBilling#29]
https://github.com/boxbilling/boxbilling/issues/1293

**Comment by notbasetwo** [comment]
Solved in #20 but awaiting testing.

**Comment by BelleNottelling** [comment]
I'd like to close this out if at all possible.
We've merged a fix that should fix it, but we don't have anyone to test it. I'd rather not keep this open for a year for no real reason
