### ISSUE TITLE
You have to sign in to use Huraga

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#298]
Huraga forces you to login before letting you see any content in the website.

New visitors shouldn't have to sign up to see what's sold.

**Comment by weismannweb** [comment]
i wasnt sure if this was the same issue so i posted it: https://github.com/FOSSBilling/FOSSBilling/issues/306

**Comment by evrifaessa** [comment]
> i wasnt sure if this was the same issue so i posted it: https://github.com/FOSSBilling/FOSSBilling/issues/306

it's unrelated.

**Comment by weismannweb** [comment]
thanks

**Comment by BelleNottelling** [comment]
Resolved after PR was merged
