### ISSUE TITLE
[Feature Request]  Feedback on using a prebuilt open source tailwind theme

### ISSUE THREAD

**Issue by weismannweb** [FOSSBilling/FOSSBilling#299]
**Is your feature request related to a problem? Please describe.**
I am looking for community feedback....
I would vote to to use modern and best practices pre-built theme using tailwind which means PWA to me.

**Describe the solution you'd like**
Use this prebuilt MIT theme:
https://github.com/justboil/admin-one-vue-tailwind 

**Describe alternatives you've considered**
also https://github.com/themesberg/tailwind-dashboard-windster

also coding tailwind from scratch but we then would not benefit from either of these themes architecture while reducing work

**Additional context**
Shouldn't a modern laravel app be PWA or SPA.

**Comment by evrifaessa** [comment]
Not actionable.
