### ISSUE TITLE
Standalone Docker image

### ISSUE THREAD

**Issue by 0x6b-dev** [FOSSBilling/FOSSBilling#30]

**Comment by John-S4** [comment]
Surely we have a docker version - so this can just be closed?

**Comment by evrifaessa** [comment]
Yeah, but still, let's keep this open as publishing a Docker image for FOSSBilling was being talked.

**Comment by evrifaessa** [comment]
We should start working on this.

**Comment by BelleNottelling** [comment]
We now have a standalone docker image officially published, closing
