### ISSUE TITLE
[Feature Request]  create microservices based framework and loosely coupled and high cohesion for every plugin or module

### ISSUE THREAD

**Issue by weismannweb** [FOSSBilling/FOSSBilling#300]
**Is your feature request related to a problem? Please describe.**

Looking for community feedback...

Develop all modules in a micro architecture way:

References:

https://www.youtube.com/watch?v=mG9SvxnkKEY

(Im not sure if this is the right thing above but it seems to be.  I kind of have book knowledge of lots of this stuff and not street knowledge :)   )

So let me dig deeper into what I mean.  If we create integrations with cpanel, plesk, cyberpanel, whatever panel.  Or if we create ANY feature we do it loosely coupled with high cohesion and make each thing we create a stand along library able to be used by laravel community or since laravel is already loosely coupled anyone can use the lib.

https://medium.com/clarityhub/low-coupling-high-cohesion-3610e35ac4a6

Maybe micro arch is the wrong statement but above is what I mean.  If anyone can provide a name for it it would be helpful.

We would then shave all of them in composer or npm or github.

**Describe the solution you'd like**
Use https://laravel.com/docs/9.x/octane

**Describe alternatives you've considered**
Yes create a monolithic app. 

**Additional context**
If ocatain and micoservices is different then loosely coupled/high cohesion let me know and ill split this.  That being said I think anyone would get my gist and I would be interested in libraries for laravel (or  framework documentation) that deals with this?

**Comment by jaapmarcus** [comment]
It doesn't make sense to publish an "Create" user account module to the public for "outside" use but it makes sense to have a public php api based system that can communicate to Cpanel, Directadmin, Plesk, Hestia or Whatever. 

But there is not need to run Fossbilling on multiple smaller instances and we need to add communication layers inbetween. Keep it *** simple

**Comment by weismannweb** [comment]
ok so then a standardized api in front of a Cpanel, Directadmin, Plesk, Hestia or Whatever. pluginized library ...am i getting that right?

**Comment by jaapmarcus** [comment]
There is no standaard API for Cpanel, Plek, Directadmin and creating really doesn't make sense because the can always change.

**Comment by weismannweb** [comment]
i think thats the point, how do you think the api i mentioned does it, but yeah you dont want it hidden behind a service thats a valid point, but saying you cant do a standard api is imho not 100% true, all it is is a api wrapper with a singular api schema around multiple code modules for each provisioning software.

**Comment by weismannweb** [comment]
sorry i mentioned the standarized api for shopping carts elsewhere, but this is what i mean, an example of what i mean:
https://api2cart.com/ 

See this: https://docs.api2cart.com/post/interactive-docs?version=v1.1

**Comment by BelleNottelling** [comment]
I'm not aware of any kind if standard API for control panels, and expecting us to create and maintain one is effectively another project entirely and restructuring FOSSBilling to work with it. 

As it stands, only 4 of the server managers are known to work (CPW, HestiaCP, Plesk, and cPanel).
Of these, the only one I know that's being actively maintained is HestiaCP, possibly Plesk. Most contributors aren't even using FOSSBilling for anything (yet), let alone using it with one of the existing control panels and maintaining the server manager for it.

Such a project would be quite cool, if there were other OSS projects that would benefit from it, but I really don't think there are more than a very small handful. 

Potentially paid software like WHM would have a use for them, but again, they would need to update their software to work with it, and potentially cause issues with existing server managers that are written for them.

I'm going to close this as not planned, if someone on the team disagrees with me, feel free to speak up / re-open this issue.
