### ISSUE TITLE
[Feature Request] GraphQL API first architecture in lara branch

### ISSUE THREAD

**Issue by weismannweb** [FOSSBilling/FOSSBilling#302]
**Is your feature request related to a problem? Please describe.**

Looking for community feedback...

problem is some day you will want to build an api, why not think about it upfront and build it automatically by doing things a certain way in the beginning by doing an api backend using laravel/graphql, then a vue.js/tailwind frontend.
Refer to this for the reasons why this is good:

https://codeburst.io/up-and-running-with-graphql-laravel-and-vue-js-698000248448
```

Why such an application ?
You may be wondering why did we opt for an headless app where we would have on one side the front-end rendered using Vue.js, and on the other side our server side dealt with Laravel — and it may sounds like an overhead.

Therefore, I want to give you a few arguments:

It offers us a non-negligeable flexibility over time as we do have the ability to easily flip around server-side language for instance.
We set up an additional layer of security
We can run distinct tests on the server-side and client-side by implementing different testing tools and automations.
Last but not least, we are reliant on a full code base: we have 2 well-defined app. Therefore, we could easily bring forth to a Mobile application using Native Script or whatever tool we want.

```
**Describe the solution you'd like**

**Describe alternatives you've considered**
Alternatives is building a separate api later. Or having more dependencies to have an api layer added later.

**Additional context**
https://www.youtube.com/watch?v=4z3EMCc4bP4
https://www.udemy.com/course/master-laravel-with-graphql-vuejs-and-tailwind
example app: https://github.com/aepnat/blogql
Lib: https://github.com/rebing/graphql-laravel

**Comment by weismannweb** [comment]
if we do do api: https://vyuldashev.github.io/laravel-openapi/ supporting swagger/openapi would be nice for auto documentation

**Comment by evrifaessa** [comment]
Not actionable. Please create issues with smaller tasks if you still want it implemented to the `main` branch.
