### ISSUE TITLE
[Feature Request] use omni pay in lara branch

### ISSUE THREAD

**Issue by weismannweb** [FOSSBilling/FOSSBilling#303]
**Is your feature request related to a problem? Please describe.**
yes its going to be a pain to code for tons of pay libs

**Describe the solution you'd like**
https://github.com/ignited/laravel-omnipay

**Describe alternatives you've considered**
none

**Comment by BelleNottelling** [comment]
This is absolutely a path we should consider to help streamline and simplify supporting multiple payment processors

**Comment by mylselgan** [comment]
Is Razorpay available or still under development?

**Comment by jaapmarcus** [comment]
Razorpay is not available or even in development.

**Comment by BelleNottelling** [comment]
Closing to make one larger issue to track the payment gateways that have been requested
