### ISSUE TITLE
[Bug] http google fonts causing console error - need to fix app wide all use of http

### ISSUE THREAD

**Issue by weismannweb** [FOSSBilling/FOSSBilling#307]
**Describe the bug**
Mixed Content: The page at 'https://billing.weismannweb.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=PT+Sans:regular,italic,bold'. This request has been blocked; the content must be served over HTTPS.

**To Reproduce**
click order service and get 404

**Expected behavior**
should not have error in console and should load the font

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://github.com/FOSSBilling/FOSSBilling/search?q=fonts.googleapis.com%2F)

need to fix http assets app wide

**Comment by jaapmarcus** [comment]
@BelleNottelling opened: https://github.com/FOSSBilling/FOSSBilling/pull/296

But no idea why she closed it.

**Comment by jaapmarcus** [comment]
src/bb-themes/huraga/html/layout_default.html.twig

She did...  Maybe today a new PR will come

**Comment by evrifaessa** [comment]
I think we can ditch Google Fonts entirely. We could bundle the fonts with the FOSSBilling source and have them served from the local server.
