### ISSUE TITLE
Separate Huraga's dependencies into their own files

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#314]
Huraga has Font Awesome and others hardcoded into theme files. The problem is there are different CSS files for each 4 color variant and they all have the dependencies hardcoded into them.

We should split dependencies into their own files and get the color variants to import them, ideally migrate to newer alternatives along the way.

**Comment by John-S4** [comment]
Are those 13000 line CSS files identical apart from colours? That's a bit nuts. 

I'm happy to take a look at this in the next couple of days unless you specifically want to. I do like a bit of CSS :)

**Comment by evrifaessa** [comment]
@John-S4

I was planning on taking a quick look this evening. I’ll separate some obvious ones like Font Awesome. I’ll tell you when I’m done.

**Comment by evrifaessa** [comment]
Absolutely. It’s now a pain to update every file with each small change.

**Comment by John-S4** [comment]
Closing this, and opened a new issue for the CSS cleanup I am doing.
