### ISSUE TITLE
[Bug] Staff member details won't report the correct API key

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#320]
**Describe the bug**
When you try to view a staff member's details and you check the API key tab, it will report your (or whoever is logged in at the moment) own API key instead of the selected staff member's.

**To Reproduce**
1. Go to Configuration -> Settings -> Staff
2. Click on the name of a staff member other than you
3. Click the API key tab, generate a key if there isn't any
4. Now go back click on the name of your own account
5. Click the API key tab and notice it's the same. This key is yours and not that other staff member's

**Expected behavior**
It should report the key of whichever staff account you've selected. I don't even know why if any administrator should be able to access the other administrator's API key, but currently there is such functionality but it's broken.

**Screenshots**
![image](https://user-images.githubusercontent.com/35808275/193651422-c5a2499b-8437-4460-ab1c-0c6e37282893.png)
![image](https://user-images.githubusercontent.com/35808275/193651500-dc342603-b675-46c4-8839-740edb1536f3.png)

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - Browser Mozilla Firefox
 - Version 105.0.1

**Comment by BelleNottelling** [comment]
IIRC, there's also some funky stuff going on in the database around this bug. Can't check it atm though
