### ISSUE TITLE
[Feature Request] In installation wizard, add option to disable automatic sending of "FOSSBilling is ready" email

### ISSUE THREAD

**Issue by nihilsen** [FOSSBilling/FOSSBilling#325]
When you finish the installation steps, an email is sent to the admin email address:

> *FOSSBilling is ready at https://your-fossbilling.url*
You have successfully setup FOSSBilling...

This is not always desirable.

There should be a checkbox in the install wizard that enables/disables the sending of this email.

**Comment by John-S4** [comment]
> This is not always desirable.

What is your use case where this is not desirable?

**Comment by nihilsen** [comment]
For installing something like a development/staging instance, it may not always be ideal to expose its URI in plaintext via email.

**Comment by admdly** [comment]
Is sending an email desirable at all after installation? 

I haven't come across software doing this more generally, and I don't see how sending an email with the login details provides any benefit.

**Comment by evrifaessa** [comment]
I've only seen Softaculous doing this. And I don't really think we should be sending emails after the installation.

**Comment by jaapmarcus** [comment]
> I've only seen Softaculous doing this. And I don't really think we should be sending emails after the installation.

Wordpress does the same for example. But maybe arguable that their users have 0 knowledge..
