### ISSUE TITLE
Bootstrap templates cant handle payments

### ISSUE THREAD

**Issue by waylenwasywas** [FOSSBilling/FOSSBilling#330]
An exception has been thrown during the rendering of a template ("Payment method not enabled").
Bootstrap theme used. Issue doesn't persist if using huraga.
I have stripe and paypal enabled, neither of them show up when going to pay.

When going to pay with stripe , stripe doesn't show up at all.
Paypal returns "Things don't appear to be working at the moment. Please try again later." 

When going to pay for a order no payment methods show up, only showing up when you go to the page to pay an invoice
![image](https://user-images.githubusercontent.com/35209231/184940573-65354556-dabf-458e-a3fe-e9779c87d8cc.png)
![image](https://user-images.githubusercontent.com/35209231/184940586-4bde177d-5919-463a-851e-c48762209e3b.png)
![image](https://user-images.githubusercontent.com/35209231/184940605-c469adbd-21e0-44e0-9617-2fcce83935bd.png)

**Comment by BelleNottelling** [comment]
Hi, @waylenwasywas 
I've transferred this issue to our main repository as it appears to be for the software and not the website.

Thanks!

**Comment by John-S4** [comment]
Yep, it's a known issue. 

One of many issues with that theme that are not likely to be fixed to be honest. That is why we have dropped both the bootstrap and boxbilling themes from the current preview builds (and upcoming releases) and are concentrating on Huraga. 

There will be a new theme with the 1.0 release but we are a fair way from there, and in the meantime it's recommended to use Huraga.

**Comment by BelleNottelling** [comment]
Closing since we did remove the theme and therefore will no longer be supporting it
