### ISSUE TITLE
[Bug] images are non existant (in system settings

### ISSUE THREAD

**Issue by givinghawk** [FOSSBilling/FOSSBilling#337]
**Describe the bug**
404 on icons in bb-admin/system

**To Reproduce**
1. look at bb-admin/system

**Expected behavior**
the actual image and not alt

**Screenshots**
![image](https://user-images.githubusercontent.com/72263189/195165430-36e964c3-ff2d-4add-8425-c01cecbf6acd.png)

**Desktop (please complete the following information):**
 - OS: win 10 pro
 - Browser chrome

**Additional context**
none

**Comment by givinghawk** [comment]
also in /bb-admin/extention 
![image](https://user-images.githubusercontent.com/72263189/195167493-d4cacacf-b62a-48b1-a1b7-924373caaa6e.png)
![image](https://user-images.githubusercontent.com/72263189/195167517-122a20ee-df13-4ffd-b39f-852d062dbfd0.png)

**Comment by BelleNottelling** [comment]
Same thing. They are all using the same icon.
