### ISSUE TITLE
Clean up Huraga CSS

### ISSUE THREAD

**Issue by John-S4** [FOSSBilling/FOSSBilling#355]
Currently it's huge and bloated and calls a separate sheet containing everything for each colour variant, which makes it a real hassle to maintain or change anything. 

- Remove all of the outdated vendor specific CSS, i.e. moz- webkit- o- and ancient IE hacks
- Separate out colours from everything else, leaving one main sheet to be always loaded, and smaller colour sheets for each variant. 

I've already started working on this, but it is taking far more time than I expected, and I'm also far more busy than I expected, but I will find some time this week to get it finished.

**Comment by evrifaessa** [comment]
@John-S4 hey, anything new? Can we get it ready before the initial release?

**Comment by BelleNottelling** [comment]
Hey, @John-S4 

Just wondering where this is at since I did the big huraga cleanup awhile ago.
The CSS still needs work (such as removing IE hacks and such)

**Comment by BelleNottelling** [comment]
Over the last handful of releases, this has been fully completed to the extent that doesn't require a rewrite of Huraga.
I've drastically cleaned up the CSS by moving all of the main components to the "huraga-main" CSS and then moved the different colors to their own CSS files, which nearly cut the overall CSS size by 1/4th. Then just recently I've ran the CSS through autoprefixer which removed a bit over 1k lines of outdated browser prefixes from the CSS.
