### ISSUE TITLE
[Feature Request] Gift cards

### ISSUE THREAD

**Issue by Coo-ops** [FOSSBilling/FOSSBilling#36]
Gift cards

Deny the use of Gift Cards to purchase some products, such as Gift Cards

https://github.com/boxbilling/boxbilling/issues/1271
https://github.com/boxbilling/boxbilling/issues/1266

**Comment by John-S4** [comment]
This feature request is over a year old and it seems to be very low priority, also probably not a high level of demand for selling hosting, etc. although I can see why they might be useful for digital downloads. 

Closing this issue for now, although it may be revisited in the future.
