### ISSUE TITLE
[Bug] Unable to create order

### ISSUE THREAD

**Issue by jaapmarcus** [FOSSBilling/FOSSBilling#363]
**Describe the bug**

<img width="508" alt="Screenshot 2022-10-19 at 13 12 16" src="https://user-images.githubusercontent.com/9754650/196675817-b029f680-f791-4771-a79a-1ae296bb1ddc.png">

**To Reproduce**
- Create new order
- Select user 
- Plan hosted on HestiaCP 
- Create the required info

Account has been created but an error is visible

No php error is really shown

**Expected behavior**
Success message to be show. 

**Screenshots**

**Desktop (please complete the following information):**
OSX / Safari last version

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BelleNottelling** [comment]
Yup, I'm able to replicate this

**Comment by jaapmarcus** [comment]
I don't know if it was caused by https://github.com/FOSSBilling/FOSSBilling/pull/392

If not we should enable logging to logs by default. It is currently searching in a bloody haystack

**Comment by BelleNottelling** [comment]
> I don't know if it was caused by #392
> 
> If not we should enable logging to logs by default. It is currently searching in a bloody haystack

The two seem to be unrelated

**Comment by BelleNottelling** [comment]
This one is weird..

**Comment by jaapmarcus** [comment]
> This one is weird..

I agree also the lack of errors it self is strange..

**Comment by jaapmarcus** [comment]
Not releated to FB/BB

Caused by the fact that Hestia restarts php where and causing a timeout
