### ISSUE TITLE
[Feature Request] Razor Pay Card Processor

### ISSUE THREAD

**Issue by Coo-ops** [FOSSBilling/FOSSBilling#37]
https://github.com/boxbilling/boxbilling/issues/1267

Feature request for razorpay payment gateway

For better payment gateway through razorpay

**Comment by weismannweb** [comment]
supported by https://github.com/FOSSBilling/FOSSBilling/issues/303

**Comment by BelleNottelling** [comment]
Closing to make one larger issue to track the payment gateways that have been requested
