### ISSUE TITLE
Display an error on PHP 7.4 and lower

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#376]
The code is clearly incompatible with PHP 7.4 and lower. So instead of displaying random error messages, display a clear message saying FOSSBilling only runs on PHP 8.0 and later.

**Comment by John-S4** [comment]
Added this to 0.0.2 because that is where the 'assign codes to errors' is, and it would be good to get all of the error stuff taken care of together.

**Comment by evrifaessa** [comment]
> Added this to 0.0.2 because that is where the 'assign codes to errors' is, and it would be good to get all of the error stuff taken care of together. 

great idea.
