### ISSUE TITLE
[Bug] Custom pages don't work

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#383]
**Describe the bug**
Custom pages don't work and display 404 errors in Huraga. I don't know why it happens, but one possible cause might be the Huraga theme.

I don't know how it was integrated back then. But if it was integrated in a theme-level, we had 3 themes before and might have left out Huraga while doing the work.

**To Reproduce**
1. Enable the "Custom Pages" extension
2. Go to "admin/custompages" and create a new custom page
3. Click the first button in the action menu
4. It will take you to a non-existent page

**Expected behavior**
The custom page should appear regularly.

**Screenshots**
![image](https://user-images.githubusercontent.com/35808275/197415403-be01b66e-5559-4109-b82c-dbbc3cc8fd4f.png)

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - Browser: Mozilla Firefox

**Server**
- Web server: nginx

**Comment by BelleNottelling** [comment]
Works fine for me. Did you run cron yet?
![image](https://user-images.githubusercontent.com/17304943/197878778-d364fc3a-42f7-474f-b431-5bcef4cb02bb.png)

**Comment by evrifaessa** [comment]
I did. Still, for some reason it didn't really work. I'll try again later.

**Comment by evrifaessa** [comment]
Seems like a nginx-specific problem. I'll see what I can do.
