### ISSUE TITLE
Call to undefined function idn_to_ascii()

### ISSUE THREAD

**Issue by TeknoHunter** [FOSSBilling/FOSSBilling#388]
Not sure what this is but when I go to create an admin account on a fresh install I get a `Call to undefined function idn_to_ascii()` error. This is using Docker, and I followed the steps on the readme.

**Comment by evrifaessa** [comment]
I’ll quickly update the Docker script. Thanks for the catch.

**Comment by TeknoHunter** [comment]
No problem. Just trying to get my hosting company stuff situated ASAP :)

**Comment by BelleNottelling** [comment]
@TeknoHunter You can manually apply this change to fix that error message:
https://github.com/FOSSBilling/FOSSBilling/pull/389/files

We need another team member to approve it before it can be merged so I'm not entirely sure how long that'll that

**Comment by John-S4** [comment]
Done

**Comment by evrifaessa** [comment]
Thanks John and Belle :)

@TeknoHunter it should now be merged. Please re-open the issue if the issue persists. You also might want to join [our Discord server](https://fossbilling.org/discord). Have a nice day!
