### ISSUE TITLE
[Bug] Plesk module potentially out of date

### ISSUE THREAD

**Issue by 0x6b-dev** [FOSSBilling/FOSSBilling#39]
https://github.com/boxbilling/boxbilling/issues/1260

What happened?

plesk server extension api xml need update "/api/v2/server"
BoxBilling Version

v4.21
What version of PHP are you running?

PHP 8.0
Additional Notes

Additional notes

**Comment by John-S4** [comment]
Problem raised in the original Issue were fixed by #20 

Tested with the latest Plesk version and there are no problems.
