### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#4]
We don't have to continue from v4.22.x or v4.23.x. Let's decide if we want to do it or not.

**Comment by jaapmarcus** [comment]
As we make extremely large changes 5.0.0 makes the most sense

**Comment by gOOvER** [comment]
its a "New" Project. Why Not start from beginning?

1.0.0

**Comment by jaapmarcus** [comment]
If we going to switch to a different framework it makes sense

**Comment by BelleNottelling** [comment]
I think since this is a new project and new branding, let's start with version 1.0.0

**Comment by hyknn** [comment]
1.0.0 is fine

**Comment by jaapmarcus** [comment]
0.x.x for until final release 

After that 1.0.0

**Comment by John-S4** [comment]
It definitely makes no sense to continue numbering from previous BB versions. 

Much better to start with fresh numbers. 1.0 sounds like a big stable release, so I think until it definitely hits that point then 0.x is the way to go.

**Comment by John-S4** [comment]
This has essentially been decided as shown in the current roadmap - https://github.com/orgs/FOSSBilling/projects/2/views/8 and in the comments above. 

The Lara rewrite will be Release 1.0.0 with everything up to that point being a point release, 0.x for releases including larger function additions or changes and 0.0.x for bug fix releases.
