### ISSUE TITLE
[Feature Request] Clarify password rules

### ISSUE THREAD

**Issue by 0x6b-dev** [FOSSBilling/FOSSBilling#40]
https://github.com/boxbilling/boxbilling/issues/1255

**Comment by John-S4** [comment]
Yep, the current password requirements are pretty loose. 

As a minimum we should be

**Comment by John-S4** [comment]
Yep, the current password requirements are pretty loose. 

As a minimum we should be requiring:

**Comment by jaapmarcus** [comment]
Current rules only require at least one 1 letter  

@hestiacp we enforce min length of  8 + 1  lowercase, 1 uppercase and 1 number

**Comment by 0x6b-dev** [comment]
In the short term we should be looking at 12 characters minimum + MFA or even passwordless (magic link, the same way OpenCollective works).

Long term I’d love to see SSO / SAML such as a Google or GitHub login as an authentication provider.

**Comment by John-S4** [comment]
> + MFA 

Agree about MFA, it should absolutely be there, but I noticed a separate issue #62 about that was already created and assigned, so just assumed we were talking solely about passwords themselves. 

SSO is great, but as an option rather than a "You need to use this" - a lot of people don't want to use Google/GH/FB to log in to everything else.

**Comment by jaapmarcus** [comment]
> In the short term we should be looking at 12 characters minimum + MFA or even passwordless (magic link, the same way OpenCollective works).
> 
> Long term I’d love to see SSO / SAML such as a Google or GitHub login as an authentication provider.

Magic link will not always work unless we add support for SMTP relay providers (Amazon SES, SMTP2GO and so on)  as port 25 might be blocked. 

I am fine with a min length of 12 chars as minimum.  MFA  / 2FA shouldn't not be forced.  And SSO should be optional...

**Comment by 0x6b-dev** [comment]
But the system sends emails for bills already. So if you’re having issue with port 25 and you’re a hosting provider… I’ve got bad news for you.

Yes MFA shouldn’t be forced, but an option to make it mandatory for users and admins should exist.

**Comment by evrifaessa** [comment]
User/staff groups and roles should have a setting that forces 2FA.

**Comment by jaapmarcus** [comment]
> But the system sends emails for bills already. So if you’re having issue with port 25 and you’re a hosting provider… I’ve got bad news for you.
> 
> Yes MFA shouldn’t be forced, but an option to make it mandatory for users and admins should exist.

Even then we should add it a lot of providers have it blocked so a support for SMTP relay is use full

**Comment by John-S4** [comment]
MFA and/or Magic Link would be good to include in the near future, but right now this is one of the items on the roadmap for 0.0.1, so I think it would be enough at this moment to clarify and enforce rules for strong passwords. 

> we enforce min length of 8 + 1 lowercase, 1 uppercase and 1 number

That works for me.

**Comment by 0x6b-dev** [comment]
As of 2022 we should be talking at least 12-14 characters… not 8. Plus MFA.

**Comment by John-S4** [comment]
MFA will come with the rewrite but I'm not sure we want to take the time to implement of before then.

A 12 character min is fine rather than 8.

There does not need to be a stated max password length, but there shoukd be an actual limit to a sensible number of characters, 30, 50, whatever.

**Comment by evrifaessa** [comment]
Why do we need to limit the maximum number of characters? Unless there's a technical requirement, I wouldn't want to limit it to anything.

**Comment by 0x6b-dev** [comment]
Nah there totally doesn't need to be a maximum. Because maximums are for people who aren't hashing your password, which we totally will be.

**Comment by John-S4** [comment]
>Why do we need to limit the maximum number of characters?

Because Long Password DOS is a thing and while it might not be a common attack route, it is out there.

It does need passwords of massive length to be effective though, like 1,000,000 characters, so we can set a limit of 500 characters, 1,000 or whatever, but there should be an upper limit.

**Comment by John-S4** [comment]
According to OWASP 

>Password Length
Minimum length of the passwords should be enforced by the application. Passwords shorter than 8 characters are considered to be weak ([NIST SP800-63B](https://pages.nist.gov/800-63-3/sp800-63b.html)).
Maximum password length should not be set too low, as it will prevent users from creating passphrases. A common maximum length is 64 characters due to limitations in certain hashing algorithms, as discussed in the [Password Storage Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#maximum-password-lengths). It is important to set a maximum password length to prevent [long password Denial of Service attacks](https://www.acunetix.com/vulnerabilities/web/long-password-denial-of-service/).

**Comment by John-S4** [comment]
PR #369 is a step towards this, but doesn't go as far as most of the suggestions in here in terms of password requirements. 

Are we happy with 8 characters, uppercase, lowercase, and a number?

If so this can be closed, or should a symbol and a higher min length be required?

**Comment by jaapmarcus** [comment]
For minimum is fine unless we want to go to 16?

**Comment by BelleNottelling** [comment]
I feel like 16 might be a bit much for a minimum. How about 12?

Also, I know there was talk about a password being too long, so we could put an upper limit of 256/512?
I don't want to make it something like 64 as people using passphrases or password managers may want to do longer (like 128)

**Comment by jaapmarcus** [comment]
I think 2FA support adds more security to it than increasing password length. 

8 Chars is fine for me...

Max length 128 or even 256 is fine for me. Don't think more is needed.

**Comment by BelleNottelling** [comment]
I agree.
We have a separate issue for MFA & I'll get a PR to set the max to 256 char.
I think we should be good to close this issue now.

We can really easily change the requirements later if we decide we want to
