### ISSUE TITLE
[Feature Request] BTCPay and/or BitpayCC

### ISSUE THREAD

**Issue by 0x6b-dev** [FOSSBilling/FOSSBilling#41]
https://github.com/boxbilling/boxbilling/issues/1250

What is the idea?

This tool is fine, but it's useless without cryptocurrency support, because even your WHMCS competitor that has a proprietary license will accept cryptocurrency payments.

There are decentralized payment processors in cryptocurrencies like BTCPay https://btcpayserver.org/ and BitcartCC https://bitcartcc.com/ that you can integrate with this BoxBiling.
Why would this be beneficial

Be aware that this is a more than elementary feature, it will guarantee anonymity to customers and also to the administrator. With cryptocurrency, censorship and unnecessary fees are avoided.

This is an important feature.

**Comment by John-S4** [comment]
I only just noticed this issue. 

I'm not sure that FOSSBilling is "useless" without crypto support or that it is "more than elementary" but yes, it would be useful to some people to have a crypto payment option. 

Probably best implemented as separate payment modules for different crypto payment gateways, in the same way as modules for gateways like Stripe or Paypal will be, and not necessarily something that needs to be supported as part of core maintained modules. 

P.S. comment is on the original issue, and not shooting the messenger @0x6b-dev :)

**Comment by MrNaif2018** [comment]
Hi! Just wanted to add that if you decide to add BitcartCC support, I could be of help to advise on how could this be implemented, i.e. how to detect invoice status changes, how it all works, etc. Always welcoming new integrations!

**Comment by MrNaif2018** [comment]
BitcartCC is the first cryptocurrency payment processor to add a plugin for FOSSBilling

You can now accept BTC, LTC, BCH, ETH, BNB and any ERC20/BEP20 tokens (and stablecoins) via BitcartCC

https://github.com/bitcartcc/bitcart-boxbilling
https://youtu.be/t8YFOhTngQo

Should it be added to the FOSSBilling distribution itself, or leave as a separate repo in our github organization?

**Comment by evrifaessa** [comment]
@MrNaif2018 hey, thanks for the contribution :) Until we have our extension store up and running again, I'll add your extension to our list of extensions in our documentation. We'll get in touch with the extension developers again once we get the store up.

**Comment by MrNaif2018** [comment]
Thanks, I see it! @evrifaessa but please, fix our name to BitcartCC (with t instead of d) in developed by line. I wonder if it's confusing (:

**Comment by evrifaessa** [comment]
> Thanks, I see it! @evrifaessa but please, fix our name to BitcartCC (with t instead of d) in developed by line. I wonder if it's confusing (:

Oh right, sorry for that. kind of tired.
