### ISSUE TITLE
[Bug] Theme huraga, guest index page is keeping its windows on custom pages (module)

### ISSUE THREAD

**Issue by xSido** [FOSSBilling/FOSSBilling#412]
I would consider it a bug because for logged users it has a different design than guests, but since on this theme guests never had a index page with site preview, i will call it a feature request.

For guests, when you are visiting the dashboard page, you are welcomed with 4 small panels ( Profile, Order, News and Knowledge Base)

When you are creating a custom page, this panels are still kept while, for logged users, they are hidden and displayed only the panel related to the custom page.
I believe they should not be shown on custom pages.

and since i'm talking about these panels
would be awesome to be able to enable/disable them from theme settings.

**Comment by BelleNottelling** [comment]
> and since i'm talking about these panels
> would be awesome to be able to enable/disable them from theme settings.

You can disable the guest dashboard already. Unless you mean a separate setting in which case tht would be a new feature.
![image](https://user-images.githubusercontent.com/17304943/199120566-41b0b639-db68-41d6-852c-93d27d3c665e.png)

**Comment by xSido** [comment]
I am talking about these.

![IMG_20221101_065751](https://user-images.githubusercontent.com/45123194/199162358-0609cf21-76c8-4859-9d7c-81ab1c649263.jpg)

1. Remove them from custom pages 
If you are guest, and visiting a custom page, you can see these too displayed on custom page you made
If you are logged user, on custom page you can see only the custom page you did

2. If possible, create an option to disable or enable each of these 4 panel
For example, display only order and news, or none at all.

**Comment by xSido** [comment]
![11a](https://user-images.githubusercontent.com/45123194/199163229-d6d0bf91-d0a0-4971-8a15-e219e7584ffb.png)
![22a](https://user-images.githubusercontent.com/45123194/199163237-fb5d8ed6-b7e1-49e5-8bbc-2f5046048c45.png)

**Comment by evrifaessa** [comment]
@BelleNottelling how should we solve the incostistency? I think we should hide the cards from the visitor layout like we do with the logged-in-client layout.

**Comment by BelleNottelling** [comment]
> @BelleNottelling how should we solve the incostistency? I think we should hide the cards from the visitor layout like we do with the logged-in-client layout.

That's the plan
