### ISSUE TITLE
[Bug] Failed Setup via Hestia CP

### ISSUE THREAD

**Issue by PotatoRui** [FOSSBilling/FOSSBilling#415]
**Describe the bug**

**To Reproduce**
1. login as client
2. put a new order for hosting
3. failed setup

**Expected behavior**
The setup should be successful , I tested the api connections via admin area and it works.
1st test with wrong password it throws error, that means it can reach the hestia panel.
![image](https://user-images.githubusercontent.com/49616497/199451124-fc5908d3-eec2-473f-b72f-cf512f1e68a6.png)
2nd test with right password it shows connected, it means that it can reach the panel.
![image](https://user-images.githubusercontent.com/49616497/199451299-f0a16cd4-7f89-4c98-8121-54877908f248.png)

Version:
Stable version of [FOSSBilling 93705bb](https://fossbilling.org/) and Im using Hestia v1.6.10

**Comment by jaapmarcus** [comment]
See:
https://github.com/FOSSBilling/FOSSBilling/issues/363
And 
https://github.com/hestiacp/hestiacp/issues/1236

Hestia adds domain to the system restarts php -> 504 

Hosting Fossbilling on a different server works fine

**Comment by BelleNottelling** [comment]
@jaapmarcus is there a way you can fix this, our should we update the integration to throw an exception if the configured IP is the same as the one FOSSBilling is running on?

**Comment by jaapmarcus** [comment]
See attached PR. Will need to wait till Hesita 1.7.0 or 1.6.12 release
