### ISSUE TITLE
[Bug] Can't change currency for client

### ISSUE THREAD

**Issue by 0x6b-dev** [FOSSBilling/FOSSBilling#42]
https://github.com/boxbilling/boxbilling/issues/1247

What happened?

I have error when I change Currency for Client from admin to edit currency from Client account, also Client have error when try choose other currency in new order ( order can not be complete with other currency must be same currency under client account )... must be currency same as first order time for client but in future client can't make order with other currency ?

SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column testacp.client.client_group_id at row 1

Thank you..
Michael
BoxBilling Version

Current Master Branch
What version of PHP are you running?

PHP 7.4
Additional Notes

change Currency for Client

**Comment by notbasetwo** [comment]
This is a very strange one. I seem to be able to replicate this too, When multiple currencies were added, it was no longer possible to add a client via the admin CP (did not check normally) and this exact error came up.

**Comment by John-S4** [comment]
@notbasetwo I've also managed to replicate this, and I also think that it's really strange.

Anybody have any thoughts on what might be causing this?

**Comment by phonkala** [comment]
Same datetime error when saving a new Client. But this only happens when no group is selected, right away when I chose group "Default", the error was gone and Client was created. Probably something to do with that I guess, cos there is no group id chosen then.

**Comment by evrifaessa** [comment]
@phonkala can you post the exact error?

**Comment by evrifaessa** [comment]
Is this still valid?

**Comment by BelleNottelling** [comment]
> Is this still valid?

Yes. This error (or at least the underlying issue of now group ID being set) can be reproduced in multiple areas
