### ISSUE TITLE
[Bug] Enabling Email logging fills the database endlessly.

### ISSUE THREAD

**Issue by d3dx9** [FOSSBilling/FOSSBilling#426]
**Describe the bug**
Enabling Email logging fills the database endlessly. The mysql table activty_client_email got filled up, sadly I had to delete it else I couldnt access the whole database anymore.

36G     activity_client_email.MYD
23M     activity_client_email.MYI
58G     activity_client_email.TMD

The installation is a migration of BoxBilling and the bug happened overnight after the upgrade.

**To Reproduce**
Enable Email logging

**Expected behavior**
It is expected not to fill up the database and making the complete installation unusuable.

**Comment by BelleNottelling** [comment]
When you migrated this installation, did you update the email templates to be compatible?

**Comment by evrifaessa** [comment]
@d3dx9, this should be fixed with #429. Can you confirm the fix?

**Comment by BelleNottelling** [comment]
Got confirmation from the reporter that this issue appears to be solved
