### ISSUE TITLE
[Feature Request] Track upstream and periodically update dependencies

### ISSUE THREAD

**Issue by Coo-ops** [FOSSBilling/FOSSBilling#43]
https://github.com/boxbilling/boxbilling/issues/1244

We have some dependencies other than the Composer packages we're using.

We should keep them updated and find a way to be notified whenever they release a new update.

Including but not limited to:

    CKEditor 4 (see 

    https://github.com/boxbilling/boxbilling/issues/1245 too)
    RedBean
    tfpdf
    PdoSessionHandler
    php-gettext
    hardcoded libs inside some server managers
    CSRF-Protector-PHP

also theme dependencies (also see https://github.com/boxbilling/boxbilling/issues/978):

Bootstrap
jQuery

    Font Awesome

We should also document the process for updating each of these so the new maintainers will have an easier time. Some of these can (and if possible, should) be replaced with automated package managers. We can even drop some of them entirely.

**Comment by BelleNottelling** [comment]
tfpdf and CSRF-Protector-PHP have replaced / removed so we don't need to worry about those two

**Comment by BelleNottelling** [comment]
Updated list:

- RedBeanPHP
- PdoSessionHandler
- Both WYSIWYG editors
- Theme dependencies
   - Bootstrap
   - jQuery
   - A handful of jQuery plugins
   - Font Awesome
- Whatever server managers and the likes may use

**Comment by John-S4** [comment]
I believe that the vast majority of the discussed dependencies have either been eliminated, including most jquery stuff, or are tracked by dependabot. Anything remaining is largely related to Huraga and so will be resolved when we have a new therme at some future point.
