### ISSUE TITLE
[Feature Request] Rootpanel integration

### ISSUE THREAD

**Issue by insxa** [FOSSBilling/FOSSBilling#431]
Can you integrate Rootpanel for domain registration ?
I have API access for testing if needed.
Here is example for Hopebilling and how its made for:
 [Link](https://github.com/vityabond/hopebilling/blob/master/app/classes/domain/RootPanel.php)
I wish we have registar module for domain provisioning like this because its wide used and it can help lots of registrars to offer fossbilling for their users who wants to use domain reselling.
Here is the API doc for Rootpanel:
[Link](https://billing.rootpanel.net/apidoc.php
)

**Comment by evrifaessa** [comment]
Likely not going to happen anytime soon.

**Comment by jaapmarcus** [comment]
You might need to build it your self. More information about it can be found here:

https://github.com/FOSSBilling/FOSSBilling/tree/main/src/library/Server/Manager

**Comment by John-S4** [comment]
I'm going to admit to being completely confused about what Rootpanel even is. This issue talks about domain registration, but their website seems to be mostly a demo for a billing panel which is described as "billing for hosting, games, iptv, and any sales", and I can't find anything registrar related there apart from in the linked docs.

I don't see any reason for a billing panel to integrate with another billing panel, so I am closing this issue. If I'm wrong and anyone can explain it clearly, then feel free to do so and it can potentially be reopened.

**Comment by John-S4** [comment]
I'm going to admit to being completely confused about what Rootpanel even is. This issue talks about domain registration, but their website seems to be mostly a demo for a billing panel which is described as "billing for hosting, games, iptv, and any sales", and I can't find anything registrar related there apart from in the linked docs.

I don't see any reason for a billing panel to integrate with another billing panel, so I am closing this issue. If I'm wrong and anyone can explain it clearly, then feel free to do so and it can potentially be reopened.

**Comment by insxa** [comment]
If my billing is main for selling domains, i need other billing that can offer reseller sell domains from their billing through API.
Like im registar only i use own billing if you understand
