### ISSUE TITLE
[Bug] Connection testing won't work on some adapters

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#434]
* [x] Plesk: Works. Also returns helpful error messages
* [x] Hestia: Works after https://github.com/FOSSBilling/FOSSBilling/issues/435

**Comment by BelleNottelling** [comment]
The one that actually had a known issue was Hestia and that's been fixed, I'm going to close this as in it's current form it's a non-actionable issue, and honestly I suspect that if this applies to any of the existing server managers that it's going to be one that doesn't work at all.
