### ISSUE TITLE
[Feature Request] Update to branch / fork branch 

### ISSUE THREAD

**Issue by jaapmarcus** [FOSSBilling/FOSSBilling#439]
In Hestia we have to option to install any branch via:

v-update-sys-hestia-git fork branch to install/test a  branch (of a fork).   It would be useful to have this option available for testing...  

**Is your feature request related to a problem? Please describe.**
Option to install test branch  instead preview or release. 

https://github.com/FOSSBilling/FOSSBilling/pull/418

Works great for preview version but it would be awesome to also allow other branches so easier test can be done.

**Describe the solution you'd like**
Provide Fork + branch and let fossbilling install it from source

**Describe alternatives you've considered**
 Tried to write something in bash:
 ```
 #!/bin/bash

username=$1
branch=$2
if [ -z "$branch" ]; then 
  branch="main"
fi

FB_ARCHIVE_LINK='https://github.com/'$username'/FOSSBilling/archive/'$branch'.tar.gz'

wget $FB_ARCHIVE_LINK 
tar -xvf  $branch.tar.gz

cd FOSSBilling-$branch

npm install
gulp 
cd src
composer install
rm -fr install
cd ..
cp -rlf ./src/ ../../
cd ..
rm -fr ../src/bb-data/cache/*
rm -fr FOSSBilling-$branch
rm -fr $branch.tar.gz
ls 
```
Does work

**Additional context**

**Comment by BelleNottelling** [comment]
So, I'd like to hear other people provide their input on this, but imo there's no reason to build this feature into FOSSBilling.
It's added complexity for little benefit. To properly automate that, we'd need it to download the source code, install composer packages, run NPM and Gulp, clear the cache, and run the foss-update.php file.

All while having no way to ensure that FOSSBilling will have the correct permissions on the server to actually exec the functions, that the functions will work on the OS it's being hosted on, and that all required packages are installed.

Both are issues that Hestia doesn't need to deal with nearly as much, as it only supports Debian / Ubuntu. It's also installed system-level meaning that you can ensure all of the require packages and software is installed and that the permissions are all sorted out.

If you want to write a bash script to help aid the process, I'm fine with including it as a stand-alone script in the github repo, but trying to add it to the main software is a bit much

**Comment by BelleNottelling** [comment]
No point in keeping this open if we aren't going to implement it
