### ISSUE TITLE
[Feature Request] Azuracast Support (Internet Radio)

### ISSUE THREAD

**Issue by Coo-ops** [FOSSBilling/FOSSBilling#45]
What is the idea?

Bill module for open source audio streaming software Azuracast
Why would this be beneficial

It will add more features and support for other open source project

**Comment by John-S4** [comment]
This is pretty niche.

No reason that there can't be a module for it but, given the tiny amount of people who would potentially use it, it's quite low priority.

**Comment by notbasetwo** [comment]
I think it'd be relatively well recieved but shouldn't be part of any core modules maintained generally by the project, at least at the moment.

**Comment by BelleNottelling** [comment]
Azuracast looks interesting, however I'd consider support for it to be out-of-scope for the core software and with the current size of the team it's not something we will officially be building and providing.
