### ISSUE TITLE
Get rid of the stylesheet we carried over from BoxBilling

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#467]
We still ship our admin theme with CSS and JS files carried over from BoxBilling bundled as a fallback.

We should migrate all of our views to Tabler and stop bundling the whole old BB admin theme stylesheet.

**Comment by John-S4** [comment]
So, are there any views that are still actively using the 'fallback', what's stopping it from just being dropped?

**Comment by BelleNottelling** [comment]
This is now fully completed
