### ISSUE TITLE
[Bug]Server Manager Hestia CP Error: Unable to create User

### ISSUE THREAD

**Issue by buycn** [FOSSBilling/FOSSBilling#470]
I used **Hestia CP** to connect to the server with foss. They have successfully connected. However, after I use the customer account to create an order, I cannot create a new user with hestia. How can I troubleshoot the next step?

**Comment by evrifaessa** [comment]
Try manually activating the order through your admin panel. It should display the error message.

Go to orders and select the order. The activation button is there.

**Comment by buycn** [comment]
I have tried to activate from the administrator's order, but it still shows that user creation failed

**Comment by evrifaessa** [comment]
Yes, it should.

But it also should display the error message as a notification in the bottom right.

You also might want to check your PHP logs. They usually are under `bb-data/log`

**Comment by jaapmarcus** [comment]
Or check logs /var/log/hestia/error.log

**Comment by buycn** [comment]
[19-Nov-2022 14:46:24 UTC] 2 Undefined variable $result1 /home/one/web/app.vmhost.cn/public_html/bb-library/Server/Manager/Hestia.php 195
[19-Nov-2022 14:46:24 UTC] Server Manager Hestia CP Error: Unable to create User  0


![image](https://user-images.githubusercontent.com/74414063/202857052-dd48cd64-1220-44e1-b0de-b26edad1a0f4.png)
The error occurs in server/manager/asia In the php file.

**Comment by jakobbouchard** [comment]
Can confirm I get the same error, the `$result` variable should be named `$result1` instead.

**Comment by BelleNottelling** [comment]
@buycn Can you update your FOSSBilling installation, try it again, and then give the new error message?

**Comment by joseluismktcuba** [comment]
The same error happens to me with the hestiacp.

The connection with the server if it goes well.

But it doesn't create the user in hestiacp, and it doesn't prepare the server either.

**Comment by buycn** [comment]
I try to create a default package first, which can normally create users under the same server name and configuration

**Comment by jaapmarcus** [comment]
> The same error happens to me with the hestiacp.
> 
> The connection with the server if it goes well.
> 
> But it doesn't create the user in hestiacp, and it doesn't prepare the server either.

make sure the packages allready exists before trying to attempt creating the user. It should work fine...

**Comment by joseluismktcuba** [comment]
> make sure the packages allready exists before trying to attempt creating the user. It should work fine...

Do you mean that it creates the packages in hestiacp?

**Comment by jaapmarcus** [comment]
No you need to create the packages first your self and they need to match exactly with the package "name"
