### ISSUE TITLE
Use modals instead of browser alerts and jConfirm

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#475]
Tabler has great modals: https://preview.tabler.io/modals.html

I think they look a lot nicer, they also enable us to make the intent more clear using icons and colors.

For reference, here is how browser alerts look in Firefox:

![image](https://user-images.githubusercontent.com/35808275/202922170-3506fa27-30d8-4c5b-a01d-cd705c881efb.png)

Here are how some of the modals look:

![image](https://user-images.githubusercontent.com/35808275/202922065-25909de6-b37d-419b-9535-58e73baa1054.png)
![image](https://user-images.githubusercontent.com/35808275/202922073-ba2461a6-317a-455e-8ab4-03a0037ccac7.png)
![image](https://user-images.githubusercontent.com/35808275/202922077-f1bd6dad-d78d-4d71-9a88-48c573b6a41e.png)

We also could change some of our full-page forms into modals:

![image](https://user-images.githubusercontent.com/35808275/202922098-01ace7d4-2a38-4c7f-be98-857e8e1c148c.png)

**Comment by jaapmarcus** [comment]
For sure ..

**Comment by evrifaessa** [comment]
This task also should include getting rid of jConfirm and replacing them with the Tabler modals.

**Comment by evrifaessa** [comment]
> I think this issue can be closed now.

Yep, thanks for the reminder.
