### ISSUE TITLE
[Feature Request] Latin American payment gateway

### ISSUE THREAD

**Issue by Coo-ops** [FOSSBilling/FOSSBilling#48]
https://github.com/boxbilling/boxbilling/issues/1177

Feature request hola abran un modulo de pago de boxbilling para latioamerica que sea mas comun y facil de usar como payu latam o mercando pago . epayco,, instapago

hello open a boxbilling payment module for Latin America that is more common and easy to use as :: payu latam.. mercando pago ... . epayco... instapago....
Why would this be beneficial

Benefits

Feature request hola abran un modulo de pago de boxbilling para latioamerica que sea mas comun y facil de usar como payu latam o mercando pago . epayco,, instapago

hello open a boxbilling payment module for Latin America that is more common and easy to use as :: payu latam.. mercando pago ... . epayco... instapago....

**Comment by BelleNottelling** [comment]
Closing to make one larger issue to track the payment gateways that have been requested
