### ISSUE TITLE
[Bug] Problem in admin theme settings

### ISSUE THREAD

**Issue by joseluismktcuba** [FOSSBilling/FOSSBilling#496]
**Describe the bug**
Problem in admin theme settings

**To Reproduce**
1. Go to 'Setting/Themes'
2. Click on 'Admin area themes in theme default in the botton Setting'

**Comment by evrifaessa** [comment]
What is the error? We would be glad if you share it here too.

**Comment by joseluismktcuba** [comment]
> 

404
Oops... You just found an error page

Page /theme_default not found

**Comment by evrifaessa** [comment]
Oh, it's okay. We just don't have anything to put there so the error should be fine.

But we might just hide the "settings" button instead, that should be better.

**Comment by joseluismktcuba** [comment]
Yes, of course, the ideal would be to hide that button.
