### ISSUE TITLE
Front-end changes

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#5]
To begin with, I think we should keep only one theme for the client-area and drop the others. Even better, we can create a new one from scratch instead.

**Comment by gOOvER** [comment]
That would be good. With time there will be people who create other themes

**Comment by jaapmarcus** [comment]
Agree it make sense to focus on on great theme instead spread the focus on 3 different themes. 

We should allow the user to select a theme with css file

**Comment by evrifaessa** [comment]
Which one to keep? Or do we start with an entirely new one?

**Comment by notbasetwo** [comment]
I think it's time to start from scratch. The current themes are super dated and I think a modern theme would totally transform BoxBilling's appearance as a legitimate billing panel.

**Comment by evrifaessa** [comment]
> I think it's time to start from scratch. The current themes are super dated and I think a modern theme would totally transform BoxBilling's appearance as a legitimate billing panel.
> 
> Something bootstrappy (maybe even an upgrade to the original Bootstrap version) could be good as this allows very easy extensibility from users.

We would really benefit from (a) good front-end designer(s).

**Comment by John-S4** [comment]
This is currently on the roadmap for the 0.0.1 release and probably does not need to be, since that release should contain bug and security fixes rather than new features and feature upgrades.

**Comment by John-S4** [comment]
Agree that we should keep just one default theme for now - and while we should probably start from scratch as others have said, that is a bigger body of work, so it would be sensible to go with one of the existing ones for the initial maintenance release, which can then be replaced in a later release.

**Comment by evrifaessa** [comment]
But which one to keep?

**Comment by John-S4** [comment]
Since the Lara branch is going to move themes to be built using Tailwind, this is now a shorter term issue. 

My suggestion is that for the initial 0.0.x releases we either keep as is currently, or drop all client themes except for bootstrap which is the best functioning right now.

**Comment by John-S4** [comment]
Current development for 0.x releases has moved to a single supported theme - Huraga, which we are working on squashing any bugs in. 

1.x and upwards releases will ship with a new theme built using TailwindCSS.
