### ISSUE TITLE
[Bug] PDF not displaying currency icon that is not Dollar

### ISSUE THREAD

**Issue by tobsowo** [FOSSBilling/FOSSBilling#508]
**Describe the bug**
When an invoice is viewed PDF, it replaces currency icon with question mark if not USD.

![image](https://user-images.githubusercontent.com/5642737/205447817-9c081c7c-669d-49a6-8873-cea1a2e5a0a6.png)

**Comment by BelleNottelling** [comment]
Seems to work fine for me, can you share the format from the settings? example: ``€ {{price}}``
![image](https://user-images.githubusercontent.com/17304943/205457932-cd980038-9c94-4fb8-999d-f9038a4ada4a.png)

**Comment by tobsowo** [comment]
Yea this same format but using ₦

**Comment by tobsowo** [comment]
How did you get the currency sign. I copied directly from Google search.

**Comment by BelleNottelling** [comment]
Okay, I'm able to reproduce that using the ₦ symbol.
I think the PDF generator is having issues with Unicode, let me see if there's a fix
