### ISSUE TITLE
[Feature Request] Icon change

### ISSUE THREAD

**Issue by tobsowo** [FOSSBilling/FOSSBilling#512]
Change the copy, edit and delete icon to reflect what they actually do. I have occasionally clicked on the copy button thinking it is settings before realizing it only copied the payment gateway, this also affect other areas it was used.

![image](https://user-images.githubusercontent.com/5642737/205453031-91e5f42f-7eb7-4d3e-83ed-e4ccb1fa8190.png)

**Comment by evrifaessa** [comment]
@tobsowo I've changed them in the domain management and the payment gateways page. Is there any more you could find?
