### ISSUE TITLE
[Bug] Domain Registrar Error

### ISSUE THREAD

**Issue by tobsowo** [FOSSBilling/FOSSBilling#513]
While testing I activated a registrar called email and since that happed I am unable to reach the domain registration settings again, I tried deleting from the email file from folder and still did not work.

![image](https://user-images.githubusercontent.com/5642737/205453123-8fe6e725-6532-4100-8aac-500d03408170.png)

**Comment by jaapmarcus** [comment]
Check the logs please..

**Comment by BelleNottelling** [comment]
Hey @tobsowo 
It's not the most convenient way to do it, but you can access your database, go to the `tld_registrar` table, and then delete the row associated with that registrar. That'll get you back into the dashboard

**Comment by tobsowo** [comment]
I'll try that. Thank you @BelleNottelling
