### ISSUE TITLE
[Enhancement] Staff Permission

### ISSUE THREAD

**Issue by tobsowo** [FOSSBilling/FOSSBilling#514]
After creating a staff and assigning support permission, staff is unable to access tickets when support is ticked.

Also, can the access be at the group level instead of individual staff so that any new staff created and linked to a group automatically have the required permission and any slight changes can be done on individual level too if necessary.

**Comment by evrifaessa** [comment]
We will rework the permission system at some point. And the suggestion to make it group-level is a good idea.

**Comment by BelleNottelling** [comment]
> This will be reworked with #1545 

No, only half of it will be. 

Otherwise I would have linked this issue to that PR

**Comment by Anuril** [comment]
Sorry, my bad. Maybe we could include it?

**Comment by BelleNottelling** [comment]
No, I'm not implementing group-based permissions in that PR. That's been stated a couple of times now.

I'm not sure how I'd want it to work and I also probably will redo the concept of staff groups in the process as well. 

The other part of this is actually complete in the PR now. 

Once it's merged, we can probably close all permission related issues and consolidate them down to just one for reworking groups and adding permissions to them as well as AFAIK that's all that will be left of both this and the other one

**Comment by BelleNottelling** [comment]
Re-reviewing this, I believe the first item was a bug (probably an authentication failed error from when we first introduced the CSRFT system?).

Either way, that's likely fixed now or will be with the refactored permission system.
Group level permissions are going to be implemented as part of #1869.

Once we publish 0.6.0 (should be fairly soon as long as we don't find many regressions), feel free to open an new issue if you're still getting the permissions bug. For now though, I am calling this one completed
