### ISSUE TITLE
[Bug] Recent Client Activity on Dashboard

### ISSUE THREAD

**Issue by tobsowo** [FOSSBilling/FOSSBilling#515]
On the admin dashboard the "recent staff activity" works as expected but the "recent client activity" is not. Is this a know issue?
![image](https://user-images.githubusercontent.com/5642737/205453493-06d86928-2656-42eb-9072-a0f29b681f9b.png)

**Comment by BelleNottelling** [comment]
I don't think the client activity works if it's being created from the same system that a staff member is logged in as, it appears under the staff activity. Otherwise, it works just fine for me
