### ISSUE TITLE
[Bug] Subscription auto list clients

### ISSUE THREAD

**Issue by tobsowo** [FOSSBilling/FOSSBilling#522]
Creating a subscription and searching for client is not listing any contact.
![image](https://user-images.githubusercontent.com/5642737/205461122-62b3f9c5-385d-4fe8-8a6a-216766790386.png)

**Comment by BelleNottelling** [comment]
So, for whatever reason the client search doesn't work for clients that don't have their last name defined

**Comment by evrifaessa** [comment]
We should rework the client selector. It depends on old code carried from BB and we can improve the styling.

**Comment by tobsowo** [comment]
I tried adding a last name but it still same @BelleNottelling maybe reworking as @evrifaessa suggested will do.

**Comment by BelleNottelling** [comment]
Hey @tobsowo this should now be working correctly with 0.2.4.
I'm going to close this as resolved, feel free to reopen if the issue is still ongoing

**Comment by tobsowo** [comment]
Yes, fixed.

I noticed the drop down list is not using the admin theme but no worries, it's working.
