### ISSUE TITLE
[Bug] Old styles in mass delete alert

### ISSUE THREAD

**Issue by jaapmarcus** [FOSSBilling/FOSSBilling#531]
**Describe the bug**
<img width="1202" alt="Screenshot 2022-12-05 at 23 03 47" src="https://user-images.githubusercontent.com/9754650/205752221-3322ad29-331a-4281-b3e3-2419bd5a1c03.png">

**To Reproduce**
Click on "Delete selected" 

**Expected behavior**
Should be in new UI

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BelleNottelling** [comment]
I believe this should be completely resolved now
