### ISSUE TITLE
A common JavaScript toolkit for the front end

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#546]
It isn't efficient to have each theme define their own way to interact with the back end API.

We should introduce a toolkit with the barebones to interact with the API. It's hard to update every theme's JavaScript code when we introduce something new or breaking. A common toolkit would be easier to maintenance in the long run, and would make it easier for custom themes to appear.

**Comment by BelleNottelling** [comment]
I've assigned this to you since you were working on it.
