### ISSUE TITLE
[Feature Request] (New) Sentora Module

### ISSUE THREAD

**Issue by Coo-ops** [FOSSBilling/FOSSBilling#55]
https://github.com/boxbilling/boxbilling/issues/1091

**Comment by altomarketing** [comment]
REally ? Sentora is a discontinued project

**Comment by John-S4** [comment]
> REally ? Sentora is a discontinued project

Is it entirely though?

It's definitely not moving very fast and the current release is probably not something that anyone should use in production, but there does seem to be some work going on somewhere in the background, and there was a public beta release of a v2 at the start of this year. See http://forums.sentora.org/showthread.php?tid=12794

I don't know much more about it than that, but it might not be completely dead, possibly, maybe.

**Comment by John-S4** [comment]
Closed and added to #1362

**Comment by admdly** [comment]
Set as sub-issue of #1362.
