### ISSUE TITLE
[Bug] Virtualmin adapter doesn't work

### ISSUE THREAD

**Issue by xinomilo** [FOSSBilling/FOSSBilling#551]
**Describe the bug**
Adding a virtualmin server shows connection failed constantly. ("Connection to server failed")
running latest Fossbilling on Debian 11, with apache+php-fpm8.1 (in a virtualmin host).

**To Reproduce**
1. Go to Admin Settings -> Hosting Plans and Servers
2. Click on 'New Server'
3. Add any virtualmin server with secure connection (or not, fails for any configuration...)
4. Server is added to server list, but connection test always fails. log : "Connection to server failed 0"
5. When updating server details, clicking on "Update and test connection" also shows the same message.

**Expected behavior**
add virtualmin server, test connection to be working.

**Desktop (please complete the following information):**
 - OS: Debian sid
 - Browser Firefox
 - Version 107.0.1

**Additional context**
had the problem with v0.1.1, updated to 0.2.2 today, same issue. todays logs : 

## ../logs/access_log 
```
xxx.xxx.xxx.xxx - - [08/Dec/2022:10:08:40 +0200] "POST /index.php?_url=/api/admin/servicehosting/server_create HTTP/2.0" 200 506 "https://$admin_url/servicehosting" "$user_agent"
xxx.xxx.xxx.xxx - - [08/Dec/2022:10:08:40 +0200] "GET /admin/servicehosting HTTP/2.0" 200 9486 "https://$admin_url/servicehosting" "$user_agent"
```

## data/log/application.log
```
2022-12-08 10:08:40 INFO (6): Added new hosting server 6
```

## ../logs/access_log
```
xxx.xxx.xxx.xxx - - [08/Dec/2022:10:08:43 +0200] "GET /api/admin/servicehosting/server_test_connection?id=6&CSRFToken=xxxxxxxxxxxxxxxxxxxx HTTP/2.0" 200 550 "https://$admin_url/servicehosting" "$user_agent"
```

## data/log/php_error.log
```
[08-Dec-2022 10:08:43 $timezone] Connection to server failed 0
```

## ../logs/access_log
```
xxx.xxx.xxx.xxx - - [08/Dec/2022:10:09:36 +0200] "GET /admin/servicehosting/server/6 HTTP/2.0" 200 9083 "https://$admin_url/servicehosting" "$user_agent"
```

## ../logs/access_log
```
xxx.xxx.xxx.xxx - - [08/Dec/2022:10:09:39 +0200] "POST /api/admin/servicehosting/server_update HTTP/2.0" 200 509 "https://$admin_url/servicehosting/server/6" "$user_agent"
xxx.xxx.xxx.xxx - - [08/Dec/2022:10:09:39 +0200] "POST /index.php?_url=/api/admin/servicehosting/server_test_connection HTTP/2.0" 200 550 "https://$admin_url/servicehosting/server/6" "$user_agent"
```

## data/log/application.log
```
2022-12-08 10:09:39 INFO (6): Update hosting server 6
```

## data/log/php_error.log
```
[08-Dec-2022 10:09:39 $timezone] Connection to server failed 0
```

**Comment by xinomilo** [comment]
i should also add it's not a network/firewall issue, i have cleared all these out.. all virtualmin servers allowlist each other, port 10000 is open in all virtualmin machines (incoming/outgoing), and i can open virtualmin link from lynx from within fossbilling host/user. lynx asks for the following though : 
- SSL error:The certificate is NOT trusted. The certificate chain uses expired certificate. -Continue? (n) 
- $virtualmin_server cookie: redirect=1 Allow? (Y/N/Always/neVer)
- $virtualmin_server cookie: testing=1 Allow? (Y/N/Always/neVer)

**Comment by BelleNottelling** [comment]
Hi there, @diegoweb and @xinomilo
The Virtualmin server manager was just recently fixed in this pull request: https://github.com/FOSSBilling/FOSSBilling/pull/842
We haven't yet made a new release with this fixed server manager, so you can either install the most recent preview release, or replace the contents of the `library/Server/Manager/Virtualmin.php` file with the one found [here](https://raw.githubusercontent.com/FOSSBilling/FOSSBilling/main/src/library/Server/Manager/Virtualmin.php), which has the updated and fixed server manager.

Have a good one :)

**Comment by xinomilo** [comment]
hey,
connection to a new virtualmin server works fine.. there's a connection failed at first, but after you edit new connection and add webmin port 10000 it works. there's no "connection port" field when adding server, and maybe blank port field doesn't use 10000 by default? 
after adding webmin port to previously added virtualmin servers in fossbilling, those work too.
so "Server connected" messages for all virtualmin servers with this change. nice! :) 

haven't tried yet to order a plan on those and see what happens...

**Comment by jaapmarcus** [comment]
$this->_config['port'] = 10000; 

It should select port 10000 by default

    private function _getUrl()
    {
    	$url = (isset($this->_config['secure']) && $this->_config['secure'])  ? 'https://' : 'http://';
    	$url .= $this->_config['host'] . ':' . $this->_config['port'] . '/virtual-server/remote.cgi';

    	return $url;
    }

**Comment by xerudro** [comment]
On Nginx worked for without any modifications except the billng.conf file. I had to modify a bit the nginx conf for the subdomain but i was able to add the server without any issue. Same i didnt try to buy a plan to test , but i will do it after i get to configure it on both sides: virtualmin and fossbilling. I will come back with a response after all set-ups get done.
