### ISSUE TITLE
[Feature Request] Adding Namesilo registrar

### ISSUE THREAD

**Issue by lamanrasmi** [FOSSBilling/FOSSBilling#563]
Hi, where can i find a working extension for Namesilo registrar?
I tried the Boxbilling Namesilo module here 
https://github.com/boxbilling/extensions/blob/master/bb-library/Registrar/Adapter/Namesilo.php

But unable to make it to work on FOSSbilling.

**Comment by agentmishra** [comment]
it would be a great help

not only that, even namecheap module for fossbilling would be an awesome idea

**Comment by insxa** [comment]
There is also this if it helps https://github.com/vaidas-lungis/Namesilo
