### ISSUE TITLE
[Bug] Database installation bug

### ISSUE THREAD

**Issue by 0x6b-dev** [FOSSBilling/FOSSBilling#57]
https://github.com/boxbilling/boxbilling/issues/1080

**Comment by John-S4** [comment]
Has anyone here managed to reproduce this but, and if so what are the specific database conditions that are causing it?

**Comment by John-S4** [comment]
I've tried with local database, remote database, various PHP versions, and I can't get this error. Yet, it seems as if multiple people had it from the old bb issue, so it must be something quite specific environment related but no idea what. 

If anybody else is experiencing it or can reproduce it then let us know, if not then in a couple of days I am going to go ahead and close this issue for now.

**Comment by John-S4** [comment]
Can not reproduce issue with current release and standard DB setup, so closing the  issue for now.
