### ISSUE TITLE
[Bug] Translations don't work

### ISSUE THREAD

**Issue by roger-net** [FOSSBilling/FOSSBilling#574]
PHP: 8.0
Tested Browsers: Chrome 108 and Firefox 107
Control Panel: KeyHelp
Web Server: Apache

I installed FOSSBilling on my hosting without any problem but the translations don't work and it doesn't matter which one you select which is always shown in English, I translated it into Portuguese and it doesn't work either, even the translations that are already available on FOSSBilling don't work either work. Can anyone give me a suggestion on how to solve it?

**Comment by BelleNottelling** [comment]
We just replaced the back end for translations so the next release should have them fully functional.
If you want you use the latest preview, or wait a few days for us to make a new release.
