### ISSUE TITLE
[Bug] Update currency rates for EUR - "Authentication failed"

### ISSUE THREAD

**Issue by xinomilo** [FOSSBilling/FOSSBilling#580]
**Describe the bug**
tried to refresh currency rate for € -> $ (using Euro as default) and getting an "Authentication failed" error message, no rates applied.
using latest FOSSBilling, problem didn't exist on 0.1.1 for sure (hadn't checked on 0.2.2... )
only 2 currencies : EURO and U$A.
Debian 11 host, apache + php8.1

**To Reproduce**
1. Go to /admin/extension/settings/currency where EUR is default currency (no api key used/needed)
2. Click on 'Update Rates'
3. Error is shown. no rates applied.

**Expected behavior**
rates for EUR -> $ conversion showed.

**php_error.log :**
```
[12-Dec-2022 16:46:32 $timezone] 2 Undefined array key "CSRFToken" /modules/Api/Controller/Client.php 302
[12-Dec-2022 16:46:32 $timezone] An exception has been thrown. Stacktrace:
[12-Dec-2022 16:46:32 $timezone] /modules/Api/Controller/Client.php:317 - __construct(CSRF token invalid., , )
/modules/Api/Controller/Client.php:179 - _checkCSRFToken()
/modules/Api/Controller/Client.php:92 - _apiCall(admin, currency_update_rates, )
/modules/Api/Controller/Client.php:68 - tryCall(admin, currency_update_rates, )
NO_FILE:NO_LINE - get_method(, admin, currency, update_rates)
/library/Box/App.php:217 - invokeArgs(, )
/library/Box/App.php:370 - executeShared(Box\Mod\Api\Controller\Client, get_method, )
/library/Box/App.php:158 - processRequest()
/index.php:30 - run()

[12-Dec-2022 16:46:32 $timezone] An exception has been thrown. Stacktrace:
[12-Dec-2022 16:46:32 $timezone] /modules/Api/Controller/Client.php:209 - __construct(Authentication Failed, , )
/modules/Api/Controller/Client.php:217 - getAuth()
/modules/Api/Controller/Client.php:182 - _tryTokenLogin()
/modules/Api/Controller/Client.php:92 - _apiCall(admin, currency_update_rates, )
/modules/Api/Controller/Client.php:68 - tryCall(admin, currency_update_rates, )
NO_FILE:NO_LINE - get_method(, admin, currency, update_rates)
/library/Box/App.php:217 - invokeArgs(, )
/library/Box/App.php:370 - executeShared(Box\Mod\Api\Controller\Client, get_method, )
/library/Box/App.php:158 - processRequest()
/index.php:30 - run()

[12-Dec-2022 16:46:32 $timezone] Authentication Failed 206
```

**Comment by dspasov** [comment]
Hi, Make sure that you use php version 8.0 with php-fpm support.

**Comment by jaapmarcus** [comment]
`<a class="d-inline-block mx-1 btn bg-light bg-gradient api-link" href="https://demo.fossbilling.org/api/admin/currency/update_rates" data-api-redirect="https://demo.fossbilling.org/admin/extension/settings/currency">
                    <svg class="mb-2 text-secondary" width="24" height="24">
                        <use xlink:href="#refresh"></use>
                    </svg>
                    <span class="d-block text-secondary">Update Rates</span>
                </a>`

Can confirm the issue

**Comment by jaapmarcus** [comment]
See linked PR

**Comment by xinomilo** [comment]
have similar error when trying to delete proxmox server, so i guess this change fixes that as well?
can someone confirm? (if it's not the same, i could file a new bug report...)

`[12-Dec-2022 20:30:59 $timezone] 2 Undefined array key "CSRFToken" /modules/Api/Controller/Client.php 302
[12-Dec-2022 20:30:59 $timezone] An exception has been thrown. Stacktrace:
[12-Dec-2022 20:30:59 $timezone] /modules/Api/Controller/Client.php:317 - __construct(CSRF token invalid., , )
/modules/Api/Controller/Client.php:179 - _checkCSRFToken()
/modules/Api/Controller/Client.php:92 - _apiCall(admin, serviceproxmox_server_delete, )
/modules/Api/Controller/Client.php:68 - tryCall(admin, serviceproxmox_server_delete, )
NO_FILE:NO_LINE - get_method(, admin, serviceproxmox, server_delete)
/library/Box/App.php:217 - invokeArgs(, )
/library/Box/App.php:370 - executeShared(Box\Mod\Api\Controller\Client, get_method, )
/library/Box/App.php:158 - processRequest()
/index.php:30 - run()

[12-Dec-2022 20:30:59 $timezone] An exception has been thrown. Stacktrace:
[12-Dec-2022 20:30:59 $timezone] /modules/Api/Controller/Client.php:209 - __construct(Authentication Failed, , )
/modules/Api/Controller/Client.php:217 - getAuth()
/modules/Api/Controller/Client.php:182 - _tryTokenLogin()
/modules/Api/Controller/Client.php:92 - _apiCall(admin, serviceproxmox_server_delete, )
/modules/Api/Controller/Client.php:68 - tryCall(admin, serviceproxmox_server_delete, )
NO_FILE:NO_LINE - get_method(, admin, serviceproxmox, server_delete)
/library/Box/App.php:217 - invokeArgs(, )
/library/Box/App.php:370 - executeShared(Box\Mod\Api\Controller\Client, get_method, )
/library/Box/App.php:158 - processRequest()
/index.php:30 - run()

[12-Dec-2022 20:30:59 $timezone] Authentication Failed 206
`

thx,

**Comment by xinomilo** [comment]
hm, just checked #581, so probably not..  will send a new report in proxmox module..

btw, response/actions on OP were superfast! thx :)

**Comment by jaapmarcus** [comment]
All modules need some updates
