### ISSUE TITLE
[Feature Request] CSV Input/Export of clients/products/orders

### ISSUE THREAD

**Issue by 0x6b-dev** [FOSSBilling/FOSSBilling#59]
https://github.com/boxbilling/boxbilling/issues/1057

**Comment by BelleNottelling** [comment]
We have the ability to export CSVs as of version 0.4.0.
An import feature doesn't sound very practical, especially in comparison to a proper migration wizard from other existing products which is already on our roadmap for FOSSBilling in the long-term. Closing

**Comment by xinomilo** [comment]
a note, csv import would be practical in the case of trying to migrate from different "non-standard products". 
example case: a modified drupal, wouldn't make it (i suspect...) in a fossbilling migration wizard.. so another "manual" way to migrate data from there, would probably be very helpful/practical.

just 2c.

**Comment by BelleNottelling** [comment]
> a note, csv import would be practical in the case of trying to migrate from different "non-standard products". example case: a modified drupal, wouldn't make it (i suspect...) in a fossbilling migration wizard.. so another "manual" way to migrate data from there, would probably be very helpful/practical.
> 
> just 2c.

I realize this is a rather late response, but: 

Even then, I think it would be more useful for the migration wizard to accept CSV files & provide the functionality to match columns in that CSV to the associated parameter inside of FOSSBilling. That'll cover the use-case you've mentioned, be more flexible, and ensure we keep import / migration functionality separate from everything else & have it all in one place, which is good for organization of the application.
