### ISSUE TITLE
Admin Page Can't Be Accessed[Bug]

### ISSUE THREAD

**Issue by robertzo** [FOSSBilling/FOSSBilling#590]
**Describe the bug**
When I finished installing Foss Billing, I couldn't access the admin page or anything. When I clicked on Admin area, it just redirected me to the main website, that is same with Client area. I cleared my cache, restarted nginx, and did everything the installer said and followed all instructions. None of the links are working either. I also tried deleting the files and database and reinstalling and it still doesn't work.

**To Reproduce**
1. Go to billing.robertzou.ml
2. Click on any link or login or go to admin page
3. Realize that nothing works.

**Expected behavior**
I expected to be able to login to the dashboard and access links.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04, 
 - Web Server: nginx-1.22.1
 - Database: MySQL 8.0.31,
 - PHP 8.1
 - Browser: Brave and Microsoft Edge
 - Version 0.2.3

**Comment by robertzo** [comment]
BTW the OS is Ubuntu for the webserver. The computer OS is windows 10, sorry for the confusion

**Comment by BelleNottelling** [comment]
How was FOSSBilling installed?
And to confirm, all pages show you the dashboard and nothing else?

**Comment by jaapmarcus** [comment]
Probally missing the nginx conf ...

**Comment by xinomilo** [comment]
had the same error when installing to an existing vhost on apache. after creating a new vhost from scratch, problem was gone.
so web server related, imho.

**Comment by evrifaessa** [comment]
Glad it’s resolved. Have a nice day :)

**Comment by jaapmarcus** [comment]
> Glad it’s resolved. Have a nice day :)

It is somebody else

**Comment by evrifaessa** [comment]
Oh, my bad.

**Comment by robertzo** [comment]
I used your nginx.conf generator.

> How was FOSSBilling installed?

I used upload your zip file and extracted it. Then I went to the website and completed the installer (with no errors). I also changed the permissions to the right permissions.

> And to confirm, all pages show you the dashboard and nothing else?

Yes

**Comment by BelleNottelling** [comment]
@jaapmarcus are you able to assist?
I personally don't have experience with nginx,

**Comment by jaapmarcus** [comment]
> I used your nginx.conf generator.
> 
> > How was FOSSBilling installed?
> 
> I used upload your zip file and extracted it. Then I went to the website and completed the installer (with no errors). I also changed the permissions to the right permissions.
> 
> > And to confirm, all pages show you the dashboard and nothing else?
> 
> Yes

Any errors?

When you run nginx -t

**Comment by jaapmarcus** [comment]
I will close the issue no new input is coming back also there was a bug in the example configuration script

**Comment by insxa** [comment]
I use openpanel and administrator sent me modified nginx rewrite rules for fossbilling [https://fossbilling.org/docs/getting-started/installation](url)
Try to replace vhost in cloudpanel for your fossbillign installation with this;
`server {
  listen 80;
  listen [::]:80;
  listen 443 quic;
  listen 443 ssl;
  listen [::]:443 quic;
  listen [::]:443 ssl;
  http2 on;
  http3 off;
  {{ssl_certificate_key}}
  {{ssl_certificate}}
  server_name billing.domen.ovh;
  {{root}}

  {{nginx_access_log}}
  {{nginx_error_log}}

  if ($scheme != "https") {
    rewrite ^ https://$host$request_uri permanent;
  }

  location ~ /.well-known {
    auth_basic off;
    allow all;
  }

  {{settings}}

  location / {
    {{varnish_proxy_pass}}
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_hide_header X-Varnish;
    proxy_redirect off;
    proxy_max_temp_file_size 0;
    proxy_connect_timeout      720;
    proxy_send_timeout         720;
    proxy_read_timeout         720;
    proxy_buffer_size          128k;
    proxy_buffers              4 256k;
    proxy_busy_buffers_size    256k;
    proxy_temp_file_write_size 256k;
  }

  location ~* ^.+\.(css|js|jpg|jpeg|gif|png|ico|gz|svg|svgz|ttf|otf|woff|woff2|eot|mp4|ogg|ogv|webm|webp|zip|swf|map|mjs)$ {
    add_header Access-Control-Allow-Origin "*";
    add_header alt-svc 'h3=":443"; ma=86400';
    expires max;
    access_log off;
  }

  location ~ /\.(ht|svn|git) {
    deny all;
  }

  if (-f $request_filename) {
    break;
  }
}

server {
  listen 8080;
  listen [::]:8080;
  server_name billing.domen.ovh;
  {{root}}

  include /etc/nginx/global_settings;

try_files $uri $uri/ @rewrite;
  index index.php index.html;
  
  location @rewrite {
        rewrite ^/page/(.*)$ /index.php?_url=/custompages/$1;
        rewrite ^/(.*)$ /index.php?_url=/$1;
    }

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_intercept_errors on;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    try_files $uri =404;
    fastcgi_read_timeout 3600;
    fastcgi_send_timeout 3600;
    fastcgi_param HTTPS "on";
    fastcgi_param SERVER_PORT 443;
    fastcgi_pass 127.0.0.1:{{php_fpm_port}};
    fastcgi_param PHP_VALUE "{{php_settings}}";
  }

  if (-f $request_filename) {
    break;
  }
}`

Also when you create site in cloudpanel use php site not wordpress

**Comment by insxa** [comment]
@dnefi yeah no problem, youre welcome, i was also strugling setting It up. But It was all Already in their fossbilling documentation. Best regards
