### ISSUE TITLE
[Bug] WHM createacct fails

### ISSUE THREAD

**Issue by a4aLien** [FOSSBilling/FOSSBilling#607]
**Describe the bug**
When activating a Hosting order, Fossbilling tries to recreate package everytime but won't create the actual user.

**1)** If its the first time and the package doesn't exist, package is created successfully and we see _'error calling action creatacct: "Sorry, "[packagename]" is not a valid pacakge name. at /usr/local/cpanel/Whostmgr/Accounts/Create.pm line 1298.'_

In _/usr/local/cpanel/logs/api_tokens_log_ I see:
```
[2022-12-18 07:34:35 +0000] info [whostmgrd] Host: ['Foss.Billing.IP.Addr'] HTTP Status: ['200'], User: ['root'], Token Name: ['Foss'], Request: ['POST /json-api/listpkgs HTTP/1.1']
[2022-12-18 07:34:35 +0000] info [whostmgrd] Host: ['Foss.Billing.IP.Addr'] HTTP Status: ['200'], User: ['root'], Token Name: ['Foss'], Request: ['POST /json-api/addpkg HTTP/1.1']
[2022-12-18 07:34:36 +0000] info [whostmgrd] Host: ['Foss.Billing.IP.Addr'] HTTP Status: ['200'], User: ['root'], Token Name: ['Foss'], Request: ['POST /json-api/createacct HTTP/1.1']
```

**2)** If package already exists, the next step i.e. createacct doesn't even get called and we see _'error calling action addpkg: The package "root-[packagename]" already exists. If you wish to make changes, please edit the page.'_

In _/usr/local/cpanel/logs/api_tokens_log_ I see: 
```
[2022-12-18 07:50:18 +0000] info [whostmgrd] Host: ['Foss.Billing.IP.Addr'] HTTP Status: ['200'], User: ['root'], Token Name: ['Foss'], Request: ['POST /json-api/listpkgs HTTP/1.1']
[2022-12-18 07:50:19 +0000] info [whostmgrd] Host: ['Foss.Billing.IP.Addr'] HTTP Status: ['200'], User: ['root'], Token Name: ['Foss'], Request: ['POST /json-api/addpkg HTTP/1.1']
```

Everytime I've double checked if the new account is created but it isn't. From _Fossbilling > Orders > 'Order_name' > Service management_, we can see Fossbilling has come up with a randomized username for this order using the domainname, and when trying the _'Sync with Server'_ button, we see _'error calling action accountsummary: "Account does not exist"'_ and in log the following is called: 

`[2022-12-18 07:58:39 +0000] info [whostmgrd] Host: ['Foss.Billing.IP.Addr'] HTTP Status: ['200'], User: ['root'], Token Name: ['Foss'], Request: ['POST /json-api/accountsummary HTTP/1.1']`

**To Reproduce**
1. In Fossbilling, create a package, then a product. Allow customer to place an order for this product. (We disallow automatic activation).
2. Activate the order manually.
3. Error messages is shown in the bottom-left popup on Fossbilling, or is accessible under _Fossbilling > Orders > 'Order_name' > History_.
4. in WHM monitor the creation of package at _Packages > Edit a Package_. To repeat, delete the newly created package.
5. Monitor /usr/local/cpanel/logs/api_tokens_log on WHM server while doing the above.

**Expected behavior**
If package exists or once it has been created, Fossbilling should succeed at creaitng the new user account.

**WHM details:**
 - Version v100.0.11
 - CentOS v7.9.2009 kernel 3.10.0-1160.80.1.el7

**Fossbilling details:**
 - Version 0.2.3
 - Rocky Linux v8.7 kernel 4.18.0-372.9.1.el8

**Comment by jaapmarcus** [comment]
I don't have any issues WHM/Cpanel

Before adding:
https://github.com/FOSSBilling/FOSSBilling/blob/e7f80c141586bfdef4b7120d0e261cb1d7492337/src/library/Server/Manager/Whm.php#L301-L341

We should check if the package exsits

**Comment by jaapmarcus** [comment]
I assume you create the accounts on the root user:

```
$name = $package->getName();
        if($this->_config['username'] != 'root') {
            $name = $this->_config['username'].'_'.$name;
        }
```

Can you check the Cpanel package name?

**Comment by a4aLien** [comment]
Hi @jaapmarcus

The package does exist and its root_packagename. But it doesn't go beyond that so won't create the actual user account.

**Comment by jaapmarcus** [comment]
It looks like the have changed something

**Comment by jaapmarcus** [comment]
https://github.com/FOSSBilling/FOSSBilling/pull/628 

Please check if this works

**Comment by a4aLien** [comment]
@jaapmarcus 

Yes, its creating accounts now. 
I also tested with a new packagename. It created the new package and the account. 

Thanks!

**Comment by a4aLien** [comment]
Slightly offtopic, but the dummy orders I was creating can't be deleted since it fails at 'removeacct' as the users don't exist since the setup failed earlier.

The notification says 'WHM server response error calling action removeacct: "Permission Denied"' but only on those orders which didn't get their users created (failed setup).

Would their be any other way of clearing them besides removing them from the DB? Should I open a new report for this?

**Comment by jaapmarcus** [comment]
I noticed the same thing.    Please create a new Bug report
