### ISSUE TITLE
[Bug] Logged In User is defaulting to System Cron Jobs for all users

### ISSUE THREAD

**Issue by 0x6b-dev** [FOSSBilling/FOSSBilling#61]
https://github.com/boxbilling/boxbilling/issues/1027

**Comment by BelleNottelling** [comment]
So, I haven't seen this issue on my installation in awhile.. I suspect one of the many bugfixes we have made fixed it.
Anyone else seen it happen recently?

**Comment by BelleNottelling** [comment]
I haven't seen this issue crop up in months. I think one of our many bug fixes have resolved it.
If someone does end up reproducing it, we can reopen this or create a new issue
