### ISSUE TITLE
[Bug] Legacy flag library

### ISSUE THREAD

**Issue by notbasetwo** [FOSSBilling/FOSSBilling#614]
The administration interface uses famfamfam's very old flag's icon pack. A couple of flags of nations have changed since this pack was released (e.g. Libya, Malawi, Mauritania).

This isn't a major issue, but this may become an even larger issue going forward (the world is forever changing, flags change fairly often). Flags are national identities and having old/wrong flags could be offensive to some people.

**Comment by John-S4** [comment]
I'm currently building a new theme, and want to replace the flag icons that were used in older ones. 

@notbasetwo do you have a suggestion of a more up to date option?

**Comment by jaapmarcus** [comment]
Font awesome flags?

**Comment by John-S4** [comment]
> https://flagicons.lipis.dev

This looks pretty good to me, will give it a go.

**Comment by admdly** [comment]
I wonder if this is now resolved with #853?

**Comment by BelleNottelling** [comment]
> I wonder if this is now resolved with #853?

Not for huraga, just the admin panel

**Comment by admdly** [comment]
> > I wonder if this is now resolved with #853?
> 
> Not for huraga, just the admin panel

Noted. I just saw

> administration interface

in the original report.

**Comment by BelleNottelling** [comment]
> > > I wonder if this is now resolved with #853?
> > 
> > Not for huraga, just the admin panel
> 
> Noted. I just saw
> 
> > administration interface
> 
> in the original report.

Ah, I didn't even see that. Then yes, I guess this is completely, but Huraga still has ancient flag icons as well

**Comment by BelleNottelling** [comment]
This is now fully complete as of 0.6.0
