### ISSUE TITLE
[Bug] Incorrect password attempts displayed in plain text in error log

### ISSUE THREAD

**Issue by ecrocombe** [FOSSBilling/FOSSBilling#617]
**Describe the bug**
When attempting to login to the admin page, when an error occurs the password is stored in the logs in plain text.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install FOSSBilling 0.2.4 stable
2. Setup web server for a FQDM but browse to the admin interface using IP (not sure this is required).
3. Attempt to login with incorrect password and receive an "Unauthorized" model error.
4. See admin username, password and client IP stored in plain text in the log file @ data/log/php_error.log

**Expected behaviour**
Password not to be visible, or at least starred *********

**Screenshots**
[21-Dec-2022 00:52:35 UTC] Check your login details 403
[21-Dec-2022 00:53:36 UTC] An exception has been thrown. Stacktrace:
[21-Dec-2022 00:53:36 UTC] /modules/Staff/Service.php:53 - __construct(Check your login details, , )
/modules/Staff/Api/Guest.php:98 - login(username@example.com, **PASSWORD IN PLAIN TEXT**, CLIENT_IP)
/library/Api/Handler.php:116 - login()
/modules/Api/Controller/Client.php:186 - __call(staff_login, )
/modules/Api/Controller/Client.php:92 - _apiCall(guest, staff_login, )
/modules/Api/Controller/Client.php:83 - tryCall(guest, staff_login, )
NO_FILE:NO_LINE - post_method(, guest, staff, login)
/library/Box/App.php:217 - invokeArgs(, )
/library/Box/App.php:370 - executeShared(Box\Mod\Api\Controller\Client, post_method, )
/library/Box/App.php:158 - processRequest()
/index.php:30 - run()

**Additional context**
I understand that in the steps above I am using an incorrect password, but what if that incorrect password is just 1 char off the correct password, or what if the correct password is logged when a different error occurs?

I believe that in no circumstance should an admin password be saved to a file in plain text.

**Comment by jaapmarcus** [comment]
Can confirm the issue. 

@John-S4  if you enter the correct password but a wrong email it still logs the correct password. But not the correct combination. 

Even then we have addressed this issue via PR #618

**Comment by John-S4** [comment]
Please ensure that you have debug mode set to off and the issue should have been solved by #618
