### ISSUE TITLE
[Feature Request] BTCPay integration

### ISSUE THREAD

**Issue by thefeli73** [FOSSBilling/FOSSBilling#622]
**Is your feature request related to a problem? Please describe.**
Not in general. My problem is there is no existing solution to connect a payment processor which handles BTC/LN payments from a seperate LN node.

**Describe the solution you'd like**
A plugin connect FOSSBilling to my BTCPay server, similar to how i can connect it to WooCommerce

**Describe alternatives you've considered**
There is a BitcartCC extension already, but that does not suit my needs and i do not plan on using BitcartCC. BTCPay server is much more fleshed out and tried and tested, and has a larger community backing it. Also, its lightning implementation is more versatile and robust. 

**Additional context**
BTCPay server already has integrations for Woocommerce (which is also php), shopify, magneto, prestashop, opencart, drupal, zapier, shopware and virtuemart, so it might be possible to port over one of those integrations? if not, BTCPay has a very nice API. Unfortunatly im not that familiar with FOSSBilling so no clue how to do it myself

**Comment by MrNaif2018** [comment]
Hi! Please let me know what exactly in BitcartCC isn't polished, and it will get polished :D
Seriously, we're just as stable as them
Or is it because we use built-in electrum LN node and you want connect your external one?
Recently I saw someone connecting c-lightning too, will get a guide
But in general if you really think this should be done I guess btcpay devs/some volunteers could create a plugin and not fossbilling devs themselves (:

**Comment by thefeli73** [comment]
> Hi! Please let me know what exactly in BitcartCC isn't polished, and it will get polished :D Seriously, we're just as stable as them Or is it because we use built-in electrum LN node and you want connect your external one? Recently I saw someone connecting c-lightning too, will get a guide But in general if you really think this should be done I guess btcpay devs/some volunteers could create a plugin and not fossbilling devs themselves (:

I did not mean to diss BitcartCC, im sure its great, but i did not like the UI/UX from what little i saw on the website and demo. As for Lightning, i really did not like the electrum implementation back when i tried it last year, and CLN (formerly C-lightning) is also a nogo for me. The payment processor needs to be able to plug into whatever lightning node i'm running. The fact that there isnt already a guide/option for connecting to a node is what i mean by unpolished, BTCPay is just simply more mature in my opinion.
That being said, i only discovered BitcartCC today, so let me know if i'm just missing something

**Comment by MrNaif2018** [comment]
Well, simply that most users were satisfied with existing electrum implementation. I think it might be possible for me to allow connecting to remote lightning node for LN-only payments. If enough users want this it can be added

I've also asked electrum devs to see if an easy migration is possible
If you're interested, you can enter our community chats and we can discuss it further and it can get to implementation

P.S. As about the UI/UX, if there's something we can improve, let me know. In my opinion being able to interactively edit items with dialogs is way easier than loading a new page and jumping back and forth for each new invoice, especially considering that btcpay can work with only 1 wallet in a store while we allow unlimited number of wallets connected to the store, even of same currency (you can even rotate the wallets on a random basis). Ah and also, if you were surprised by some graphics on main page of store.bitcartcc.com, it was me testing a plugin, we've added plugins support just yesterday, it's not in core bitcart (:

**Comment by MrNaif2018** [comment]
Hi @thefeli73! Our plugins support is pretty robust now, and it should be pretty easy and fast to create a plugin to connect your node for lightning payments not based on electrum implementation
I can code it in a day I believe (:
I can do it if you join our communities and help test it (i.e. I would need node URL or similar to test if it's working)

**Comment by WaxySteelWorm** [comment]
We would be willing to donate 250k sats to get this implemented.

**Comment by MrNaif2018** [comment]
Do you also need to connect to already running LN node? If so, which implementation? Please let me know and we can test and add it to lightning network + plugin so that btcpay is not needed (:

**Comment by WaxySteelWorm** [comment]
> Do you also need to connect to already running LN node? If so, which implementation? Please let me know and we can test and add it to lightning network + plugin so that btcpay is not needed (:

We would like to route everything through BTCPay API. We want to be able to accept BTC,XMR, and potentially CLND.

**Comment by MrNaif2018** [comment]
I see. If you want you can contact me via email chuff184@gmail.com or telegram MrNaif_bel (preferred) and we can discuss the addition of CLN support. Just that ideally I need a node to connect to to test it. As for XMR for example, in our case it works better, allowing to accept payments on many wallets on one instance in case you need it

**Comment by BelleNottelling** [comment]
Closing to make one larger issue to track the payment gateways that have been requested
