### ISSUE TITLE
[Bug] Error 103 when attemp to migrate to fossbillling from boxbilling

### ISSUE THREAD

**Issue by 123ysys** [FOSSBilling/FOSSBilling#627]
**Describe the bug**
After I followed the steps in [https://fossbilling.org/docs/getting-started/migrate-from-boxbilling](url) to migrate to fossbillling from boxbilling, when I finished the step of "upload and extract the FOSSBilling files" and access my billing address, it says that the composer file is missing, and then returned 502 HTTP error when I second time to access it. However, the composer file exists. 
**To Reproduce**
1. follow the steps of "migrate to fossbillling from boxbilling"
2. Go to my billing system URL
3. See the error which shows"composer file is missing, if you downloaded boxbilling from GitHub, it shouldn't happen"
4. See 502 error on the second time to my billing system URL

**Expected behavior**
I should be able to access my admin page of FOSSbilling.

[**Screenshots**]
[![fossbillling](https://user-images.githubusercontent.com/27964272/209435847-30fec63f-7f32-464d-a881-cc6176053476.PNG)](url)

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Browser [Chrome]
 - Version [the latest]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BelleNottelling** [comment]
Did you download a release or clone it from GitHub?
This is expected if you did not download a release.

**Comment by BelleNottelling** [comment]
Also, are you sure you overwrote the BoxBilling files?
This error message appears to be from BoxBilling & not FOSSBilling

**Comment by 123ysys** [comment]
> Did you download a release or clone it from GitHub? This is expected if you did not download a release.

Yes. I downloaded boxbilling from github.

**Comment by 123ysys** [comment]
> Also, are you sure you overwrote the BoxBilling files? This error message appears to be from BoxBilling & not FOSSBilling

No. I think I overwrote the FOSSbillling files with the original Boxbilling files and deleted the Boxbilling folders, following the steps of [https://fossbilling.org/docs/getting-started/migrate-from-boxbilling](https://github.com/FOSSBilling/FOSSBilling/issues/url)

**Comment by BelleNottelling** [comment]
> > Also, are you sure you overwrote the BoxBilling files? This error message appears to be from BoxBilling & not FOSSBilling
> 
> No. I think I overwrote the FOSSbillling files with the original Boxbilling files and deleted the Boxbilling folders, following the steps of [https://fossbilling.org/docs/getting-started/migrate-from-boxbilling](https://github.com/FOSSBilling/FOSSBilling/issues/url)

That would be opposite from the actual steps

**Comment by 123ysys** [comment]
> > > Also, are you sure you overwrote the BoxBilling files? This error message appears to be from BoxBilling & not FOSSBilling
> > 
> > 
> > No. I think I overwrote the FOSSbillling files with the original Boxbilling files and deleted the Boxbilling folders, following the steps of [https://fossbilling.org/docs/getting-started/migrate-from-boxbilling](https://github.com/FOSSBilling/FOSSBilling/issues/url)
> 
> That would be opposite from the actual steps

Opps... I will correct my steps but by the way, I think the documents needed to be updated, doesn't it?

**Comment by BelleNottelling** [comment]
> 

Yes, they are a bit outdated. I'll try to get them updated in the near future
