### ISSUE TITLE
Mercado Pago for Latin America  [Feature Request]

### ISSUE THREAD

**Issue by heberq1978** [FOSSBilling/FOSSBilling#641]
It would be possible to add Mercado Pago as an alternative for Latin America, as it is the best option for accepting several payment methods internally.

https://www.mercadopago.com.br/developers/en

**Comment by roger-net** [comment]
It would be really good.

**Comment by robvieiradev** [comment]
If there is any documentation or guide on the development of payment gateways, I myself have already made a plugin to integrate Mercado Pago with API's for Wordpress. Following some example for FOSS I could program an extension...

**Comment by heberq1978** [comment]
Hello my friends,

Any news about the Mercado Pago gateway?

Thanks
Heber

**Comment by BelleNottelling** [comment]
Closing to make one larger issue to track the payment gateways that have been requested
