### ISSUE TITLE
[Bug] Manage Email Templates Update Fails

### ISSUE THREAD

**Issue by DataLores** [FOSSBilling/FOSSBilling#643]
**Describe the bug**
Making an update to the content of a template results in an "Authentication Failed (201)" message.

**To Reproduce**
1. Go to Settings, Email
2. Click on a template of your choosing and update the email messag body.
3. Click update and see error.

**Expected behavior**
Template updates without error.

**Screenshots**
Notice the following POST failure in browser console:
index.php?_url=/api/admin/email/template_update 401

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Iridium/Chrome
 - Version 04.2022

**Additional context**
FOSSBilling: 0.2.6
PHP: 8.0.25

**Comment by DataLores** [comment]
Seeing same failure in creating a new client page. Checking upgrade was kosher.

**Comment by DataLores** [comment]
Confirmed with CSRFPrevention set back to false the issues do not occur.

**Comment by DataLores** [comment]
@BelleNottelling is this reproducible for you, and if so, is there a standard CSRF include missing from this and several other admin pages?

**Comment by jaapmarcus** [comment]
Update went fine but reset returned:

Email template mod_client_password_reset_request.html, 'CSRFToken': CSRFToken was not found (9999)

**Comment by jaapmarcus** [comment]
Please check if
https://github.com/FOSSBilling/FOSSBilling/pull/652

Solves the issue

**Comment by DataLores** [comment]
After PR patch...

With CSRF enabled:

Reset button: Unknown API call admin/email/template_reset?code=mod_client_password_reset_approve (879)
Update button: Authentication failed (201)

With CSRF disabled:

Reset button: Unknown API call admin/email/template_reset?code=mod_client_password_reset_approve (879)
Update button: Template updated

**Comment by jaapmarcus** [comment]
> After PR patch...
> 
> With CSRF enabled:
> 
> Reset button: Unknown API call admin/email/template_reset?code=mod_client_password_reset_approve (879) Update button: Authentication failed (201)

It looks like it didn't update it correctly.  Can you check in the html code the href attribute? 

It looks like it not updated...  

> 
> With CSRF disabled:
> 
> Reset button: Unknown API call admin/email/template_reset?code=mod_client_password_reset_approve (879) Update button: Template updated

**Comment by DataLores** [comment]
Recopied and tested the below with same result. Here is my patch:

 line 83: modules/Email/html_admin/mod_email_template.html.twig
                            href="{{ 'api/admin/email/template_reset'|link({'code' : template.action_code , 'CSRFToken': CSRFToken })}}"

**Comment by jaapmarcus** [comment]
And the generated html code?

**Comment by DataLores** [comment]
I only have .twig entries in my install under modules/Email/html_admin/, which may be the problem.

What is needed to regenerate all .html files, and where can that be run? I think we also should make a note on the upgrade instructions in FOSS documentation if its not an automated step.

**Comment by evrifaessa** [comment]
In v0.2.6, updating seems fine. It doesn't return any errors and actually does update the template. But as Jaap said, the reset button won't work. After Jaap's patch (#652), the reset button also works fine.

Does `/themes/admin_default/html/mod_email_template.html.twig` exist?

**Comment by jaapmarcus** [comment]
> I only have .twig entries in my install under modules/Email/html_admin/, which may be the problem.
> 
> What is needed to regenerate all .html files, and where can that be run? I think we also should make a note on the upgrade instructions in FOSS documentation if its not an automated step.

If you open the web page and click copy link / or you web developers tools you are able to see the generated link

It should look like this:
```
<a class="btn btn-danger w-25 api-link" href="https://xxxxxx/api/admin/email/template_reset?code=mod_client_confirm.html&amp;CSRFToken=bd16705341eadffc5cb44ae7e9864401" data-api-confirm="Are you sure?" data-api-reload="1">
                            Reset
                        </a>
```

**Comment by DataLores** [comment]
Ran an rm -rf mod* under themes/admin_default/html and now everything is working (both this patch and the originally reported bug with various update buttons).

I don't quite understand how this does/doesn't work. From an upgrade perspective, there probably needs to be at a minimum user documentation that specifies cleaning up and removing old template files, as it definitely honors the template overrides in themes/admin_default/html first. When the module files were deleted and functionality retested, everything works, but I notice the files are not regenerated under this path.

**Comment by jaapmarcus** [comment]
System updates via our the installer should clear the cache folder how ever if it done manually currently not

**Comment by evrifaessa** [comment]
> System updates via our the installer should clear the cache folder how ever if it done manually currently not

This isn't about caching. It's about us moving module templates under the modules' own directories.

>  From an upgrade perspective, there probably needs to be at a minimum user documentation that specifies cleaning up and removing old template files, as it definitely honors the template overrides in themes/admin_default/html first.

Yes, I agree on that. I think we should do that with the next possible release.

**Comment by DataLores** [comment]
So is it fair then that themes/admin_default/html has a higher order precedence for same-named module template files? I.e. twig will load from here first, and if not present it falls back to the module specific folder structure?

**Comment by evrifaessa** [comment]
> So is it fair then that themes/admin_default/html has a higher order precedence for same-named module template files? I.e. twig will load from here first, and if not present it falls back to the module specific folder structure?

Yes. As far as I know, that is correct. This way, it allows the users to overwrite module template files without having them overwritten with each upgrade.
