### ISSUE TITLE
[Bug] Batch Delete Fails in Admin CP

### ISSUE THREAD

**Issue by DataLores** [FOSSBilling/FOSSBilling#644]
**Describe the bug**
Attempts to batch delete orders from the orders page results in nothing happening.

**To Reproduce**
1. Go to Orders
2. Click on at least two checkboxes next to the entry to delete
3. Scroll down and click delete selected.

**Expected behavior**
Deletion to occur

**Screenshots**
From the browser console:

fossbilling-bundle.min.js?v=0.2.6:1 This theme or module is using a deprecated method. Please update it to use the new API wrapper instead. Documentation: https://fossbilling.org/docs/api/javascript
post @ fossbilling-bundle.min.js?v=0.2.6:1
(anonymous) @ index.php?_url=/admin/order:1694
(anonymous) @ fossbilling-bundle.min.js?v=0.2.6:1
(anonymous) @ fossbilling-bundle.min.js?v=0.2.6:1
dispatch @ fossbilling-bundle.min.js?v=0.2.6:1
r @ fossbilling-bundle.min.js?v=0.2.6:1
API.js:162          POST client/index.php?_url=/api/admin/order/batch_delete 500
makeRequest @ API.js:162
post @ fossbilling-bundle.min.js?v=0.2.6:1
(anonymous) @ index.php?_url=/admin/order:1694
(anonymous) @ fossbilling-bundle.min.js?v=0.2.6:1
(anonymous) @ fossbilling-bundle.min.js?v=0.2.6:1
dispatch @ fossbilling-bundle.min.js?v=0.2.6:1
r @ fossbilling-bundle.min.js?v=0.2.6:1
VM247:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at API.js:171:29

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Iridium/Chrome
 - Version 04.2022

**Additional context**
FOSSBilling: 0.2.6
PHP: 8.0.25

**Comment by DataLores** [comment]
May be related to CSRF, other mutating actions on other pages show similar behaviors with 500s from JS wrapper.

**Comment by evrifaessa** [comment]
Can you try recording the outgoing request using the "network" tab in the developer console? The response should be helpful.

**Comment by DataLores** [comment]
Since toggling CSRF off and back on again, I've been unable to reproduce this now in either mode. Nothing else changed server side. Am still able to reproduce https://github.com/FOSSBilling/FOSSBilling/issues/643 consistently before and after feature flag change.

**Comment by jaapmarcus** [comment]
Can't replicate this bug either. 

It looks like something has been patched will close the issue for now. If you are able to replicate please reopen it again

**Comment by jaapmarcus** [comment]
Issue is still present.

**Comment by jaapmarcus** [comment]
Nevermind other PR caused the issue
