### ISSUE TITLE
[Bug] Payment Gateway settings not saving/updating

### ISSUE THREAD

**Issue by nathanmay** [FOSSBilling/FOSSBilling#659]
**Describe the bug**
When adding a payment gateway the configuration is not saved, no error messages.

**To Reproduce**
1. Go to Configuration->Payment Gateways
2. Add a new one such as Paypal - adjust settings and enter Paypal Email.
3. Click 'Update' 
4. Get a toast message stating "Gateway updated" - No error produced. However, navigating away to another page and them back to the Paypal payment gateway settings and the Email field is now blank and no config in the database.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Additional context**
Radio buttons (enables, one-time payments, subscriptions, etc), Gateway Title all save. Only seems to affect the configuration fields for that payment method. Tested with Paypal Email and also same issue with stripe - Doesn't save the API fields for Stripe but all other fields save.

**Comment by jaapmarcus** [comment]
See https://github.com/FOSSBilling/FOSSBilling/issues/654

It is related it should be solved after we merge the patch

**Comment by John-S4** [comment]
Just updated two installs to 0.2.7 and can confirm that this issue was resolved
