### ISSUE TITLE
[Bug] Custom product upgrades are not saved

### ISSUE THREAD

**Issue by bidikov** [FOSSBilling/FOSSBilling#665]
**Describe the bug**
I have 2 custom products (VM and Custom VM). the general idea is that if the client needs more to use the upgrade option for the custom VM product (where i have addon defined althought they can only take one quantity of addon)

When i Update the product page i mark the product which is a available update, looks saved but when i return it seems it's not save (this can be connected to the JSON issue which awas resolved with the latest release)

**Expected behavior**
Saving of Upgrades needs to work.

**Screenshots**
https://prnt.sc/MDfXoiRC_QKl
https://prnt.sc/4LX1XzUOHyAq

**Additional context**
Now sure if Custom products are the right way if we do not need to provision the VM (as using some plugin for VM since we provision Vmware manualy)

**Comment by jaapmarcus** [comment]
Can confirm the error
Empty string:
`{"CSRFToken":"383054e8dac741c9e4333c97e4611c2a","upgrades":"","id":"1"}`

All option selected:
`{"CSRFToken":"383054e8dac741c9e4333c97e4611c2a","upgrades":"","upgrades[]":"4","id":"1"}
`

**Comment by bidikov** [comment]
If i'm not seeing things wrong - this can be closed as soon as merge of: https://github.com/FOSSBilling/FOSSBilling/pull/685 is complete :)
