### ISSUE TITLE
Modal window is not displayed correctly [Bug]

### ISSUE THREAD

**Issue by roger-net** [FOSSBilling/FOSSBilling#666]
PHP: 8.1
Version: 0.2.7

In the custom form option, when creating a form, the modal window is not shown correctly, as shown in the attached images. The modal window is below the menu.

![Custom-form-builder-Novacast](https://user-images.githubusercontent.com/58113324/210627194-81d51a85-f514-46f6-9a22-75532ea2d884.png)
![Custom-form-builder-Novacast 2](https://user-images.githubusercontent.com/58113324/210627213-1d480821-3f12-4408-985b-01d86451b3a1.png)
![Custom-form-builder-Novacast 3](https://user-images.githubusercontent.com/58113324/210627232-ead61344-1cb1-41bd-b21d-d6ee7f7cb1a2.png)

**Comment by BelleNottelling** [comment]
So.. the issue is styling, right? 

That module is super old and effectively needs a rewrite

**Comment by roger-net** [comment]
> So.. the issue is styling, right?
> 
> That module is super old and effectively needs a rewrite

I managed to solve it, on line 37 of the file "mod_formbuilder_settings.html.twig" I changed the command "z-index:1002" to 2000 and it started to work correctly.

![Capturar](https://user-images.githubusercontent.com/58113324/210895192-4a893d34-0dc3-4f47-b8c1-b81f8f4eee95.JPG)
