### ISSUE TITLE
[Bug] Forward and backslashes are being mixed up when hosted on Windows

### ISSUE THREAD

**Issue by rubenuijtdewilligen** [FOSSBilling/FOSSBilling#670]
**Description**
When hosting FOSSBilling on Windows using Apache via Xampp, templates can't be found because forward and backslashes are both used like in "Unable to find template "page_name.html.twig" (looked into: C:\xampp\htdocs\fossbilling-dev/themes\theme-name\html)". This is probably because Linux as the hosting OS is assumed and Linux uses forward slashes, while Windows uses backslashes for paths.

**To reproduce**
Steps to reproduce the behaviour:
1. Install FOSSBilling on Windows using Apache via Xampp
2. Create a theme where a file is missing
3. Make sure debug mode is enabled
4. Send a GET request to the url that should be showing this theme file

**Expected behaviour**
Only forward slashes should be used on Linux and only backslashes should be used on WINNT.

**Screenshot**
[https://i.imgur.com/x9jaLjU.png](https://i.imgur.com/x9jaLjU.png)

**Comment by John-S4** [comment]
Resolved by #671

**Comment by rubenuijtdewilligen** [comment]
I have just found that there are more places where this happens.

![image](https://user-images.githubusercontent.com/39881862/211201563-40f02b76-259b-4f2f-81a6-7eb650df6ba3.png)

**Comment by evrifaessa** [comment]
I think

**Comment by jaapmarcus** [comment]
https://github.com/FOSSBilling/FOSSBilling/blob/main/src/install/install.php#L85

It is the same

**Comment by jaapmarcus** [comment]
No if is is only the installer that is the issue we should only update it there... For access via the web / is still good enough

**Comment by jaapmarcus** [comment]
https://github.com/FOSSBilling/FOSSBilling/pull/675

Should work fine can't test ... And it is to much work to setup a vm for it...
