### ISSUE TITLE
[Typo] "Theme does not exists"

### ISSUE THREAD

**Issue by rubenuijtdewilligen** [FOSSBilling/FOSSBilling#677]
When a theme is selected and then removed, a Box_Exception shows up to tell the user that the theme does not exist. There is a typo here, because it says "Theme :theme does not exists" instead of "Theme :theme does not exist"

![image](https://user-images.githubusercontent.com/39881862/211218374-93a4ccb3-6ae6-43d9-9e12-f0e547f2d113.png)

**Comment by rubenuijtdewilligen** [comment]
Opened a [PR](https://github.com/FOSSBilling/FOSSBilling/pull/678) to fix.

**Comment by jaapmarcus** [comment]
No need to create a bug report if you can fix it with a PR :)
