### ISSUE TITLE
[Feature Request] KeyHelp panel API

### ISSUE THREAD

**Issue by syltmedia** [FOSSBilling/FOSSBilling#684]
I know that my code the not the cleanest but it is working:

https://github.com/syltmedia/FOSSBilling_KeyHelp

**Comment by jaapmarcus** [comment]
Please create a fork of Fossbilling, add the files to the correct location and submit a PR :)

**Comment by evrifaessa** [comment]
> Please create a fork of Fossbilling, add the files to the correct location and submit a PR :)

Please don’t. Any third party implementation that won’t be maintained by us in the future should have its own repository.

We can list it in the extension store once it receives support for external adapters.

**Comment by syltmedia** [comment]
So I leave it there and submit it to the extension store when the time is come...

**Comment by John-S4** [comment]
If it is working then it should be added to the 'Working Extenstions' list in docs. 

https://fossbilling.org/docs/extensions

**Comment by syltmedia** [comment]
Still some points to do on my list

**Comment by syltmedia** [comment]
New release: https://github.com/syltmedia/FOSSBilling_KeyHelp/releases/tag/0.0.2

**Changelog:**

- Adding getCURL()
- Replace the tabs with spaces
- Find out that synchronizeAccount() are not working
- Changed the readme - Because the hosting plan name must be the same in KeyHelp as in FOSSBilling

**Comment by Mostafa96-cybersecurity** [comment]
This is The package KeyHelp API Fossbilling 

https://github.com/Mostafa96-cybersecurity/fossbilling-keyhelp-server-manager
