### ISSUE TITLE
[Feature Request] l10n: implement value-based countable translations

### ISSUE THREAD

**Issue by anatolinicolae** [FOSSBilling/FOSSBilling#699]
Current localization implementation can be tweaked in order to provider better translation support for countable strings.

This has little to no impact on most strings, but provides better translation experience as well as clearer information to the reader.

In English it does make sense to use `Every :number week(s)` as it makes sense for both 1 and more as in `Every 1 week(s)` and `Every 2 week(s)`. Meanwhile, it sounds weird in other languages such as Italian where the translation would be along the lines of `Ogni :number settimana/e` therefore being `Ogni 1 settimana/e` and `Ogni 2 settimana/e`. While `Ogni 2 settimane` is perfectly fine, in Italian "weekly" loses the number indication in the translation becoming `Ogni settimana` and not `Ogni 1 settimana`.

The solution has been identified in the use of `ngettext` method to provide value-based translations for singular and plural versions.

```php
$parser->ngettext(
    'Every week', // singular translation
    'Every %d weeks', // plural translation
    2 // items count
)
```

[Translator API usage](https://github.com/phpmyadmin/motranslator#translator-api-usage)
[Implementation example](https://github.com/phpmyadmin/motranslator/blob/91227d4aa60224420cba69f1d5b2e565f6625944/tests/MoFilesTest.php#L41)

**Comment by jaapmarcus** [comment]
It is allready implemented in https://github.com/phpmyadmin/motranslator/
