### ISSUE TITLE
Set up a demo

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#7]
But fix the module first

**Comment by Komodroid** [comment]
I could set up a demo on my VPS if you want....

**Comment by jaapmarcus** [comment]
Ideally you want to set up an "job" that resets every hour a docker image with the last version

**Comment by evrifaessa** [comment]
> Ideally you want to set up an "job" that resets every hour a docker image with the last version

Yup, we can either set up a demo with freer permissions and reset it hourly or limit settings and don't need to reset it.

**Comment by BelleNottelling** [comment]
I fixed the demo module btw:
https://github.com/FOSSBilling/FOSSBilling/tree/DemoModule

I would say a demo running that + a hourly or so reset with a docker image would work, but..
I also feel we should wait until we have made more significant progress (like, the laravel port / migration)

**Comment by jaapmarcus** [comment]
It doesn't make sense to do it right now to use it. 

So wait until closer too final release

**Comment by evrifaessa** [comment]
The demo module is now in its own repository: https://github.com/FOSSBilling/demo
I've also added instructions and general guidelines there.

**Comment by BelleNottelling** [comment]
We've had a demo up for awhile now 
https://demo.fossbilling.org/
