### ISSUE TITLE
[Feature Request] Database prefixes

### ISSUE THREAD

**Issue by 0x6b-dev** [FOSSBilling/FOSSBilling#70]
https://github.com/boxbilling/boxbilling/issues/830

**Comment by John-S4** [comment]
This is currently on the roadmap for the 0.0.1 release, and I'm wondering if it should be. 

It's unclear from the discussion in the old bb issue whether these breaking changes that should be pushed back to a more significant release, or is it something that can be done now and then carried forward?

@BelleNottelling @HunterNyan thoughts?

**Comment by John-S4** [comment]
Moved to 0.0.2

**Comment by evrifaessa** [comment]
It might be a little troublesome to achieve this without rewriting our installer. Right now, it imports a full database dump and isn't very flexible in terms of programmability.

**Comment by evrifaessa** [comment]
It also will break compatibility with many of our modules. Right now, before a new major release, should be the best time to do it.

**Comment by John-S4** [comment]
> It also will break compatibility with many of our modules. Right now, before a new major release, should be the best time to do it.

That's a fair point, I'm just a bit concerned that there are going to be a huge jump in the number of basic support questions from people who find that whatever module stops working. 

On the other hand if the default prefix stays as it is, and we add the option to configure a custom one at install, with a disclaimer that doing so may break any modules that have not been updated, then I don't see it being a huge problem.

**Comment by jaapmarcus** [comment]
I would personally wait until Lara release

**Comment by evrifaessa** [comment]
> I would personally wait until Lara release

No more Lara. If we're planning to do this, now is the best time.

**Comment by jaapmarcus** [comment]
Fine forme...

**Comment by John-S4** [comment]
I think it would be a nice thing to implement, and isn't overly breaking as per my comment above

**Comment by evrifaessa** [comment]
> I think it would be a nice thing to implement, and isn't overly breaking as per my comment above

Yeah. Especially considering there aren't really that many custom modules. The core ones would be taken care of by us.

**Comment by BelleNottelling** [comment]
The installation process will need to be completely rewritten, the update patch system will need to be updated to use it, and all the internal modules will need to be adjusted.

And honestly, I'm questioning how much of a security enhancement this actually is? I mean, if your system is compromised enough that they have any kind of access to that database, I fail to see why the naming of the internal tables would add any additional protection.

**Comment by John-S4** [comment]
> And honestly, I'm questioning how much of a security enhancement this actually is? I mean, if your system is compromised enough that they have any kind of access to that database, I fail to see why the naming of the internal tables would add any additional protection.

I'd tend to completely agree with you, but you will find that a lot of people really do still believe in the good old 'security through obscurity' idea, and will want to do this for that reason. 

Outside of that there are probably some other, admittedly reasonably obscure, use cases where you might want to have a different DB prefix for some reason.

I don't think it is in any way urgent or of massively high priority, and if it actually requires substantial reworking of things then maybe it really isn't worth the effort at all at the moment, but I can see valid reasons for it.

**Comment by admdly** [comment]
This is an interesting discussion and there are valid reasons for a prefix such as a shared table namespaces, but realistically this isn't an issue unless limited to a single database, and providing modules database access with their own namespace. 

Otherwise, the security aspect is frankly nonsense even with a security through obscurity mindset as access to tables, including names, is dependent on greater access.

That said, I'm not opposed to a prefix - provided the above is considered, and the benefits considered.

**Comment by admdly** [comment]
I'll add that prefixes are primarily a legacy thing, from experience, but if there is a genuine concern it is not the end of world to support.

**Comment by BelleNottelling** [comment]
I'm going to close this. We all seem to be at best iffy on the actual benefit of implementing this, while all agreeing it introduces a lot of currently unneeded complexity. If needed, we can revisit this later down the line once we've modernized the installation and patching process, but for now there's too much effort for seemingly zero benefit.
