### ISSUE TITLE
Error opening a product [Bug]

### ISSUE THREAD

**Issue by heberq1978** [FOSSBilling/FOSSBilling#704]
When clicking on the registered product link, the error is returning:

`League\CommonMark\MarkdownConverter::convert(): Argument #1 ($input) must be of type string, null given, called in /home/financeiro/domains/financeiro.hospedarsite.net.br/public_html/library/Box/TwigExtensions.php on line 309`

My Link hosting product: https://financeiro.hospedarsite.net.br/order/2

Thank You
Heber Queiroz

**Comment by BelleNottelling** [comment]
Fix has already been found and will be in the next release within the next 24 hours
