### ISSUE TITLE
Unable to view and use of Admin Panel on a Mobile Device ( Poco F1 )

### ISSUE THREAD

**Issue by DineshKandasamy2k21** [FOSSBilling/FOSSBilling#710]
Trying to use "foss-billing-installation.com/admin" on a mobile device

The Main Side Panel from the Admin Panel Disappears

The Logout / Profile Information Disappears.

Only remaining Orders - Users - Invoices - Payments are Visible.

Tried Google Chrome, Mozilla, Opera All Displaying above and Hiding the Actual Admin Side Panel.

But Was Able to Use The Side Panel Using A Desktop Browser App From Playstore.

So the problem is with either the Auto Scaling to resolution or with the Admin Panlel Code Itself.

**Comment by DineshKandasamy2k21** [comment]
The Resolution of Poco F1 Display is 1080 × 2280 Pixels

**Comment by DineshKandasamy2k21** [comment]
When the resolution of the display set to 1024 x 480 the above error occurs

**Comment by jaapmarcus** [comment]
Even with a iPhone it has multiple issues:
![IMG_0272](https://user-images.githubusercontent.com/9754650/213291263-0fa19119-5265-4625-8109-dc16e4d724cb.jpeg)

**Comment by yuhao7025** [comment]
Set css like this in .table for mobile：
```
.table {
    width: 100%;
    display: block;
    overflow-x: auto;
    white-space: nowrap;
}
```
The Logo part can be modified in line 133 of "layout default.html.twig", remove "d-flex" and see.

**Comment by BelleNottelling** [comment]
The navbar has been fixed, at this point the remaining issue is with the profile link being hidden and the main elements going off-screen if it's especially small
