### ISSUE TITLE
Error: IP is not allowed to connect with API (9999)

### ISSUE THREAD

**Issue by DineshKandasamy2k21** [FOSSBilling/FOSSBilling#717]
Fresh Installed FOSSbilling, created a package and added server IP with HestiaCP in it.

When I try to ping the server using the network icon from the server configuration it gives the following error:

> Connection Error: IP is not allowed to connect with API (9999)

Is there anything Missing on the server side? or is a flaw?

Note: Fossbilling is installed in the same server using HestiaCP as the Web Hosting CP

![IMG_20230120_115729](https://user-images.githubusercontent.com/122649062/213631755-b0294425-cf2e-4a70-8a97-83649b4ad266.jpg)

**Comment by BelleNottelling** [comment]
https://docs.hestiacp.com/admin_docs/api.html#unable-to-connect-to-the-api

You need to ensure the IP is listed in HestaiCP, I would list both the internal (loopback) IP as well as whatever public IP your server is behind
