### ISSUE TITLE
[Bug] Authentication Failed (201) when updating records ,only working with CSRFPrevention is set to false

### ISSUE THREAD

**Issue by DigitalVocano** [FOSSBilling/FOSSBilling#719]
**Authentication Failed (201)**
I cant handle domain and hosting configurations from my admin panel

**To Reproduce**
1. Go to Configurations.'
2. Click on 'Hosting plans and servers'
3. Navigate to 'New hosting plan'
4. Create Hosting Plan
5. Update Plan (NB the system will throw a 201 authentication error)

**Comment by DigitalVocano** [comment]
225d521 latest previe

**Comment by jaapmarcus** [comment]
That commit is allready over a week old. Please try the current last preview or update to 0.2.9

**Comment by DigitalVocano** [comment]
can l have the link to last last preview

**Comment by jaapmarcus** [comment]
I noticed a bug when clicking on: Save and Test connection on the edit server page:
![Screenshot 2023-01-20 at 13 23 41](https://user-images.githubusercontent.com/9754650/213694340-8b205502-df16-4861-9553-7dbbef118f85.png)

But I don't have any issues with Edit / Manage hosting plan
<img width="1053" alt="Screenshot 2023-01-20 at 13 27 06" src="https://user-images.githubusercontent.com/9754650/213694763-c109c38e-b720-41ed-b1ca-454346edd51c.png">

**Comment by BelleNottelling** [comment]
@DigitalVocano Please clear both your browser cache and FOSSBilling's cache.

**Comment by DigitalVocano** [comment]
The problem still exists after clearing the cache, changed the server aswell, tested on both nginx and none nginx server

**Comment by jaapmarcus** [comment]
I am not able to verify the issue

With Google Chrome
Please go to "Inspect" -> Network 
<img width="768" alt="Screenshot 2023-01-20 at 15 12 03" src="https://user-images.githubusercontent.com/9754650/213718657-0dc97d68-eaca-4125-a3e9-3e844f967e1e.png">

Make a post request via the form and check "Payload" it should include the CSRF token
<img width="617" alt="Screenshot 2023-01-20 at 15 14 39" src="https://user-images.githubusercontent.com/9754650/213718851-913ee8aa-e743-4fa8-bdb2-cff9faf00329.png">

**Comment by DigitalVocano** [comment]
server update and test connection throws {"result":null,"error":{"message":"Authentication Failed","code":201}}

**Comment by jaapmarcus** [comment]
Please try if you have the same issue at the demo.fossbilling.org

**Comment by DigitalVocano** [comment]
The Demo is loading an error,l have noticed the erro only happens when l try to update the record in hosting,payments,tax and domain

**Comment by jaapmarcus** [comment]
> The Demo is loading an error,l have noticed the erro only happens when l try to update the record in hosting,payments,tax and domain

What kind of error?

**Comment by DigitalVocano** [comment]
In demo mode its working fine.l have noticed that in my version the bug is on all update functions ,and the system is showing lm logged in as system cron but Im login in with my admin email and pwd,hence getting me in system cron account.In the Demo version lm logged in Demo account not system cron

**Comment by BelleNottelling** [comment]
> In demo mode its working fine.l have noticed that in my version the bug is on all update functions ,and the system is showing lm logged in as system cron but Im login in with my admin email and pwd,hence getting me in system cron account.In the Demo version lm logged in Demo account not system cron

I haven't heard anyone mention the "system cron" error in well over a year, since before we forked from BoxBilling. I thought it had been fixed by one of the many bug fixes we had made.

Please provide any and all information you can on your server setup, including what software you are using and what versions they are at, how you setup FOSSBilling, and what settings / changes you have made to FOSSBilling after installation.

**Comment by DigitalVocano** [comment]
l have intstalled the latest boxbilling stable release 0.2.9 on php 8
We downloaded the latest stable release,uploaded to cpanel account.extracted and visited the url and installed fossbilling.
However fossbilling installation is not moving to the finish stage,its throwing page unresponsive wait/exit,we chose to wait for more than five minutes ,nothing changed then we refreshed the page
All installation requirements has been detected as ok
we were running boxbilling before ,However we installed fossbilling as a new installation
After Installation we didnt change any setting but just logged in and navigate to Domains and try updating the .com TLD,then we are getting the erro.
Logging in using our admin email is getting us into system cron account,tried deleting the system cron from mysql database but upon refreshing the page its created again and automatically logged in.

Some output from error log are shared below

[21-Jan-2023 15:42:31 UTC] 8192 json_decode(): Passing null to parameter #1 ($json) of type string is deprecated /home/digitalvocano/public_html/f/modules/Invoice/ServicePayGateway.php 146
[21-Jan-2023 15:42:49 UTC] Authentication Failed 201
[21-Jan-2023 15:42:00 UTC] Cron hasn't been run in 56.27 minutes. Manually executing.
[21-Jan-2023 15:47:30 UTC] 8192 trim(): Passing null to parameter #1 ($string) of type string is deprecated /home/digitalvocano/public_html/f/library/Box/Tools.php 411

**Comment by BelleNottelling** [comment]
> l have intstalled the latest boxbilling stable release 0.2.9 on php 8
> We downloaded the latest stable release,uploaded to cpanel account.extracted and visited the url and installed fossbilling.
> However fossbilling installation is not moving to the finish stage,its throwing page unresponsive wait/exit,we chose to wait for more than five minutes ,nothing changed then we refreshed the page
> All installation requirements has been detected as ok
> we were running boxbilling before ,However we installed fossbilling as a new installation
> After Installation we didnt change any setting but just logged in and navigate to Domains and try updating the .com TLD,then we are getting the erro.
> Logging in using our admin email is getting us into system cron account,tried deleting the system cron from mysql database but upon refreshing the page its created again and automatically logged in.
> 
> Some output from error log are shared below
> 
> [21-Jan-2023 15:42:31 UTC] 8192 json_decode(): Passing null to parameter #1 ($json) of type string is deprecated /home/digitalvocano/public_html/f/modules/Invoice/ServicePayGateway.php 146
> [21-Jan-2023 15:42:49 UTC] Authentication Failed 201
> [21-Jan-2023 15:42:00 UTC] Cron hasn't been run in 56.27 minutes. Manually executing.
> [21-Jan-2023 15:47:30 UTC] 8192 trim(): Passing null to parameter #1 ($string) of type string is deprecated /home/digitalvocano/public_html/f/library/Box/Tools.php 411
> 
> 

I'd also like to know all of the following:
- Host OS
- Control panel software
- What's being used as a webserver (apache, nginx, ect)
- what software is running the DB?
- Is your server behind anything such as a CDN? If so, what?

**Comment by DigitalVocano** [comment]
> > l have intstalled the latest boxbilling stable release 0.2.9 on php 8
> > We downloaded the latest stable release,uploaded to cpanel account.extracted and visited the url and installed fossbilling.
> > However fossbilling installation is not moving to the finish stage,its throwing page unresponsive wait/exit,we chose to wait for more than five minutes ,nothing changed then we refreshed the page
> > All installation requirements has been detected as ok
> > we were running boxbilling before ,However we installed fossbilling as a new installation
> > After Installation we didnt change any setting but just logged in and navigate to Domains and try updating the .com TLD,then we are getting the erro.
> > Logging in using our admin email is getting us into system cron account,tried deleting the system cron from mysql database but upon refreshing the page its created again and automatically logged in.
> > Some output from error log are shared below
> > [21-Jan-2023 15:42:31 UTC] 8192 json_decode(): Passing null to parameter #1 ($json) of type string is deprecated /home/digitalvocano/public_html/f/modules/Invoice/ServicePayGateway.php 146
> > [21-Jan-2023 15:42:49 UTC] Authentication Failed 201
> > [21-Jan-2023 15:42:00 UTC] Cron hasn't been run in 56.27 minutes. Manually executing.
> > [21-Jan-2023 15:47:30 UTC] 8192 trim(): Passing null to parameter #1 ($string) of type string is deprecated /home/digitalvocano/public_html/f/library/Box/Tools.php 411
> 
> I'd also like to know all of the following:
> 
> * Host OS
> * Control panel software
> * What's being used as a webserver (apache, nginx, ect)
> * what software is running the DB?
> * Is your server behind anything such as a CDN? If so, what?

Host os is Linux i.e Cent OS 
Contro panel software is cpanel
Webserver we tried both Nginx and Apache
DB mysql 
No CDN

**Comment by DigitalVocano** [comment]
Host os is Linux i.e Cent OS
Contro panel software is cpanel
Webserver we tried both Nginx and Apache
DB mysql
No CDN

**Comment by BelleNottelling** [comment]
Interesting, I had seen it on CWP as well, back when I still used it.
I just generally had issues with it (such as with Nextcloud) and always thought it was something I did, but I'm now starting to wonder if there's something especially unique about that control panel that breaks software.

I'll spin up an issue about that as it would be worthwhile in investigating the issue. 

Regarding you upgrading to FOSSBilling, did you run the `foss-update.php` file? There are some updates that need to be made to the DB to ensure everything runs smoothly, and that file will process those for you.

Regarding this issue, I'd like to verify that you've cleared the cache of both FOSSBilling and your browser?
FOSSBilling cache can be manually cleared `/data/cache` or through the system settings

**Comment by BelleNottelling** [comment]
Disregard - I had my confused

**Comment by jaapmarcus** [comment]
> Host os is Linux i.e Cent OS
> Contro panel software is cpanel
> Webserver we tried both Nginx and Apache
> DB mysql
> No CDN

Do you have a cronjob setup?

**Comment by DigitalVocano** [comment]
More Details on the Error and Enviroments.
We tried on both Nginx and Apache server
Both cron enabled and Disabled
Both stable release and the source code version.
All requirements are enabled
our control panel is cpanel.
We tried all php versions from 8.0

NB. The script is freezing upon install and cant reach the finish page
      There are 59 tables in the database for the stable release version
      There are 60 tables in the database for the source code version
Box Billing is working fine but its taking us into system cron account aswell upon login.

**Comment by jaapmarcus** [comment]
> More Details on the Error and Enviroments. We tried on both Nginx and Apache server Both cron enabled and Disabled Both stable release and the source code version. All requirements are enabled our control panel is cpanel. We tried all php versions from 8.0
> 
> NB. The script is freezing upon install and cant reach the finish page There are 59 tables in the database for the stable release version There are 60 tables in the database for the source code version Box Billing is working fine but its taking us into system cron account aswell upon login.

Do you have a cronjob setup to execute cron.php at the moment?

**Comment by DigitalVocano** [comment]
yes,its configured,l have installed the souce code version

**Comment by DigitalVocano** [comment]
![cron](https://user-images.githubusercontent.com/123166151/213912396-d8727cf6-5c02-40c4-be77-96556c18748b.PNG)
cron.php throwing the error

**Comment by jaapmarcus** [comment]
Page not found looks like wrong cronjob... is wrong.

**Comment by DigitalVocano** [comment]
cron working ,error continues,cant execute update functions on the database

**Comment by DigitalVocano** [comment]
Executed when CSRFPrevention is set to false
Update On the issue
The Update function is failing to execute when the CSRFPrevention is set to true in config file.

l have an Api Token in my cpanel security aswell

**Comment by jaapmarcus** [comment]
Please check if this patch is working:

https://github.com/FOSSBilling/FOSSBilling/pull/769

**Comment by BelleNottelling** [comment]
Hello, @DigitalVocano, are you able to replicate this with the most recent FOSSBilling version?

**Comment by BelleNottelling** [comment]
Hey, @DigitalVocano 
Just checking in. It's been about a month since 0.3.0 was released, which should have included a fix for this issue.
I'll be closing this issue as resolved within the next few weeks if we don't hear back from you

**Comment by BelleNottelling** [comment]
Closing as resolved. If you are still experiencing this issue after the fixes is 0.3.0, please feel free to re-open this issue
