### ISSUE TITLE
There is no clear documentation on how to change Brand Logo & Company Name

### ISSUE THREAD

**Issue by DineshKandasamy2k21** [FOSSBilling/FOSSBilling#722]
Trying to change the default branding logo and Company name for both login page and admin panel, but to no avail couldn't find the configuration settings in the direct admin panel!

Should it changed directly on the filemamager of hosting or there is a better way in the admin panel!?

There should be clear neat and tidy documentation for changing default branding.

**Comment by John-S4** [comment]
It is in the admin panel. 

Configuration -> Settings -> System 

You will end up at yourdomain.comadmin/extension/settings/system There you can set two logos for light and dark modes. 

It does need to be better documented, and also just a neater settings system, but we will get to both, feel free to submit a PR for the docs.

**Comment by DineshKandasamy2k21** [comment]
I see it's hidden under the configuration -> settings -> system -> company details .

But its like hidden inside the visible options. Visible only if someone clicks on the "system" actually. 

It should be made visible directly under the "system" under "settings".
