### ISSUE TITLE
Unable to Login to Admin panel after auto updating to 0.2.9 [from 0.2.7]

### ISSUE THREAD

**Issue by DineshKandasamy2k21** [FOSSBilling/FOSSBilling#723]
I was working with settings on admin panel,

As I saw the notification for version 0.2.9 Update,

I updated using the auto updater module

I Logged out to check for logo changes

Now unable to login back to admin panel

I am sure the problem is from the update only

Because, previous to update I had no issue/bug/problem logging in to admin panel!

What's with the update?

Check the image attached, also, there is no message for submit login button action and unable to check or uncheck "Remember Me".

Now I am unable to login to my admin panel.

![IMG_20230121_031350](https://user-images.githubusercontent.com/122649062/213810835-8c4780d3-a795-4655-be60-1b97e7088090.jpg)

**Comment by DineshKandasamy2k21** [comment]
Using Redmi 9A,

Browser : Full-screen Desktop Web Browser

**Comment by DineshKandasamy2k21** [comment]
I see, the issue is with the browser and the update.

Until the update I was able to login from the said browser(desktop we browser)

But now I am able to login from other browser (opera) but not desktop web browser.

**Comment by jaapmarcus** [comment]
Check error logs. We are not able to "debug" from a distance

**Comment by DineshKandasamy2k21** [comment]
You may check it here [Mayoza Web Hosting](https://mayoza.com)

**Comment by DineshKandasamy2k21** [comment]
URL to admin panel [](https://billing.mayoza.com/admin)

**Comment by DineshKandasamy2k21** [comment]
URL to admin panel [Mayoza Billing](https://billing.mayoza.com/admin)

**Comment by jaapmarcus** [comment]
Send data looks fine I can't access the access / server logs.

**Comment by heberq1978** [comment]
Clear your browser's cache, that will solve the problem!

**Comment by DineshKandasamy2k21** [comment]
The issue is only solved after removing the browser app [desktop web browser] and reinstalling again from the playstore again.

I think there might be a issue with the update code and cache folder.

Anyone facing the same issue shall reinstall their browser or try to purge cache folder.
