### ISSUE TITLE
[Feature Request] Made the admin intro menu translatable and added to crowdin

### ISSUE THREAD

**Issue by yuhao7025** [FOSSBilling/FOSSBilling#725]
When I wanted to translate the menu, I found that many words were not found in crowdin, forming a mixture of two languages.

![image](https://user-images.githubusercontent.com/25569593/213848917-bc7a6a21-9ea8-4a72-a7cb-10745906c3fa.png)

![image](https://user-images.githubusercontent.com/25569593/213848948-826e6a1c-dfce-4195-a71d-fec0af1c9c2f.png)

Hope to make the menu translatable.

**Comment by BelleNottelling** [comment]
Just pushed the new strings to Crowdin, so these should be fully translatable.
