### ISSUE TITLE
There is a message " Please edit mod_servicehosting_order_form.html.twig file ", what should be done!?

### ISSUE THREAD

**Issue by DineshKandasamy2k21** [FOSSBilling/FOSSBilling#726]
Trying to add a product on both domain and hosting,

The following message come under "order form" section:

Please edit mod_servicehosting_order_form.html.twig file in order to change order form for hosting category products.

What exactly should be done to overcome this message in a proper manner!?

I was able to overcome this message by just RENAMING the .twig file to .html, and the problem is solved!

But I need to know that is the right approach or should there be better way to overcome this message!?

![IMG_20230121_192150](https://user-images.githubusercontent.com/122649062/213869970-ddb5648b-3d39-48f9-b4f0-31e7b9fe3ace.jpg)

**Comment by DineshKandasamy2k21** [comment]
This message shows up for all new products wether it is domain or hosting or custom

**Comment by BelleNottelling** [comment]
Editing it is optional and is only used to create a custom HTML order form.

**Comment by DineshKandasamy2k21** [comment]
No, I asked about wether to rename the file or to edit the file!?

**Comment by DineshKandasamy2k21** [comment]
Hey why you closed the issue, without proper answering it...!?
