### ISSUE TITLE
[Bug] after update 0.2.9 [ order page and total billing [fossbilling] site crashed to Gateway Error!

### ISSUE THREAD

**Issue by DineshKandasamy2k21** [FOSSBilling/FOSSBilling#733]
**Describe the bug**
updated the Fossbilling to 0.2.9
Tried to add a product from direct link and login with an already registered (registered before update) client account.
Got a message with no text ( just a black pop up on the right up corner) in it.

Then I tried to login from the client dashboard (Login or Register) to check if login works!

Entire site crashed to a Gateway Error.

Now unable to access the billing website [url : [Mayoza Billing](https://billing.mayoza.com) ]

**To Reproduce**
1. Go to 'main-fossbilling-installation.com'
2. Click on 'login'
3. See error

**Expected behavior**
I was looking to login as a client and make a sample order for a newly added product.

**Screenshots**
![IMG_20230122_013049](https://user-images.githubusercontent.com/122649062/213884982-2307e02d-4e83-4ea6-b29d-c85cdef287ed.jpg)

**Desktop (please complete the following information):**
 - OS: [Andoid 12]
 - Browser [Chrome]
 - Version [103]

**Smartphone (please complete the following information):**
 - Device: [Redmi 9A]
 - OS: [Android 12]
 - Browser [Google Chrome]
 - Version [103]

**Additional context**
I am looking at alternative or I will reinstall Fossbilling 0.2.7 back again.
Update 0.2.9 has lots of bugs out of the box.

**Comment by DineshKandasamy2k21** [comment]
Now it is loading,

But Login does not work again for client.

No message is showing in the popup message.

![IMG_20230122_014105](https://user-images.githubusercontent.com/122649062/213885380-a0b9f969-6dc3-43f5-9e4f-d7c6d87838ba.jpg)

**Comment by jaapmarcus** [comment]
Make sure to clear the cache

**Comment by DineshKandasamy2k21** [comment]
The problem still persists!

It happens then and there, 

Point to Note: other sites on my server still works good, but only fossbilling website and domain doesn't work it as intended with the above : Gateway Timeout error.

**Comment by jaapmarcus** [comment]
Check your error logs most likely you are using Hestia so https://forum.hestiacp.com/t/504-gateway-timeout/4819/3

**Comment by DineshKandasamy2k21** [comment]
The issue is still persisting.

Only when login the gateway error arises.

**Comment by evrifaessa** [comment]
I'm quite unsure if this is an issue on our end. We also can't really help much without server logs and more details about your stack.

**Comment by BelleNottelling** [comment]
Closing, per your other comment things are working fine for you.

**Comment by jaapmarcus** [comment]
HestiaCP has options for caching the static files a bit to well:
https://github.com/jaapmarcus/web-templates/blob/master/templates/nginx/nocache.tpl
https://github.com/jaapmarcus/web-templates/blob/master/templates/nginx/nocache.stpl

Also if the the cronjob doesn't run properly the system will probably timeout due to php execution time.
