### ISSUE TITLE
[Bug] Unable to create a successful order [ order status : failed setup ]

### ISSUE THREAD

**Issue by DineshKandasamy2k21** [FOSSBilling/FOSSBilling#734]
**Describe the bug**
Created a free hosting plan from admin panel
created a new client account from dashboard [using a different browser].
ordered the free hosting plan from dashboard of client area
chose the plan
chose the domain ( I will use my domain name.... )
clicked next
showed ( your account balance will be deducted )
clicked next
order made but showing : ORDER STATUS : FAILED SETUP [ in grey color ]

The panel used here is HestiaCP [ panel is connected with IP using API - successful connection test ]
API Key used is of from the admin user with root permissions inside HestiaCP.

**To Reproduce**
You may go to this address to reproduce the above error : url [Mayoza Billing](https://billing.mayoza.com/) 
1. Go to 'client area dashboard'
2. Click on 'create an order from the list'
3. After choosing the plans head to checkout.
4. See error " Failed Setup " in the dashboard of user.

**Expected behavior**
Expected to automatically create an account and corresponding Plan inside HestiaCP.

**Screenshots**
![IMG_20230122_022541](https://user-images.githubusercontent.com/122649062/213886845-be594054-83e4-45b2-95bf-e2d67d288ceb.jpg)

**Desktop (please complete the following information):**
 - OS: [Android 12]
 - Browser [Chrome]
 - Version [103]

**Smartphone (please complete the following information):**
 - Device: [Redmi 9A]
 - OS: [Android 12]
 - Browser [Google Chrome]
 - Version [103]

**Additional context**
You are allowed to test the error by creating account at [Mayoza Billing](https://billing.mayoza.com/) and order the "free" plan.

**Comment by jaapmarcus** [comment]
Check /var/log/hestia/error.log

**Comment by jaapmarcus** [comment]
Make sure to create a plan as well in Hestia and make it is sure the same name

**Comment by DineshKandasamy2k21** [comment]
I figured it out! but now again unable to login to the admin panel [desktop web browser]

Cleared the cache, cleared the cookies, and also cleared the history [just in case]

Yet, unable to login.

Sometimes it logins from other browsers and sometimes it doesn't login from any browsers!
