### ISSUE TITLE
New order via admin panel [Bug]

### ISSUE THREAD

**Issue by heberq1978** [FOSSBilling/FOSSBilling#737]
I am creating customer accounts, but when trying to link a new order to the user created, after filling in all the data such as: domain, user, hosting password, it is generating the following error and does not let me place the order:

**Domain name is not valid**

![erro-220123](https://user-images.githubusercontent.com/96161153/213905694-1ee46f3e-4e33-4393-8676-9b1f0c14473d.png)

No matter how, insert the domain, it's always giving the same error.

Thank You

**Comment by BelleNottelling** [comment]
![image](https://user-images.githubusercontent.com/17304943/213906343-0ed55565-eb8e-4726-bdcb-1483524e777a.png)

**Comment by BelleNottelling** [comment]
Looks like we just recently fixed it, patch will be in the next release
https://github.com/FOSSBilling/FOSSBilling/pull/709

**Comment by jaapmarcus** [comment]
Yes already patched the issue :)
