### ISSUE TITLE
Custom Fields do not appear [Bug]

### ISSUE THREAD

**Issue by heberq1978** [FOSSBilling/FOSSBilling#739]
I added two custom fields for the customer to fill in, but when accessing the customer's profile, these fields are not appearing, preventing them from being updated if necessary.
Another thing, the fields enabled for registration, such as date of birth, are not being filled in, looking like this:
00/00/0000

**Comment by jaapmarcus** [comment]
End point with the issue?

**Comment by heberq1978** [comment]
> End point with the issue?

I didn't understand what you meant.

**Comment by jaapmarcus** [comment]
Where can the url be found? Make searching easier

**Comment by jaapmarcus** [comment]
<img width="546" alt="Screenshot 2023-01-22 at 12 48 05" src="https://user-images.githubusercontent.com/9754650/213914166-5b46a97f-6129-4702-b523-35076a00c61e.png">
<img width="1150" alt="Screenshot 2023-01-22 at 12 47 12" src="https://user-images.githubusercontent.com/9754650/213914172-593ab157-b4d6-4811-9e5b-45f10931b3c2.png">

Looks to be working fine

**Comment by jaapmarcus** [comment]
It doesn't enter the placeholder I assume?

**Comment by heberq1978** [comment]
Ok, sorry I'm using Google to translate, I'm BR.
You created the test field, it appeared on the registration form, it appears for the admin, but in the customer's account, in his profile, this field does not appear. I'm using a custom field for the customer to register an alternative email.
However, if he needs to change this email, there is no way, because this custom field does not appear for him.
