### ISSUE TITLE
Payment gateway[Bug]

### ISSUE THREAD

**Issue by Kampende75** [FOSSBilling/FOSSBilling#744]
Hello! I added a payment gateway in library/adpter/payment gateways,  after adding it I went to Fossbilling admin area to activate it. I clicked on configuration then clicked on payment gateways, a new blank tab opened http://....../admin/invoice/gateways. Since it remained blanked for more than 3 minutes without showing any payment gateway, I went back to cpanel - file manager to delete the new payment gateway I added. After deleting it, i clicked again on payment gateways in admin area, then i got this error message **" ERROR
An exception has been thrown during the rendering of a template ("Payment gateway rave was not found")."**
![Screenshot from 2023-01-23 14-46-48](https://user-images.githubusercontent.com/87914373/214045429-d337f102-46bd-4fa2-9d4d-2daafd9fd51d.png)

**Comment by jaapmarcus** [comment]
Please share the code of the adapter..

**Comment by Kampende75** [comment]
> Please share the code of the adapter..

For which adapter?

**Comment by jaapmarcus** [comment]
For "rave" adapter you have uploaded

**Comment by jaapmarcus** [comment]
Also the correct path should be:
/src/libary/Payment/Adapter/

**Comment by Kampende75** [comment]
The thing is I cannot see other payment gateways now in admin area

**Comment by Kampende75** [comment]
> Also the correct path should be: /src/libary/Payment/Adapter/

[rave.zip](https://github.com/FOSSBilling/FOSSBilling/files/10479951/rave.zip)

**Comment by jaapmarcus** [comment]
You can't use the WHCMS adapter and expect it to be working

```
<?php
* Rave by Flutterwave Payment Gateway Module
 *
 * This Payment Gateway module allows you to integrate Rave payment solutions with the
 * WHMCS platform.
 *
 * For more information, please refer to the online documentation.
 *
 * @author Oluwole Adebiyi <flamekeed@gmail.com>
 *
 * @copyright Copyright (c) Oluwole Adebiyi 2017
 */



if (!defined("WHMCS")) {
    die("This file cannot be accessed directly");
}
?>
```

Delete the file you will need to develop the plugin your self. (Or hire somebody to do it)

**Comment by Kampende75** [comment]
> You can't use the WHCMS adapter and expect it to be working
> 
> ```
> <?php
> * Rave by Flutterwave Payment Gateway Module
>  *
>  * This Payment Gateway module allows you to integrate Rave payment solutions with the
>  * WHMCS platform.
>  *
>  * For more information, please refer to the online documentation.
>  *
>  * @author Oluwole Adebiyi <flamekeed@gmail.com>
>  *
>  * @copyright Copyright (c) Oluwole Adebiyi 2017
>  */
> 
> 
> 
> if (!defined("WHMCS")) {
>     die("This file cannot be accessed directly");
> }
> ?>
> ```
> 
> Delete the file you will need to develop the plugin your self. (Or hire somebody to do it)

Alright thank you. Everything was supposed to get back to normal after removing it though

**Comment by BelleNottelling** [comment]
> > You can't use the WHCMS adapter and expect it to be working
> > ```
> > <?php
> > * Rave by Flutterwave Payment Gateway Module
> >  *
> >  * This Payment Gateway module allows you to integrate Rave payment solutions with the
> >  * WHMCS platform.
> >  *
> >  * For more information, please refer to the online documentation.
> >  *
> >  * @author Oluwole Adebiyi <flamekeed@gmail.com>
> >  *
> >  * @copyright Copyright (c) Oluwole Adebiyi 2017
> >  */
> > 
> > 
> > 
> > if (!defined("WHMCS")) {
> >     die("This file cannot be accessed directly");
> > }
> > ?>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Delete the file you will need to develop the plugin your self. (Or hire somebody to do it)
> 
> Alright thank you. Everything was supposed to get back to normal after removing it though

You may need to remove it from the database. I believe the table is called payment_gateway
