### ISSUE TITLE
[Feature Request] Make admin area pages translatable

### ISSUE THREAD

**Issue by yuhao7025** [FOSSBilling/FOSSBilling#748]
Hello, when I was translating, I found that this page "/admin/system" could not be translated.

Is it possible to make it a translatable field?

![image](https://user-images.githubusercontent.com/25569593/214652123-ba83a8aa-c6f8-4567-aa27-a0de2c4d37ea.png)

**Comment by BelleNottelling** [comment]
So, in the linked PR I've made the navigation items under each item translatable, but the title is pulled from a json file rather than a PHP array, so making that translatable would be a more involved task and would likely require a mini restructuring of how everything is loaded
