### ISSUE TITLE
Login - system cron job [Bug]

### ISSUE THREAD

**Issue by Jonpwatson5** [FOSSBilling/FOSSBilling#763]
### Describe the bug

After running through the install, I tried to login using the new admin account I created during setup.

However, it logged in as the 'system Cron job' user with a random email address assignment.

I looked in the DB, deleted the user, deleted all the sessions and as soon as I login again (using the admin I created) it logs in as the crown again.  Upon looking in the DB in the admins table, a new user has been created again.

### How to reproduce

/admin
Enter admin login
Look in top right to see who is logged in

### Expected behavior

Log in as my admin user, not create a new user and login as that everytime 

### FOSSBilling version

0.2.10

### Device

Desktop

### Information

Microsoft edge 109.0.1518.70 (official build)

**Comment by BelleNottelling** [comment]
Hello, @Jonpwatson5 I have a theoretical fix for this, but I don't have the server setup to test it.
If you could please, modify your `di.php` with the changes here: https://github.com/FOSSBilling/FOSSBilling/pull/769/files

Let me know if that fixes the issue, thanks!

**Comment by BelleNottelling** [comment]
> > Hello, @Jonpwatson5 I have a theoretical fix for this, but I don't have the server setup to test it. If you could please, modify your `di.php` with the changes here: https://github.com/FOSSBilling/FOSSBilling/pull/769/files
> > Let me know if that fixes the issue, thanks!
> 
> This produces an error with a missing }
> 
> > > > > > ORIGINAL
> > > > > > [CODE]
> > > > > > $di['loggedin_admin'] = function () use ($di) {
> > > > > > if ('cli' === php_sapi_name() || str_starts_with(php_sapi_name(), 'cgi')) {
> > > > > > return $di['mod_service']('staff')->getCronAdmin();
> > > > > > }
> > > > > > [/CODE]
> 
> > > > > > NEW
> > > > > > [CODE]
> > > > > > $di['loggedin_admin'] = function () use ($di) {
> > > > > > if ('cli' === php_sapi_name() || str_starts_with(php_sapi_name(), 'cgi')) {
> > > > > > if ('cli' === php_sapi_name() || !http_response_code()) {
> > > > > > return $di['mod_service']('staff')->getCronAdmin();
> > > > > > }
> > > > > > }
> > > > > > [/CODE]
> 
> I can confirm this has fixed the issue.

Pretty sure you made a typo when copying the change over, there aren't any syntax errors in the proposed file: 
![image](https://user-images.githubusercontent.com/17304943/216031853-6db7d7b7-5b51-4ab3-b1d1-bdca0ade18c0.png)
