### ISSUE TITLE
[Bug] Can't edit IDN ccTLD

### ISSUE THREAD

**Issue by xinomilo** [FOSSBilling/FOSSBilling#770]
### Describe the bug

hey,

in a past fossbilling version, i added an idn top level domain ( (IDN ccTLD) .ελ - details in https://en.wikipedia.org/wiki/.gr#Alternative_top_domain )  
when trying to edit today with fully upgraded fossbilling (0.2.10), got a 404 : https://url/admin/servicedomain/tld/ελ

so, deleted tld, and readded (without errors), but still can't edit it. same 404. 

nothing on data/log/php_error.log : 
`[01-Feb-2023 23:20:35 timezone] Page /servicedomain/tld/ελ not found`

apache log : 
`[01/Feb/2023:23:20:35] GET /admin/servicedomain/tld/%CE%B5%CE%BB HTTP/2.0" 404 17134 "https://url/admin/servicedomain`

exactly the same applies for .ευ (https://en.wikipedia.org/wiki/.eu#Greek_domain) and any other IDN ccTLD i've tried. (even with cyrillic, not just greek characters). eg. .ею (https://en.wikipedia.org/wiki/.eu#Cyrillic_domain)

running on virtualmin host . Debian 11, apache2.4, Mariadb 10.5, php8.1

thanks in advance,

### How to reproduce

1. Go to /admin/servicedomain
2. Add any IDN ccTLD and save
3. Try to edit added IDN ccTLD

### Expected behavior

be able to edit ccTLDs/details. As TLDs prices/offers keep changing it doesn't seem wise to have to delete TLD + re-add each time. also not sure how/if such "workaround" would affect existing customers/orders (?)

### FOSSBilling version

0.2.10 (latest stable)

### Device

Desktop

### Information

- Device : PC
- OS : Debian testing amd64
- Browser : Firefox 
- Version : 109

**Comment by BelleNottelling** [comment]
Hi there, can you do me a favor and let me know what's in the `service_domain`  table in your database?

**Comment by jaapmarcus** [comment]
Issue is caused by:
https://github.com/FOSSBilling/FOSSBilling/blob/4d7b341e0396f8b34f0d758ddeee8f3291bcfaaf/src/modules/Servicedomain/Controller/Admin.php#L57

**Comment by xinomilo** [comment]
> Hi there, can you do me a favor and let me know what's in the `service_domain` table in your database?

service_domain table is empty.
tld table contains an entry for .ελ, which looks normal, just like any other TLD.

**Comment by jaapmarcus** [comment]
Our current match look like:

<img width="1226" alt="Screenshot 2023-02-02 at 09 08 38" src="https://user-images.githubusercontent.com/9754650/216267293-f91147ea-1487-474e-be00-e8b98fc15d9f.png">
