### ISSUE TITLE
[Bug]  Order Button code Doesnt work

### ISSUE THREAD

**Issue by GamenHaaDee** [FOSSBilling/FOSSBilling#777]
### Describe the bug

When i go to settings and the press ORDER BUTTON
![image](https://user-images.githubusercontent.com/75490815/216790643-bab75307-6051-47b5-801c-c77ad87527e0.png)

It doesnt generate any code for my site
![image](https://user-images.githubusercontent.com/75490815/216790652-ae1d5dfe-cc20-4e21-9921-1179fddd767a.png)

This worked on BoxBilling

### How to reproduce

1. Go to settings
2. Press Order Button
3. you wont see any code

### Expected behavior

I need to set the code there for you

### FOSSBilling version

Latest Stable

**Comment by jaapmarcus** [comment]
<img width="1426" alt="Screenshot 2023-02-04 at 22 44 52" src="https://user-images.githubusercontent.com/9754650/216790816-73d9e009-d882-4384-8d70-2a32ce507019.png">

Spectrum *** that has been removed but not completely

**Comment by jaapmarcus** [comment]
Fixed
