### ISSUE TITLE
[Bug] Timezone Error - Config File

### ISSUE THREAD

**Issue by tobsowo** [FOSSBilling/FOSSBilling#779]
### Describe the bug

When the timezone is changed to 'WAT' from 'UTC' it throws error in the user and admin UI but the timezone works when checking using the recent activity tab.

### How to reproduce

Change the time zone in config file

### Expected behavior

Should work as expected

### Screenshots

![image](https://user-images.githubusercontent.com/5642737/216791697-ac7d89d3-1dfb-40d4-9630-0ff74fcc857a.png)

![image](https://user-images.githubusercontent.com/5642737/216791713-42d418b2-56e6-419a-93db-906d5f70b625.png)

### FOSSBilling version

0.2.10

**Comment by BelleNottelling** [comment]
You need to find the right timezone as supported by PHP and use that, here's the complete list:
https://www.php.net/manual/en/timezones.php

**Comment by tobsowo** [comment]
Worked.
Thank you.
Since the default was UTC was expecting that WAT will work.

**Comment by jaapmarcus** [comment]
No need to keep it open maybe we should at a link with the supported time zones
