### ISSUE TITLE
[Bug]Fossbilling Site Says ok

### ISSUE THREAD

**Issue by AwesomePerson2** [FOSSBilling/FOSSBilling#781]
### Describe the bug

When trying to install fossbilling it gives the following error after i press next (i already entered mysql information)
![image](https://user-images.githubusercontent.com/112724753/216797239-e5c8dbec-202a-4c87-93ff-95478ff2001b.png)
after checking the mysql db nothing was inserted

### How to reproduce

1. go to fossbilling installation page
2. accept agreement and press next
3. enter mysql information
4. press next and see error

### Expected behavior

successfully set up mysql db

### Screenshots

![image](https://user-images.githubusercontent.com/112724753/216797261-d47f6542-9418-475b-9c8f-531c3e39a263.png)

### FOSSBilling version

0.2.10

**Comment by evrifaessa** [comment]
I don't really thing this is reproducible. If it still exists in a newer version, please reopen this issue.
