### ISSUE TITLE
[Feature Request] Add the ability to define payment adapter logo outside of CSS

### ISSUE THREAD

**Issue by jaapmarcus** [FOSSBilling/FOSSBilling#787]
### Describe the bug

<img width="659" alt="Screenshot 2023-02-06 at 13 05 09" src="https://user-images.githubusercontent.com/9754650/216967002-4260e3f8-65c2-4337-b8c5-85c249576d7e.png">

Stripe  / My plugin / Custom 

How ever current all logo's are hard coded in:
https://github.com/FOSSBilling/FOSSBilling/blob/main/src/themes/huraga/assets/css/logos.css

### How to reproduce

Download https://github.com/jaapmarcus/mollie-fossbilling and install it

Create a new invoice and try to pay as user

In the order page it has been solved by listing the payment providers as  text:

Pay with xxx

### Expected behavior

Ability to have the logo visible

### FOSSBilling version

N/A

**Comment by tobsowo** [comment]
This also happens with Paystack payment too

**Comment by jaapmarcus** [comment]
And it is hardcoded in:
https://github.com/FOSSBilling/FOSSBilling/blob/8863cb4b65c9b80800cb67dfdd3a35bd0adee4c2/src/modules/Invoice/html_client/mod_invoice_invoice.html.twig#L34

**Comment by jaapmarcus** [comment]
Existing Custom gateways need to update their code to support them: 

See: https://github.com/jaapmarcus/FOSSBilling/blob/be3ef9db36f8f9f72b25e7dffd037e6e94b85ea3/src/library/Payment/Adapter/Custom.php for the changes required
