### ISSUE TITLE
[Bug] Blank notification

### ISSUE THREAD

**Issue by xSido** [FOSSBilling/FOSSBilling#835]
### Describe the bug

in client login page, when you try to log in with a non existent account/email , you receive a blank notification.  
if u try an email that does not look like an email you are told that email address is not correct - proving that notifications work, but seems to be none for non existing emails

### How to reproduce

Client Log in page.
Try to log in with an email that does not exist.

### Expected behavior

It should show a message that the email you inserted is not existing / or good.

### FOSSBilling version

FOSSBilling 0.3.0

### Device

Desktop

### Information

Windows 10
Edge browser

**Comment by exp0logy** [comment]
@BelleNottelling 
Please assign to myself.
![image](https://user-images.githubusercontent.com/79308061/221390594-8641866a-8fdf-42a2-97d4-b19d7529ab0c.png)
