### ISSUE TITLE
[Feature Request] Add support GTM for client bootstrap theme

### ISSUE THREAD

**Issue by andpavlenko** [FOSSBilling/FOSSBilling#84]
For ability setup analytics need to add support Google Tag Manager for Bootstrap client theme.

**Comment by HunterNyan** [comment]
Should this be seperate from the SEO Module? Or even just a hook for the header like in Wordpress?

We could also build something similar to google sitekit as a seperate seo module for more functionality?

**Comment by jaapmarcus** [comment]
Ideally  you want to add support for multiple "providers" for example [Mamento](https://matomo.org)

**Comment by John-S4** [comment]
I was just about to write the same thing, this should be available for open source analytics solutions like Matomo as well as GA.

**Comment by evrifaessa** [comment]
We should set up hooks and not need to install these as modules.

**Comment by andpavlenko** [comment]
Seems like we don't understand each others.
I wrote "ability setup analytics" - this is not analytics! It's just ability to connect analytics which you want.
GTM it's container for connect custom scripts without change code of application. See: https://tagmanager.google.com/

**Comment by John-S4** [comment]
So, basically we are talking about an admin editable field in the backend to be able to enter scripts / meta tags / whatever, which will be added to the html head?

**Comment by andpavlenko** [comment]
> So, basically we are talking about an admin editable field in the backend to be able to enter scripts / meta tags / whatever, which will be added to the html head?
> That would mean that you could add any analytics script or anything else you liked really.

Almost, but not quite.
GTM its configurable container for scripts.
Used by all sited many years basically for analytics but could for everything external JS.

**Comment by John-S4** [comment]
Surely as a user this is more work than just having an input to add things to the head though. 

You have to both go to the Google Tag Manager admin and enter your scripts there and also add the tag manager container ID into FOSSB - why not just add directly in the FOSSD admin. 

You also aren't then making an extra external call to Google to achieve it, which would seem like an advantage. 

Or am I still missing something?

**Comment by HunterNyan** [comment]
I don't see any benefits in locking the user base into google when a simple hook in the header works best. Especially in the core of the application.

**Comment by BelleNottelling** [comment]
Closing since we removed this theme & we already have a separate request for SEO
https://github.com/FOSSBilling/FOSSBilling/issues/64
