### ISSUE TITLE
[Feature Request] Apple Pay

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#87]
Some providers like Stripe support Apple Pay.

https://stripe.com/docs/apple-pay

https://developer.apple.com/documentation/apple_pay_on_the_web

https://stripe.com/docs/stripe-js/elements/payment-request-button

**Comment by John-S4** [comment]
If you are going to add Apple Pay then it makes sense to add Google Pay as well. 

A few payment gateways support both.

**Comment by notbasetwo** [comment]
This seems like it would make more sense just to support Stripe Checkout et al, let them handle it so the platform doesn't have to keep chasing the latest and greatest payment methods.

Apple Pay/Google Pay is a bit of a pita to chase for every payment gateway.

**Comment by John-S4** [comment]
I was thinking the same thing, that it would make sense for this to be done by payment gateways rather than as a separate module.

**Comment by weismannweb** [comment]
https://github.com/FOSSBilling/FOSSBilling/issues/303

**Comment by weismannweb** [comment]
https://github.com/FOSSBilling/FOSSBilling/issues/303

**Comment by evrifaessa** [comment]
Seems better to let payment adapters handle it.
