### ISSUE TITLE
[Bug] form builder dropdown save elements

### ISSUE THREAD

**Issue by BradBot1** [FOSSBilling/FOSSBilling#891]
### Describe the bug

Trying to save a form dropdown/radio option displays an error and doesn't occur

### How to reproduce

Go to admin panel
Create a custom form
Create a dropdown/radio field
Click the edit button for the dropdown/radio
Click "Save"

### Expected behavior

The ability to save form dropdown/radio elements

### Screenshots

![image](https://user-images.githubusercontent.com/45739045/222929833-fee64ff6-b32f-4e7b-b05c-bc73c495b173.png)
![image](https://user-images.githubusercontent.com/45739045/222929817-2d851a8f-2c6c-4774-9d67-d7977f92c70e.png)

### FOSSBilling version

0.3.0

### Module version

formbuilder

### Device

Desktop

### Information

OS: Windows 11
Browser: Google Chrome 110.0.5481.178, MS Edge 110.0.1587.57
Version 0.3.0

### Additional context

This seems to be an error to-do with the actual submitting to the server as my network tools are saying that this is the data sent:
```json
{
    "CSRFToken": "********************",
    "name": "new_select_1",
    "label": "Dropdown 1",
    "labels[]": "",
    "values[]": "",
    "default_value": "",
    "description": "",
    "id": "1",
    "form_id": "1",
    "type": "select"
}
```

**Comment by BradBot1** [comment]
I believe I have found the cause!
![image](https://user-images.githubusercontent.com/45739045/222930950-61fd1f83-20b8-4ed4-bd8e-6236476a3c2e.png)
This code doesn't serialise the forms correctly, it skips the array stuff completely

**Comment by BradBot1** [comment]
I've mocked up a fix:
```javascript
const formDataObject = {};
for (const [key, value] of new FormData(event.currentTarget).entries()) {
    if (!formDataObject.hasOwnProperty(key)) {
        formDataObject[key] = value;
        continue;
    }
    // Ensure we have an array
    if (!Array.isArray(formDataObject[key])) formDataObject[key] = [ formDataObject[key] ];
    formDataObject[key].push(value);
}
const formDataInJSON = JSON.stringify(formDataObject);
```
Isn't the best but it works
![image](https://user-images.githubusercontent.com/45739045/222931080-06356b00-b7c7-444e-b905-48adbdf8997f.png)
A simple swap should fix it

**Comment by BradBot1** [comment]
Turns out php is not expecting the arrays to have brackets? This fixes it though
```javascript
const formDataObject = {};
for (const [key, value] of new FormData(event.currentTarget).entries()) {
    if (!key.endsWith("[]")) {
        formDataObject[key] = value;
        continue;
    }
    const trueKey = key.slice(0, -2);
    if (!formDataObject.hasOwnProperty(trueKey)) {
        formDataObject[trueKey] = [ value ];
        continue;
    }
    formDataObject[trueKey].push(value);
}
```

**Comment by BradBot1** [comment]
I've found the [responsible code](https://github.com/FOSSBilling/FOSSBilling/blob/540c46dfbb0b1674766b88a598eae1b132d73fa2/src/modules/Formbuilder/html_admin/mod_formbuilder_settings.html.twig#L358) and I'll make a pull request shortly with the changes

**Comment by jaapmarcus** [comment]
Migrating to the new api handler should be enough

https://github.com/FOSSBilling/FOSSBilling/blob/540c46dfbb0b1674766b88a598eae1b132d73fa2/src/themes/admin_default/assets/js/fossbilling.js

**Comment by BradBot1** [comment]
Oh, I didn't know about this

Is there any documentation on how to utilise it, because the [previous implementation](https://github.com/FOSSBilling/FOSSBilling/blob/540c46dfbb0b1674766b88a598eae1b132d73fa2/src/modules/Formbuilder/html_admin/mod_formbuilder_settings.html.twig#L353-L368) was embedded

**Comment by jaapmarcus** [comment]
It is replacing the form element as:
https://github.com/FOSSBilling/FOSSBilling/blob/eb2cbf4120ff570e87711d7557aac218e17cb631/src/modules/Servicehosting/html_admin/mod_servicehosting_config.html.twig#L5

But probally the form need also an update to make it look like the current admin theme

**Comment by BradBot1** [comment]
The theming can come later I'd rather make sure it at least works but I do agree that it needs some changes (for instance I'd love #886 )

**Comment by BradBot1** [comment]
I've been looking and it [already has the syntax given in the snippet](https://github.com/FOSSBilling/FOSSBilling/blob/eb2cbf4120ff570e87711d7557aac218e17cb631/src/modules/Formbuilder/html_admin/mod_formbuilder_settings.html.twig#L134) and I am unsure of what else to change

**Comment by BelleNottelling** [comment]
Hello, @BradBot1 
The changes in pull request #893 should resolve this issue for you.

**Comment by BradBot1** [comment]
Oh thanks! What did you change to male it work?

**Comment by jaapmarcus** [comment]
See changes:
https://github.com/FOSSBilling/FOSSBilling/pull/893/commits/72715ccfc9f7322816da0df8865fc938a7275c5f
