### ISSUE TITLE
Migration error thing appears for no reason even though I didn't migrate.

### ISSUE THREAD

**Issue by Linuspro** [FOSSBilling/FOSSBilling#936]
I've had 2 installations of Foss Billing and this issue is making me want to switch back to Box Billing.  
https://hostinghaven.us/  
I can't even explain what's happening, maybe have 2 different options? Like, 2 separate packages, 1 for a standalone install and 1 for a migration install.  
I got A fresh install of Foss billing with no trace of box billing, but here my website is, stuck with a migration error.  
In the mean time I'll be using Box billing.

**Comment by BelleNottelling** [comment]
Connected via discord and found the issue :)
