### ISSUE TITLE
[Bug] Date picker cannot be empty

### ISSUE THREAD

**Issue by epichosts** [FOSSBilling/FOSSBilling#938]
### Describe the bug

On a custom product, when editing an order through the 'Edit order' tab, the 'Expires at', 'Created at', and 'Activated at' forms are using the date picker. This form does not allow for an empty form to be submitted, as it will revert back to it last setting.

It is important to note that this issue **does not** occur on the client-side of the panel (ie: the client's profile page). The issue only seems to occur on the admin-side of the panel.

### How to reproduce

1. Go to any order using the 'Custom' product type.
2. Press the 'Edit order' tab.
3. Find the fields using a date picker, and if they do not have a date selected already, select a date and save, then try to empty the field and save again. You will see that after a refresh the original date still appears.

### Expected behavior

For the field to be empty and not use the original date.

### FOSSBilling version

0.3.0 (the latest stable release)

### Device

Desktop

### Information

This issue happens on all devices.

**Comment by admdly** [comment]
Thanks for this report - I can see the issue (and a few others). I plan to resolve this, and the various related issues, sometime this week.
