### ISSUE TITLE
[Feature Request] Send e-mail to staff when service is suspended

### ISSUE THREAD

**Issue by epichosts** [FOSSBilling/FOSSBilling#949]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
When a service is suspended due to lack of renewal (ie: when an order is not renewed), there is no feature or setting to have staff notified when a service is suspended. It would be very useful to have an e-mail template (or some form of notification) where staff cna be notified when a service is suspended.

**Describe alternatives you've considered**
I have tried copying the code which sends the suspension e-mail to clients, by making it send an e-mail to staff through a separate template instead. This works to an extent however it is very glitchy and occasionally it will cause a suspension e-mail to just not send to either the client or staff. 

**Additional context**
N/A

**Comment by Anuril** [comment]
This could be looked at when improving #1261 / #997

**Comment by John-S4** [comment]
Folded into #1675
