### ISSUE TITLE
Client unable to update profile

### ISSUE THREAD

**Issue by tobsowo** [FOSSBilling/FOSSBilling#971]
### Describe the bug

When client try to update profile, they get this error:
`Client API call update does not exist in module client`

### How to reproduce

Try to edit the client profile and save.

### Expected behavior

The client data should be updated.

### FOSSBilling version

0.3

**Comment by BelleNottelling** [comment]
This has been patched in the development branch and the fix will be in version 0.4.0

**Comment by tobsowo** [comment]
Noted. Thank you.
