### ISSUE TITLE
[Bug] SQLSTATE[42000]: Syntax error or access violation 

### ISSUE THREAD

**Issue by m-primo** [FOSSBilling/FOSSBilling#994]
### Describe the bug

Whenever I try to install I get this error.
![Untitled](https://user-images.githubusercontent.com/44984918/227613462-e359251e-c032-4f9d-adf3-ec46461d9d40.png)

And when I click again, I get this error:
![2Untitled](https://user-images.githubusercontent.com/44984918/227613564-ab5768c7-d4db-4136-bdec-f6a71f71a1a1.png)

So, the database installed with all the tables correctly.

When I remove the install directory to see if I can access, and navigate to the admin panel, I get this:
![3Untitled](https://user-images.githubusercontent.com/44984918/227614017-ad37d28f-d7d5-4f8f-8430-e259dc29cb18.png)

I have no idea what is that!

### How to reproduce

All you have to do is just download and follow the "Download the latest preview build" steps.

I tried many times with different things to download:

1. latest release
2. preview build
3. git version (with composer install and other source code steps)

So to reproduce the issue:

1. Download the preview build / latest release.
2. Unzip to your public web directory.
3. go to `/install` in your browser.
4. Enter credentials.
5. Click next. And it'll show.

### Expected behavior

Installation should complete.

### FOSSBilling version

preview

### Information

- OS: Centos 7.9.2009
- Web Server: Apache 2.4.55
- MySQL version: MariaDB 10.4.28

### Additional context

Note: I had the same error with your old fork BoxBilling!

**Comment by BelleNottelling** [comment]
The SQL installation process happens with 3 distinct steps:
1. It creates the empty tables based off the [structure.sql](https://github.com/FOSSBilling/FOSSBilling/blob/main/src/install/sql/structure.sql) file. At this stage, all tables are completely empty and do not have any of their required rows
2. It imports the [content.sql](https://github.com/FOSSBilling/FOSSBilling/blob/main/src/install/sql/content.sql) file. At this stage, *most* of the required SQL work is done, but still not enough to have a functional FOSSBilling instance.
3. Finally, it replaces with default USD currency in the database with whatever you entered during the install process and creates a new entry in the `admin` table to create your admin account with the credentials you entered.

Judging by the error messages you get, the installer is able to create the empty tables, but it doesn't have permissions to actually write to the tables, and then fails at the 2nd step.

You need to check the permissions that user has for the database, it sounds like it can create tables, but it cannot write to them.

I see you have CentOS for the OS, are you using CWP? From what I remember (from a few years back), the initial DB user set up didn't actually display all of the available permissions on the setup screen and I had to go back in and add in the few remaining permissions before it worked.

**Comment by m-primo** [comment]
@BelleNottelling 

> I see you have CentOS for the OS, are you using CWP? From what I remember (from a few years back), the initial DB user set up didn't actually display all of the available permissions on the setup screen and I had to go back in and add in the few remaining permissions before it worked.

Yes for this I'm using CWP.. It does have permission setup screen now, but if it's only problem with permission I'll try to solve it manually from the command line and see what will happen.


I'll reply back with the results.

**Comment by m-primo** [comment]
@BelleNottelling I can confirm now that it's working as expected.

I noticed that the CWP adding the permissions to wrong database name.. for example the name of the database contains underscore `_`, it get escaped to be like `\_`, so it gives the permission to a wrong database.

After I fixed this issue, everything worked correctly.

Thanks.

**Comment by BelleNottelling** [comment]
> @BelleNottelling I can confirm now that it's working as expected.
> 
> I noticed that the CWP adding the permissions to wrong database name.. for example the name of the database contains underscore `_`, it get escaped to be like `\_`, so it gives the permission to a wrong database.
> 
> After I fixed this issue, everything worked correctly.
> 
> Thanks.

Awesome, glad you got it figured out
