### ISSUE TITLE
[Feature Request] Grace days after expiration

### ISSUE THREAD

**Issue by heberq1978** [FOSSBilling/FOSSBilling#997]
I'm using version 3.0 and it's excellent, but after expiry the client's hosting is instantly blocked.
There is no field where it could be configured so that after expiration, block the account after 7 days.
If this configuration exists, I ask you to pass me the location, because I did not find it anywhere.
It really is the way it is, but here in Brazil, other hosting companies have already got their customers used to it, there are companies that leave the service enabled for up to 120 days after expiration.

Thank You
Heber Queiroz

**Comment by heberq1978** [comment]
> BR - Eu não sei ao certo mais será que não é isso? EN- I don't know for sure but is it not? ![Configurações-da-fatura-Novacast](https://user-images.githubusercontent.com/58113324/228323466-645b3bbc-5a84-406f-96e4-34221c6fb4b8.png)

Grande muito obrigado pelo seu retorno, vou estar testando a sua dica !

**Comment by John-S4** [comment]
> EN- I don't know for sure but is it not?

It isn't exactly - that is the number of days after an invoice is issued that the client has to pay the invoice. 

Logically there should then be an overdue reminder sent out if it has not been paid, and then suspension a configurable number of days after that if it still not paid.

**Comment by John-S4** [comment]
Folded into #1675
